<x-layouts.core>
    <main class="min-h-screen bg-secondary px-4 py-12 text-primary sm:px-6">
        <div class="mx-auto max-w-5xl">
            <a href="{{ url('/') }}" class="text-sm font-bold text-ternary">← {{ config('app.name') }}</a>
            <header class="mt-6"><p class="text-xs font-bold uppercase tracking-widest text-ternary">API v1</p><h1 class="mt-2 text-4xl font-black">{{ __('Control plane API') }}</h1><p class="mt-3 max-w-2xl text-secondary">{{ __('Automate projects, deployments, runtime state, scaling, and workflow configuration with scoped Bearer tokens.') }}</p><a href="/openapi.json" class="button primary mt-5 inline-flex" download>{{ __('Download OpenAPI specification') }}</a></header>
            <section class="mt-10 rounded-2xl border border-primary bg-primary p-6"><h2 class="text-xl font-black">{{ __('Authentication') }}</h2><pre class="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-sm text-slate-100"><code>Authorization: Bearer YOUR_TOKEN
Accept: application/json</code></pre><p class="mt-3 text-sm text-secondary">{{ __('Create named read, deploy, or manage tokens from Automation. Tokens are shown once and can be rotated or revoked.') }}</p></section>
            <section class="mt-6 overflow-hidden rounded-2xl border border-primary bg-primary"><div class="border-b border-primary p-5"><h2 class="text-xl font-black">{{ __('Endpoints') }}</h2></div>@foreach([['GET','/api/v1/me','read','Current user and workspace'],['GET','/api/v1/projects','read','List applications and environments'],['GET','/api/v1/projects/{project}','read','Get an application'],['PUT','/api/v1/projects/{project}/workflow','manage','Apply buildpusher.yaml'],['GET','/api/v1/deployments','read','List recent deployments'],['GET','/api/v1/deployments/{build}','read','Get a deployment'],['POST','/api/v1/environments/{environment}/deploy','deploy','Queue a deployment'],['PATCH','/api/v1/environments/{environment}/scale','manage','Change desired capacity'],['PATCH','/api/v1/environments/{environment}/runtime','manage','Hibernate or resume']] as [$method,$path,$scope,$description])<article class="grid gap-2 border-b border-primary p-5 last:border-0 sm:grid-cols-[5rem_1fr_8rem] sm:items-center"><span class="w-fit rounded bg-secondary px-2 py-1 font-mono text-xs font-bold">{{ $method }}</span><div><code class="break-all text-sm text-primary">{{ $path }}</code><p class="mt-1 text-xs text-secondary">{{ __($description) }}</p></div><span class="text-xs font-bold text-ternary">{{ $scope }}</span></article>@endforeach</section>
            <section class="mt-6 rounded-2xl border border-primary bg-primary p-6"><h2 class="text-xl font-black">{{ __('Request example') }}</h2><pre class="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-sm text-slate-100"><code>curl -X POST \
  -H "Authorization: Bearer $BUILDPUSHER_TOKEN" \
  -H "Accept: application/json" \
  {{ url('/api/v1/environments/1/deploy') }}</code></pre></section>
        </div>
    </main>
</x-layouts.core>
