<x-layouts.core :title="__('Product guide')" :description="__('Move from an empty workspace to a verified release with a safe operational workflow.')" :livewire="false">
    <a href="#main-content" class="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-primary focus:px-4 focus:py-3 focus:font-semibold focus:text-primary focus:shadow-xl">
        {{ __('Skip to main content') }}
    </a>
    <main id="main-content" tabindex="-1" class="min-h-screen bg-secondary px-4 py-10 text-primary sm:px-6">
        <div class="mx-auto max-w-6xl">
            <div class="flex flex-wrap items-center justify-between gap-3"><a href="{{ auth()->check() ? route('dashboard') : url('/') }}" class="inline-flex min-h-[2.5rem] items-center font-bold text-ternary">← {{ config('app.name') }}</a><div class="flex flex-wrap gap-2"><x-ui.button href="#troubleshooting" variant="secondary">{{ __('Troubleshooting') }}</x-ui.button><x-ui.button :href="route('api-docs')" variant="secondary">{{ __('API reference') }}</x-ui.button></div></div>
            <header class="mt-8 max-w-3xl"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Getting started') }}</p><h1 class="mt-2 text-4xl font-black">{{ __('From empty workspace to verified release') }}</h1><p class="mt-3 text-base leading-7 text-secondary">{{ __('Follow the shortest safe path first. Add automation, scaling, and team controls after one manual release and recovery drill succeed.') }}</p></header>
            <details id="guide-contents" class="ui-card group mt-8 overflow-hidden">
                <summary class="flex cursor-pointer list-none items-center justify-between gap-4 px-4 py-3 font-bold text-primary [&::-webkit-details-marker]:hidden">
                    <span>{{ __('On this page') }}</span>
                    <span class="flex items-center gap-2 text-sm font-normal text-secondary"><span>{{ __('6 guide sections') }}</span><span class="text-lg leading-none transition group-open:rotate-45" aria-hidden="true">+</span></span>
                </summary>
                <nav class="grid gap-2 border-t border-primary p-4 sm:grid-cols-2 lg:grid-cols-3" aria-label="{{ __('Guide sections') }}">
                    @foreach ([['quick-start', __('Quick start')], ['first-deploy', __('First deployment')], ['operations', __('Daily operations')], ['recovery', __('Recovery')], ['security', __('Release checklist')], ['troubleshooting', __('Troubleshooting')]] as [$anchor, $label])
                        <a href="#{{ $anchor }}" class="rounded-xl border border-primary bg-secondary px-4 py-3 font-bold text-primary hover:border-ternary">{{ $label }}</a>
                    @endforeach
                </nav>
            </details>

            <section id="quick-start" class="mt-6 scroll-mt-6 rounded-2xl border border-primary bg-primary p-6"><div class="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Ten-minute orientation') }}</p><h2 class="mt-2 text-2xl font-black">{{ __('Know where things live') }}</h2><p class="mt-3 leading-7 text-secondary">{{ __('Applications group environments. Sites own domains and health checks. Repositories produce releases. Observability and Backups retain operational evidence.') }}</p></div><div class="grid gap-3 sm:grid-cols-2">@foreach([[__('⌘K / Ctrl K'),__('Search resources and open common actions.')],[__('Applications'),__('Configure runtime, secrets, processes, and release controls.')],[__('Observability'),__('Review metrics, logs, incidents, status pages, and alerts.')],[__('Send feedback'),__('Privately report a bug or confusing workflow from any page.')]] as [$title,$text])<div class="rounded-xl border border-primary bg-secondary p-4"><h3 class="font-black">{{ $title }}</h3><p class="mt-1 text-sm leading-6 text-secondary">{{ $text }}</p></div>@endforeach</div></div></section>

            <div class="mt-6 grid gap-6 lg:grid-cols-2">
                <section id="first-deploy" class="scroll-mt-6 rounded-2xl border border-primary bg-primary p-6"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Start here') }}</p><h2 class="mt-1 text-xl font-black">{{ __('First deployment') }}</h2><ol class="mt-4 list-decimal space-y-3 pl-5 leading-6 text-secondary"><li>{{ __('Connect DigitalOcean, Hetzner, or Vultr and use Test connection.') }}</li><li>{{ __('Provision Ubuntu, or import an existing Ubuntu server using an SSH key.') }}</li><li>{{ __('Create a site, point DNS to its public IP, and enable a health path that returns 2xx.') }}</li><li>{{ __('Connect GitHub, GitLab, or Bitbucket; choose the exact repository and branch.') }}</li><li>{{ __('Configure the runtime and secrets, then review the deployment preflight snapshot.') }}</li><li>{{ __('Deploy manually, inspect every stage, and confirm the post-release health result.') }}</li></ol></section>
                <section id="operations" class="scroll-mt-6 rounded-2xl border border-primary bg-primary p-6"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Repeat safely') }}</p><h2 class="mt-1 text-xl font-black">{{ __('Daily operations') }}</h2><ul class="mt-4 list-disc space-y-3 pl-5 leading-6 text-secondary"><li>{{ __('Use approval, release locks, and maintenance windows for production changes.') }}</li><li>{{ __('Watch the deployment timeline, searchable logs, health history, and server metrics together.') }}</li><li>{{ __('Set alert thresholds and send failures and recoveries to an external destination.') }}</li><li>{{ __('Use buildpusher.yaml, scoped API tokens, the CLI, or MCP only after the manual path works.') }}</li><li>{{ __('Review cost estimates and hibernate truly idle environments; treat the provider invoice as authoritative.') }}</li></ul></section>
                <section id="recovery" class="scroll-mt-6 rounded-2xl border border-primary bg-primary p-6"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Practice before failure') }}</p><h2 class="mt-1 text-xl font-black">{{ __('Recovery drill') }}</h2><ol class="mt-4 list-decimal space-y-3 pl-5 leading-6 text-secondary"><li>{{ __('Configure an offsite S3-compatible destination and a bounded retention schedule.') }}</li><li>{{ __('Run a backup and wait for a verified snapshot identifier and size.') }}</li><li>{{ __('Restore into a disposable environment; confirm the safety snapshot and health verification complete.') }}</li><li>{{ __('Deploy a known release, then perform an exact-release rollback.') }}</li><li>{{ __('Record root cause, remediation, follow-up owner, recovery point, and observed restore time.') }}</li></ol><p class="mt-4 rounded-lg bg-secondary p-3 text-sm text-secondary">{{ __('Automatic rollback protects an activated release, but it does not replace tested offsite recovery.') }}</p></section>
                <section id="security" class="scroll-mt-6 rounded-2xl border border-primary bg-primary p-6"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Before inviting users') }}</p><h2 class="mt-1 text-xl font-black">{{ __('Release and security checklist') }}</h2><ul class="mt-4 space-y-3 leading-6 text-secondary">@foreach([__('APP_DEBUG is off and HTTPS/HSTS are verified.'),__('SMTP sender, password reset, verification, invitation, and alert emails are tested.'),__('Independent uptime and heartbeat monitors run outside this server.'),__('Every administrator uses two-factor authentication and stores recovery codes offline.'),__('Members have the smallest role required; old sessions and API tokens are revoked.'),__('Secret rotation dates, backup retention, log retention, and rate limits are reviewed.'),__('A real provider provision, deploy, rollback, backup, and restore drill has passed.'),__('Stripe remains disabled until product and price identifiers are approved.')] as $item)<li class="flex gap-3"><span class="text-ternary">□</span><span>{{ $item }}</span></li>@endforeach</ul></section>
            </div>

            <section id="troubleshooting" class="mt-6 scroll-mt-6 rounded-2xl border border-primary bg-primary p-6"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Decision guide') }}</p><h2 class="mt-1 text-2xl font-black">{{ __('Troubleshooting') }}</h2><p class="mt-2 text-sm leading-6 text-secondary">{{ __('Start with the visible resource state and retained evidence. Do not rerun repeatedly before understanding whether remote work is still active.') }}</p><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[44rem] text-left text-sm"><thead><tr class="border-b border-primary text-xs uppercase text-secondary"><th class="p-3">{{ __('Symptom') }}</th><th class="p-3">{{ __('Check first') }}</th><th class="p-3">{{ __('Safe next action') }}</th></tr></thead><tbody>@foreach([[__('Provider connection failed'),__('Connection history and credential scope'),__('Test once; rotate only if the provider rejects the credential.')],[__('Server provisioning stopped'),__('Provisioning stage, streamed log, cloud console'),__('Retry only the eligible failed phase; do not create a duplicate server.')],[__('Deployment is waiting'),__('Approval, release lock, maintenance window, active site build'),__('Resolve the explicit guardrail or cancel the queued request.')],[__('Deployment failed before activation'),__('Preflight snapshot and deployment log'),__('Correct configuration, then redeploy the exact revision.')],[__('Health failed after activation'),__('Health path, runtime log, latest server metrics'),__('Follow automatic recovery, or roll back to a retained successful release.')],[__('Site is unreachable'),__('DNS A/AAAA records, certificate inspection, load-balancer nodes'),__('Fix the failing layer; avoid changing DNS and application state together.')],[__('Backup or restore failed'),__('Destination verification and retained job error'),__('Preserve the current site, correct credentials/capacity, then retry once.')],[__('Unexpected 500 response'),__('The safe incident reference in the response'),__('Give the reference to an administrator; never paste secrets into feedback.')]] as [$symptom,$check,$action])<tr class="border-b border-primary align-top"><td class="p-3 font-bold text-primary">{{ $symptom }}</td><td class="p-3 text-secondary">{{ $check }}</td><td class="p-3 text-secondary">{{ $action }}</td></tr>@endforeach</tbody></table></div><div class="mt-5 flex flex-wrap gap-3">@auth<x-ui.button :href="route('system-health.index')" variant="secondary">{{ __('Open system health') }}</x-ui.button><x-ui.button :href="route('feedback.index', ['from' => '/docs'])" variant="primary">{{ __('Report a problem') }}</x-ui.button>@endauth<x-ui.button :href="route('platform-status.show')" variant="secondary">{{ __('Public platform status') }}</x-ui.button></div></section>
        </div>
    </main>
</x-layouts.core>
