@extends('monitor::layouts.app')
@section('title', $series->name)
@section('breadcrumb', 'Metrics')
@section('content')
@php
    $validPoints = collect($chart['points'])->filter(fn ($point) => $point['value'] !== null);
    $polyline = $validPoints->map(fn ($point) => $point['x'].','.$point['y'])->implode(' ');
    $anomalyPoints = $validPoints->filter(fn ($point) => ($point['anomaly']['state'] ?? null) === 'anomaly');
@endphp
<div class="space-y-6">
    <a href="{{ route('monitor.metrics.index') }}" class="text-xs font-bold text-primary hover:underline dark:text-primary">← Metrics</a>
    <x-monitor::ui.page-header :eyebrow="$series->environment->application->name.' / '.$series->environment->name" :title="$series->name" :description="$series->resource_label.' · '.($series->unit ?: 'unitless').' · '.$series->kind.($series->temporality ? ' / '.$series->temporality : '')">
        <x-slot:actions><x-monitor::ui.button :href="route('monitor.alerts.create', ['series' => $series->id])">Create numeric alert</x-monitor::ui.button></x-slot:actions>
    </x-monitor::ui.page-header>
    <form method="GET" action="{{ route('monitor.metrics.show', $series) }}" class="ui-panel flex flex-wrap items-end gap-4 p-5"><x-monitor::ui.select name="range" label="Range" :value="$filters['range']" :options="$rangeOptions" /><x-monitor::ui.select name="mode" label="Display" :value="$filters['mode']" :options="['value' => 'Recorded value', 'rate' => 'Counter rate']" /><x-monitor::ui.button>Refresh chart</x-monitor::ui.button></form>
    <section class="ui-panel p-5">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-bold">{{ $filters['mode'] === 'rate' ? 'Rate over time' : 'Value over time' }}</h2><p class="mt-1 text-xs text-muted dark:text-subtle">{{ number_format($chart['valid']) }} usable points · {{ $from->toISOString() }} → {{ $until->toISOString() }}</p></div>@if($chart['truncated'])<x-monitor::ui.badge tone="amber">Chart capped at 600 points</x-monitor::ui.badge>@endif</div>
        @if($polyline !== '')
            <div class="mt-6 overflow-x-auto rounded-control bg-surface-muted p-3"><svg viewBox="0 0 1000 200" class="h-64 min-w-[720px] w-full" role="img" aria-label="Metric chart"><line x1="0" y1="20" x2="1000" y2="20" class="stroke-line" /><line x1="0" y1="100" x2="1000" y2="100" class="stroke-line" /><line x1="0" y1="180" x2="1000" y2="180" class="stroke-line" /><polyline points="{{ $polyline }}" fill="none" class="stroke-primary" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" />@if($anomalyDetectionEnabled)@foreach($anomalyPoints as $point)<circle cx="{{ $point['x'] }}" cy="{{ $point['y'] }}" r="5" class="fill-warning stroke-surface" stroke-width="2"><title>{{ ucfirst($point['anomaly']['direction'] ?? 'unusual') }} shift · score {{ number_format($point['anomaly']['score'] ?? 0, 2) }}×</title></circle>@endforeach @endif</svg></div>
            <dl class="mt-4 grid gap-4 text-sm sm:grid-cols-3"><div><dt class="text-xs text-muted dark:text-subtle">Minimum</dt><dd class="mt-1 font-semibold">{{ $chart['minimum'] === null ? '—' : number_format($chart['minimum'], 4) }}</dd></div><div><dt class="text-xs text-muted dark:text-subtle">Maximum</dt><dd class="mt-1 font-semibold">{{ $chart['maximum'] === null ? '—' : number_format($chart['maximum'], 4) }}</dd></div><div><dt class="text-xs text-muted dark:text-subtle">Latest usable point</dt><dd class="mt-1 font-semibold">{{ $chart['latest']['value'] === null ? '—' : number_format($chart['latest']['value'], 4) }}</dd></div></dl>
        @else
            <p class="mt-6 rounded-control bg-surface-muted p-8 text-center text-sm text-muted dark:bg-surface-muted dark:text-subtle">No usable points in this range. Missing values, unsupported distributions, counter resets and conflicting samples remain visible below as unknown states.</p>
        @endif
    </section>
    @if($anomalyDetectionEnabled)
        <section class="ui-alert ui-alert-warning block p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-bold text-warning dark:text-warning">Anomaly detection</h2><p class="mt-1 max-w-3xl text-xs leading-5 text-warning dark:text-warning">A robust rolling baseline uses the previous valid points in this range. It needs {{ \App\Modules\Monitor\Services\MetricAnomalyDetector::MINIMUM_BASELINE_POINTS }} points before it can classify a shift, and it never changes the recorded value.</p></div>@if($chart['anomalies'] > 0)<x-monitor::ui.badge tone="amber">{{ $chart['anomalies'] }} unusual {{ $chart['anomalies'] === 1 ? 'point' : 'points' }}</x-monitor::ui.badge>@else<x-monitor::ui.badge tone="emerald">No unusual shifts</x-monitor::ui.badge>@endif</div>@if($chart['anomalies'] > 0)<p class="mt-4 text-sm font-semibold text-warning dark:text-warning">The largest detected shift scored {{ number_format($chart['max_anomaly_score'], 2) }}× above the rolling deviation threshold. Use the highlighted points as investigation leads, not as automatic incidents.</p>@elseif($chart['anomaly_baseline_points'] < \App\Modules\Monitor\Services\MetricAnomalyDetector::MINIMUM_BASELINE_POINTS)<p class="mt-4 text-xs text-warning dark:text-warning">Not enough valid history is available in this range yet. Expand the range or send more samples to establish a baseline.</p>@else<p class="mt-4 text-xs text-warning dark:text-warning">No point exceeded the robust deviation threshold in this range.</p>@endif</section>
    @else
        <section class="ui-alert border-primary/30 bg-primary-soft block p-5"><h2 class="font-bold text-primary dark:text-primary">Metric anomaly detection</h2><p class="mt-2 max-w-3xl text-xs leading-5 text-primary dark:text-primary">Find unusual metric shifts with robust rolling baselines, without hand-tuning a threshold for every service. Anomaly detection is available on Pro and above.</p><a href="{{ route('monitor.settings.billing') }}" class="mt-3 inline-flex text-xs font-bold text-primary underline dark:text-primary">Review plans →</a></section>
    @endif
    <section class="ui-panel overflow-hidden"><div class="border-b border-line p-5 dark:border-line"><h2 class="font-bold">Sample evidence</h2><p class="mt-1 text-xs text-muted dark:text-subtle">Unknown samples never become zero and cannot prove recovery.</p></div><div class="overflow-x-auto"><x-monitor::ui.table caption="Metric sample evidence" :framed="false">
        <x-slot:head><tr><th scope="col">Time</th><th scope="col">Value</th><th scope="col">State</th>@if($anomalyDetectionEnabled)<th scope="col">Anomaly</th>@endif<th scope="col">Raw event</th></tr></x-slot:head>
@foreach(collect($chart['points'])->reverse()->take(50) as $point)<tr><td class="whitespace-nowrap">{{ \Carbon\CarbonImmutable::parse($point['time'])->format('Y-m-d H:i:s.u') }} UTC</td><td class="font-mono">{{ $point['value'] === null ? '—' : number_format($point['value'], 6) }}</td><td>{{ str_replace('_', ' ', $point['state']) }}</td>@if($anomalyDetectionEnabled)<td>@if(($point['anomaly']['state'] ?? null) === 'anomaly')<span class="font-semibold text-warning dark:text-warning">{{ ucfirst($point['anomaly']['direction'] ?? 'unusual') }} · {{ number_format($point['anomaly']['score'], 2) }}×</span>@elseif(($point['anomaly']['state'] ?? null) === 'warming')<span class="text-muted dark:text-subtle">Establishing baseline</span>@elseif(($point['anomaly']['state'] ?? null) === 'unknown')<span class="text-muted dark:text-subtle">Unknown</span>@else<span class="text-muted dark:text-subtle">Normal</span>@endif</td>@endif<td><a href="{{ route('monitor.events.show', $point['event_id']) }}" class="font-bold text-primary hover:underline dark:text-primary">Inspect event #{{ $point['event_id'] }}</a></td></tr>@endforeach
    </x-monitor::ui.table></div></section>
    <section class="ui-panel p-5"><h2 class="font-bold">Resource identity</h2><p class="mt-1 text-xs leading-5 text-muted dark:text-subtle">Resource attributes and point labels are kept separately. Displayed values are redacted; the internal identity hash is never exposed.</p><pre class="library-code mt-4"><code>{{ json_encode($series->descriptor, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</code></pre></section>
</div>
@endsection
