@extends('analytics::layouts.app')

@section('content')
<div class="mx-auto max-w-4xl space-y-8">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="ui-eyebrow">Website settings</p><h2 class="mt-2 text-3xl font-extrabold tracking-tight">{{ $site->name }}</h2><p class="mt-2 text-sm leading-6 text-muted">Control collection, domains, privacy exclusions, and the installation snippet.</p></div><a class="ui-btn ui-btn-secondary" href="{{ route('analytics.dashboard') }}">Back to overview</a></div>
    @if (session('status'))<div class="rounded-panel border border-success/30 bg-success-soft p-4 text-sm text-success">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="rounded-panel border border-danger/30 bg-danger-soft p-4 text-sm text-danger"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form class="ui-panel space-y-6 p-6 sm:p-8" method="POST" action="{{ route('analytics.sites.settings.update', $site) }}">
        @csrf @method('PUT')
        <div><label class="ui-label" for="name">Website name</label><input class="ui-input" id="name" name="name" value="{{ old('name', $site->name) }}" required></div>
        <div><label class="ui-label" for="domains">Allowed domains</label><textarea class="ui-input min-h-24" id="domains" name="domains" required>{{ old('domains', implode("\n", $site->domains ?? [])) }}</textarea><p class="mt-2 text-xs text-muted">One exact hostname per line. Origins are checked against this list before events are accepted.</p></div>
        <div><label class="ui-label" for="timezone">Reporting timezone</label><select class="ui-input" id="timezone" name="timezone" required><option value="UTC" @selected(old('timezone', $site->timezone) === 'UTC')>UTC</option><option value="America/New_York" @selected(old('timezone', $site->timezone) === 'America/New_York')>America/New_York</option><option value="America/Los_Angeles" @selected(old('timezone', $site->timezone) === 'America/Los_Angeles')>America/Los_Angeles</option><option value="Europe/London" @selected(old('timezone', $site->timezone) === 'Europe/London')>Europe/London</option><option value="Europe/Berlin" @selected(old('timezone', $site->timezone) === 'Europe/Berlin')>Europe/Berlin</option><option value="Asia/Singapore" @selected(old('timezone', $site->timezone) === 'Asia/Singapore')>Asia/Singapore</option></select><p class="mt-2 text-xs text-muted">The timezone is frozen after the first event to keep local-day reports stable.</p></div>
        <div><label class="ui-label" for="excluded_paths">Excluded paths</label><textarea class="ui-input min-h-28" id="excluded_paths" name="excluded_paths" placeholder="/admin/*&#10;/account">{{ old('excluded_paths', implode("\n", $site->excluded_paths ?? [])) }}</textarea><p class="mt-2 text-xs text-muted">One path or wildcard per line. Excluded paths are dropped before durable storage.</p></div>
        <div class="space-y-3 border-t border-line pt-6"><label class="flex items-center gap-3 text-sm text-muted"><input class="rounded border-line" name="collection_enabled" type="checkbox" value="1" @checked(old('collection_enabled', $site->collection_enabled))> Accept new collection requests</label><label class="flex items-center gap-3 text-sm text-muted"><input class="rounded border-line" name="collection_paused" type="checkbox" value="1" @checked(old('collection_paused', $site->collection_paused_at !== null))> Pause collection temporarily</label></div>
        <div class="flex justify-end"><button class="ui-btn ui-btn-primary" type="submit">Save settings</button></div>
    </form>
    <section class="ui-panel p-6"><p class="ui-eyebrow">Installation</p><h3 class="mt-2 text-lg font-extrabold">Tracker snippet</h3><pre class="mt-4 overflow-x-auto rounded-card bg-zinc-950 p-4 text-xs leading-6 text-zinc-200"><code>&lt;script defer src="{{ url('/tracker/v1.js') }}" data-site="{{ $site->public_id }}"&gt;&lt;/script&gt;</code></pre><p class="mt-3 text-xs leading-5 text-muted">Collection status: {{ $site->isCollectionAvailable() ? 'active' : 'not accepting events' }} · Detail retention: {{ config('analytics.event_retention_days') }} days.</p></section>
    <section class="ui-panel flex flex-col justify-between gap-4 p-6 sm:flex-row sm:items-center"><div><p class="ui-eyebrow">Workspace access</p><h3 class="mt-2 text-lg font-extrabold">Invite your team</h3><p class="mt-2 text-sm text-muted">Manage owner, admin, and viewer access for {{ $site->workspace->name }}.</p></div><a class="ui-btn ui-btn-secondary" href="{{ route('analytics.workspaces.team', $site->workspace) }}">Open team settings</a></section>
    <section class="ui-panel border-danger/20 p-6"><p class="ui-eyebrow text-danger">Danger zone</p><h3 class="mt-2 text-lg font-extrabold">Delete this website</h3><p class="mt-2 text-sm leading-6 text-muted">Collection stops immediately and stored events, visits, goals, and batches are removed.</p><form class="mt-5" method="POST" action="{{ route('analytics.sites.destroy', $site) }}">@csrf @method('DELETE')<button class="ui-btn ui-btn-ghost text-danger" type="submit">Delete website</button></form></section>
</div>
@endsection
