<x-monitor::ui.document :title="$statusPage->name.' · '.config('app.name').' status'" noindex>
<main id="main-content" tabindex="-1" class="mx-auto max-w-4xl px-5 py-10 sm:px-8 sm:py-16">
    <x-monitor::ui.page-header :eyebrow="$statusPage->workspace->name" :title="$statusPage->name" class="mb-8">
        <x-slot:actions><span class="flex h-10 w-10 items-center justify-center rounded-control bg-emphasis text-sm font-bold text-emphasis-ink dark:bg-surface dark:text-emphasis-ink" aria-label="{{ config('app.name') }}">{{ mb_substr(config('app.name'), 0, 1) }}</span></x-slot:actions>
    </x-monitor::ui.page-header>
    @if($statusPage->description)<p class="mb-8 max-w-2xl text-sm leading-6 text-muted dark:text-subtle">{{ $statusPage->description }}</p>@endif
    <section @class(['rounded-card border p-6 shadow-soft', 'border-success bg-success-soft dark:border-success dark:bg-success-soft' => $overall === 'operational', 'border-warning bg-warning-soft dark:border-warning dark:bg-warning-soft' => $overall === 'degraded', 'border-danger bg-danger-soft dark:border-danger dark:bg-danger-soft' => $overall === 'major_outage'])><div class="flex items-center gap-4"><span @class(['flex h-11 w-11 items-center justify-center rounded-full', 'bg-success-soft text-success' => $overall === 'operational', 'bg-warning-soft text-warning' => $overall === 'degraded', 'bg-danger-soft text-danger' => $overall === 'major_outage'])><span class="h-3 w-3 rounded-full bg-current"></span></span><div><h2 class="text-lg font-bold">{{ $overallLabel }}</h2><p class="mt-1 text-xs text-muted dark:text-muted">Current status across the services listed below.</p></div></div></section>
    <section class="ui-panel mt-6 overflow-hidden"><div class="border-b border-line px-6 py-4 dark:border-line"><h2 class="font-bold">Systems</h2></div><div class="divide-y divide-line dark:divide-line">@forelse($components as $component)<div class="px-6 py-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="text-sm font-semibold">{{ $component['name'] }}</h3><p class="mt-1 text-xs text-muted dark:text-subtle">{{ $component['type'] ?? 'Monitored service' }}@if($component['checkedAt']) · Checked {{ $component['checkedAt']->diffForHumans() }}@endif</p></div><span @class(['inline-flex items-center gap-2 rounded-full px-2.5 py-1 text-[11px] font-semibold', 'bg-success-soft text-success' => $component['state'] === 'operational', 'bg-warning-soft text-warning' => $component['state'] === 'degraded', 'bg-danger-soft text-danger' => $component['state'] === 'major_outage'])><span class="h-1.5 w-1.5 rounded-full bg-current"></span>{{ $component['stateLabel'] }}</span></div>@if($component['history'])<div class="ui-card shadow-none mt-5 bg-surface-muted/70 p-4 dark:bg-surface/40"><div class="flex flex-wrap items-center justify-between gap-2"><div><p class="text-xs font-bold text-ink dark:text-ink">30-day observed uptime</p><p class="mt-1 text-[11px] text-muted dark:text-subtle">Completed checks from the current monitor configuration.</p></div>@if($component['history']['uptime'] !== null)<span class="text-lg font-bold text-ink dark:text-ink">{{ number_format($component['history']['uptime'], 2) }}%</span>@else<span class="text-xs font-semibold text-muted dark:text-subtle">Not enough data</span>@endif</div><div class="mt-4 flex gap-1" role="img" aria-label="30-day observed uptime history for {{ $component['name'] }}">@foreach($component['history']['days'] as $day)<span title="{{ $day['label'] }} · {{ $day['summary'] }}" aria-label="{{ $day['label'] }} · {{ $day['summary'] }}" @class(['h-7 min-w-0 flex-1 rounded-sm', 'bg-success dark:bg-success' => $day['state'] === 'operational', 'bg-danger dark:bg-danger' => $day['state'] === 'outage', 'bg-warning dark:bg-warning' => $day['state'] === 'degraded' || $day['state'] === 'unknown', 'bg-line dark:bg-line' => $day['state'] === 'no_data'])></span>@endforeach</div><div class="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-muted dark:text-subtle"><span>{{ $component['history']['measured'] }} observed checks</span>@if($component['history']['failed'] > 0)<span>{{ $component['history']['failed'] }} failed</span>@endif @if($component['history']['unknown'] > 0)<span>{{ $component['history']['unknown'] }} unknown</span>@endif</div></div>@else<p class="mt-4 text-xs text-muted dark:text-subtle">No recent check data is available for this system.</p>@endif</div>@empty<p class="px-6 py-8 text-sm text-muted dark:text-subtle">No systems have been added to this page yet.</p>@endforelse</div></section>
    @if($incidents->isNotEmpty())<section class="ui-panel mt-6 p-6"><h2 class="font-bold">Active incidents</h2><div class="mt-4 space-y-3">@foreach($incidents as $incident)<div class="ui-alert ui-alert-danger block p-4"><div class="flex flex-wrap justify-between gap-2"><p class="text-sm font-semibold">{{ $incident->title }}</p><span class="text-xs font-semibold text-danger dark:text-danger">{{ ucfirst($incident->status) }}</span></div><p class="mt-1 text-xs text-muted dark:text-subtle">Started {{ $incident->opened_at->diffForHumans() }}</p></div>@endforeach</div></section>@endif
    @if($recentIncidents->isNotEmpty())<section class="ui-panel mt-6 overflow-hidden"><div class="border-b border-line px-6 py-4 dark:border-line"><h2 class="font-bold">Recent incidents</h2><p class="mt-1 text-xs text-muted dark:text-subtle">Resolved monitor incidents from the last 30 days.</p></div><div class="divide-y divide-line dark:divide-line">@foreach($recentIncidents as $incident)<div class="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><div><p class="text-sm font-semibold">{{ $incident->title }}</p><p class="mt-1 text-xs text-muted dark:text-subtle">Started {{ $incident->opened_at->diffForHumans() }}@if($incident->resolved_at) · Resolved {{ $incident->resolved_at->diffForHumans() }}@endif</p></div><span class="inline-flex items-center gap-2 rounded-full bg-surface-muted px-2.5 py-1 text-[11px] font-semibold text-muted dark:bg-surface-muted dark:text-muted"><span class="h-1.5 w-1.5 rounded-full bg-current"></span>Resolved</span></div>@endforeach</div></section>@endif
    <footer class="mt-10 flex flex-wrap justify-between gap-3 text-xs text-subtle"><span>Powered by {{ config('app.name') }}</span><span>Updated {{ now()->format('Y-m-d H:i') }} UTC</span></footer>
</main>
</x-monitor::ui.document>
