@extends('monitor::layouts.app')

@section('title', $objective->name)
@section('breadcrumb', 'SLOs')

@section('content')
    @php($statusTone = match($report['status']) { 'healthy' => 'green', 'warning' => 'amber', 'exhausted' => 'red', default => 'slate' })
    @php($statusLabel = match($report['status']) { 'healthy' => 'Within budget', 'warning' => 'Budget low', 'exhausted' => 'Budget exhausted', default => 'No eligible data' })
    <div class="flex flex-col gap-6">
        <a href="{{ route('monitor.objectives.index') }}" class="text-xs font-bold text-primary hover:underline dark:text-primary">← SLOs</a>
        <x-monitor::ui.page-header :eyebrow="$objective->indicatorLabel().' objective'" eyebrow-icon="shield" :title="$objective->name" :description="$objective->environment->application->name.' / '.$objective->environment->name.' · '.$objective->scopeLabel()">
            <x-slot:actions>
                <x-monitor::ui.badge :tone="$statusTone">{{ $statusLabel }}</x-monitor::ui.badge>
                @if($sloReportsEnabled)<x-monitor::ui.button :href="route('monitor.objectives.export', $objective)" variant="secondary"><x-monitor::icon name="arrow-down" class="h-3.5 w-3.5" />Export CSV</x-monitor::ui.button>@else<x-monitor::ui.button :href="route('monitor.settings.billing')" variant="secondary">Team reports</x-monitor::ui.button>@endif
                @if($canManage)<x-monitor::ui.button :href="route('monitor.objectives.edit', $objective)" variant="secondary">Edit</x-monitor::ui.button>@endif
            </x-slot:actions>
        </x-monitor::ui.page-header>

        <section aria-label="SLO summary" class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <x-signal.ui.card as="div" class="p-5"><h2 class="text-xs font-semibold text-muted dark:text-subtle">Observed compliance</h2><p class="mt-2 text-2xl font-bold">{{ $report['compliance'] === null ? 'Not reported' : number_format($report['compliance'], 3).'%' }}</p><p class="mt-2 text-xs text-muted dark:text-subtle">Target {{ number_format($objective->target, 3) }}%</p></x-signal.ui.card>
            <x-signal.ui.card as="div" class="p-5"><h2 class="text-xs font-semibold text-muted dark:text-subtle">Error budget remaining</h2><p class="mt-2 text-2xl font-bold {{ $report['budget_remaining'] !== null && $report['budget_remaining'] < 0 ? 'text-danger dark:text-danger' : '' }}">{{ $report['budget_remaining'] === null ? 'Not reported' : number_format($report['budget_remaining'], 2).'%' }}</p><p class="mt-2 text-xs text-muted dark:text-subtle">Burn rate {{ $report['burn_rate'] === null ? 'not reported' : number_format($report['burn_rate'], 3).'×' }}</p></x-signal.ui.card>
            <x-signal.ui.card as="div" class="p-5"><h2 class="text-xs font-semibold text-muted dark:text-subtle">Measured requests</h2><p class="mt-2 text-2xl font-bold">{{ number_format($report['observed']) }}</p><p class="mt-2 text-xs text-muted dark:text-subtle">{{ number_format($report['good']) }} good · {{ number_format($report['bad']) }} bad</p></x-signal.ui.card>
            <x-signal.ui.card as="div" class="p-5"><h2 class="text-xs font-semibold text-muted dark:text-subtle">Unknown records</h2><p class="mt-2 text-2xl font-bold">{{ number_format($report['unknown']) }}</p><p class="mt-2 text-xs text-muted dark:text-subtle">of {{ number_format($report['total']) }} matching requests</p></x-signal.ui.card>
        </section>

        @if($burnRate === null)
            <x-signal.ui.alert as="section" tone="info" class="border-primary/30 bg-primary-soft block p-5"><h2 class="font-bold text-primary dark:text-primary">Burn-rate analysis</h2><p class="mt-2 max-w-3xl text-xs leading-5 text-primary dark:text-primary">Compare fast and slow error-budget consumption before the rolling budget is exhausted. SLO burn-rate analysis is available on paid plans.</p><a href="{{ route('monitor.settings.billing') }}" class="mt-3 inline-flex text-xs font-bold text-primary underline dark:text-primary">Review plans →</a></x-signal.ui.alert>
        @else
            @php($burnTone = match($burnRate['status']) { 'critical' => 'red', 'warning' => 'amber', 'healthy' => 'green', default => 'slate' })
            <x-signal.ui.panel as="section" class="space-y-5 p-5 sm:p-6"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p class="text-xs font-semibold text-primary dark:text-primary">PROACTIVE RELIABILITY SIGNAL</p><h2 class="mt-1 text-base font-bold text-ink dark:text-ink">Burn-rate analysis</h2><p class="mt-1 max-w-3xl text-xs leading-5 text-muted dark:text-subtle">Fast-burn and slow-burn windows show whether current bad-request consumption could exhaust this objective's budget.</p></div><x-monitor::ui.badge :tone="$burnTone">{{ $burnRate['label'] }}</x-monitor::ui.badge></div><div class="grid gap-4 sm:grid-cols-2"><x-signal.ui.card as="div" class="shadow-none p-4"><p class="text-xs text-muted dark:text-subtle">Last hour</p><p class="mt-2 text-2xl font-bold">{{ $burnRate['short']['burn_rate'] === null ? '—' : number_format($burnRate['short']['burn_rate'], 2).'×' }}</p><p class="mt-1 text-xs text-muted dark:text-subtle">{{ number_format($burnRate['short']['bad']) }} bad / {{ number_format($burnRate['short']['observed']) }} measured</p></x-signal.ui.card><x-signal.ui.card as="div" class="shadow-none p-4"><p class="text-xs text-muted dark:text-subtle">Last 6 hours</p><p class="mt-2 text-2xl font-bold">{{ $burnRate['long']['burn_rate'] === null ? '—' : number_format($burnRate['long']['burn_rate'], 2).'×' }}</p><p class="mt-1 text-xs text-muted dark:text-subtle">{{ number_format($burnRate['long']['bad']) }} bad / {{ number_format($burnRate['long']['observed']) }} measured</p></x-signal.ui.card></div><p class="text-xs leading-5 text-muted dark:text-subtle">{{ $burnRate['message'] }} Thresholds use a 6× warning signal and a sustained 14.4× fast-burn signal.</p></x-signal.ui.panel>
        @endif

        <section class="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(300px,0.7fr)]">
            <x-signal.ui.card as="div" class="p-5 sm:p-6"><h2 class="text-base font-bold text-ink dark:text-ink">How this objective is measured</h2><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt class="text-xs text-muted dark:text-subtle">Indicator</dt><dd class="mt-1 text-sm font-semibold">{{ $objective->indicatorLabel() }} · target {{ number_format($objective->target, 3) }}%</dd></div><div><dt class="text-xs text-muted dark:text-subtle">Window</dt><dd class="mt-1 text-sm font-semibold">{{ $objective->windowLabel() }}</dd></div><div><dt class="text-xs text-muted dark:text-subtle">Scope</dt><dd class="mt-1 break-words text-sm font-semibold">{{ $objective->scopeLabel() }}</dd></div><div><dt class="text-xs text-muted dark:text-subtle">Healthy condition</dt><dd class="mt-1 text-sm font-semibold">{{ $objective->isLatency() ? 'Duration ≤ '.\App\Modules\Monitor\Data\Telemetry\TraceRecord::formatDuration($objective->latency_threshold_ms) : 'HTTP '.$objective->status_min.'–'.$objective->status_max }}</dd></div></dl><div class="mt-6 rounded-control bg-surface-muted p-4 text-xs leading-5 text-muted dark:bg-surface-muted dark:text-muted"><p>Window: {{ $report['from']->format('Y-m-d H:i:s.u') }}–{{ $report['until']->format('Y-m-d H:i:s.u') }} UTC.</p><p class="mt-2">First eligible record: {{ $report['first_measured_at']?->format('Y-m-d H:i:s.u') ?? 'None' }}{{ $report['first_measured_at'] ? ' UTC' : '' }} · last eligible record: {{ $report['last_measured_at']?->format('Y-m-d H:i:s.u') ?? 'None' }}{{ $report['last_measured_at'] ? ' UTC' : '' }}.</p><p class="mt-2">Only <span class="font-semibold">request</span> telemetry in the selected environment is included. Unknown records are excluded from both good and bad counts and should be treated as a coverage signal.</p></div></x-signal.ui.card>
            <x-signal.ui.card as="div" class="p-5 sm:p-6"><h2 class="text-base font-bold text-ink dark:text-ink">Next steps</h2><div class="mt-5 flex flex-col gap-3"><x-signal.ui.card as="a" href="{{ route('monitor.events.index', ['environment' => $objective->environment_id, 'type' => 'request', ...($objective->service ? ['service' => $objective->service] : [])]) }}" class="shadow-none p-4 text-xs font-semibold hover:border-primary hover:bg-primary-soft dark:hover:border-primary dark:hover:bg-primary-soft">Inspect matching request events <span class="float-right text-primary dark:text-primary">→</span></x-signal.ui.card><x-signal.ui.card as="a" href="{{ route('monitor.alerts.create', ['environment' => $objective->environment_id]) }}" class="shadow-none p-4 text-xs font-semibold hover:border-primary hover:bg-primary-soft dark:hover:border-primary dark:hover:bg-primary-soft">Create a supporting alert rule <span class="float-right text-primary dark:text-primary">→</span></x-signal.ui.card></div>@if($canManage)<form method="POST" action="{{ route('monitor.objectives.destroy', $objective) }}" class="mt-8 border-t border-line pt-5 dark:border-line">@csrf @method('DELETE')<x-monitor::ui.button variant="secondary" class="text-danger dark:text-danger">Archive objective</x-monitor::ui.button></form>@endif</x-signal.ui.card>
        </section>
        <p class="text-xs leading-5 text-muted dark:text-subtle">This report is calculated when the page loads. It is a reliability indicator based on received telemetry, not proof of uptime; external synthetic checks and complete instrumentation remain important.</p>
    </div>
@endsection
