<x-layouts.app>
    <x-layouts.partials.heading icon="terminal" :title="__('Automation')" :description="__('API access, deploy schedules, scaling and versioned workflow configuration.')" />
    @if(session('success'))<div class="mt-6 rounded-xl border border-green-300 bg-green-50 p-4 text-green-800">{{ session('success') }}</div>@endif
    @if(session('plainTextToken'))<div class="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><p class="font-bold">{{ __('Copy this token now') }}</p><code class="mt-2 block break-all rounded-lg bg-white p-3 text-sm">{{ session('plainTextToken') }}</code></div>@endif
    @if($errors->any())<div class="mt-6 rounded-xl border border-red-300 bg-red-50 p-4 text-red-900"><ul class="space-y-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="mt-8 grid gap-5 lg:grid-cols-2">
        <section class="rounded-2xl border border-primary bg-primary p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Control plane API') }}</p><h2 class="mt-2 text-xl font-black text-primary">{{ __('Personal access tokens') }}</h2><p class="mt-2 text-sm text-secondary">{{ __('Create least-privilege Bearer tokens with an explicit expiry.') }} <a href="{{ route('api-docs') }}" class="font-bold text-ternary">{{ __('API reference') }}</a></p></div>@unless($features['api'])<a class="text-sm font-bold text-ternary" href="{{ route('billing.index') }}">{{ __('Business feature') }}</a>@endunless</div>
            @if($features['api'] && $canManage)<form method="POST" action="{{ route('automation.tokens.store') }}" class="mt-5 space-y-4">@csrf<div class="grid gap-3 sm:grid-cols-[1fr_11rem]"><input name="name" required maxlength="100" class="input secondary rounded" placeholder="CI deployment"><select name="expires_in_days" class="input secondary rounded"><option value="30">{{ __('30 days') }}</option><option value="90">{{ __('90 days') }}</option><option value="180">{{ __('180 days') }}</option><option value="365" selected>{{ __('1 year') }}</option></select></div><div class="flex flex-wrap gap-4 text-sm text-secondary">@foreach(['read', 'deploy', 'manage'] as $ability)<label class="flex items-center gap-2"><input type="checkbox" name="abilities[]" value="{{ $ability }}" @checked($ability === 'read')>{{ ucfirst($ability) }}</label>@endforeach</div><button type="submit" class="button primary">{{ __('Create token') }}</button></form>@endif
            <div class="mt-5 space-y-2">@forelse($tokens as $token)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-secondary p-3"><div><p class="font-bold text-primary">{{ $token->name }}</p><p class="text-xs text-secondary">{{ implode(', ', $token->abilities) }} · {{ $token->last_used_at ? __('used :time', ['time' => $token->last_used_at->diffForHumans()]) : __('never used') }} · {{ $token->expires_at ? __('expires :time', ['time' => $token->expires_at->diffForHumans()]) : __('no expiry') }}</p></div><div class="flex gap-3">@if($canManage)<form method="POST" action="{{ route('automation.tokens.rotate', $token->id) }}">@csrf<button type="submit" class="text-sm font-bold text-ternary">{{ __('Rotate') }}</button></form>@endif<form method="POST" action="{{ route('automation.tokens.destroy', $token->id) }}">@csrf @method('DELETE')<button type="submit" class="text-sm font-bold text-red-600">{{ __('Revoke') }}</button></form></div></div>@empty<p class="text-sm text-secondary">{{ __('No API tokens.') }}</p>@endforelse</div>
        </section>
        <section class="rounded-2xl border border-primary bg-primary p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Quick start') }}</p><h2 class="mt-2 text-xl font-black text-primary">{{ __('CLI-friendly API') }}</h2><p class="mt-2 text-sm text-secondary">{{ __('Everything returns JSON and works with curl, CI, or your preferred scripting language.') }}</p><pre class="mt-5 overflow-x-auto rounded-xl bg-gray-950 p-4 text-xs leading-6 text-gray-100"><code>export BUILDPUSHER_TOKEN="bp_…"
curl -H "Authorization: Bearer $BUILDPUSHER_TOKEN" \
  {{ url('/api/v1/projects') }}

curl -X POST -H "Authorization: Bearer $BUILDPUSHER_TOKEN" \
  {{ url('/api/v1/environments/1/deploy') }}</code></pre></section>
    </div>

    <section class="mt-6"><div class="mb-4"><h2 class="text-2xl font-black text-primary">{{ __('Application workflows') }}</h2><p class="mt-1 text-secondary">{{ __('Open an application to configure it. This keeps a large workspace compact.') }}</p></div>
        <div class="space-y-4">@forelse($projects as $project)<details class="group overflow-hidden rounded-2xl border border-primary bg-primary"><summary class="flex cursor-pointer list-none items-center justify-between p-5"><div><p class="font-black text-primary">{{ $project->name }}</p><p class="mt-1 text-sm text-secondary">{{ $project->environments->count() }} {{ __('environments') }}</p></div><span class="text-2xl text-ternary transition group-open:rotate-45">+</span></summary>
            <div class="border-t border-primary p-5"><form method="POST" action="{{ route('automation.workflow', $project) }}">@csrf @method('PUT')<label class="block text-sm font-bold text-primary">buildpusher.yaml</label><textarea name="workflow" rows="12" class="input secondary mt-2 w-full rounded font-mono text-xs" spellcheck="false">{{ old('workflow', $project->workflow_yaml ?: "version: 1\nenvironments:\n  production:\n    deployment:\n      cron: '0 3 * * 1-5'\n      timezone: UTC\n    scale:\n      minimum: 1\n      maximum: 3\n      desired: 2\n      hibernate_after_minutes: 60") }}</textarea><div class="mt-3 flex items-center justify-between gap-3"><p class="text-xs text-secondary">{{ __('Applying YAML validates every setting before saving any of them.') }}</p><button type="submit" class="button primary" @disabled(!$canManage)>{{ __('Validate & apply') }}</button></div></form>
                <div class="mt-6 grid gap-4 xl:grid-cols-2">@foreach($project->environments as $environment)<article class="rounded-xl border border-primary bg-secondary p-4"><div class="flex items-center justify-between"><div><h3 class="font-black text-primary">{{ $environment->name }}</h3><p class="text-xs text-secondary">{{ $environment->branch }} · {{ $environment->hibernated_at ? __('Hibernated') : __('Running') }}</p></div>@if($features['hibernation'])<form method="POST" action="{{ route('automation.runtime', $environment) }}">@csrf @method('PATCH')<input type="hidden" name="state" value="{{ $environment->hibernated_at ? 'running' : 'hibernated' }}"><button type="submit" class="text-xs font-bold text-ternary">{{ $environment->hibernated_at ? __('Resume') : __('Hibernate') }}</button></form>@endif</div>
                    @if($features['scaling'])<form method="POST" action="{{ route('automation.scale', $environment) }}" class="mt-4 grid grid-cols-3 gap-2">@csrf @method('PATCH')<input class="input secondary rounded" type="number" min="1" max="20" name="minimum_replicas" value="{{ $environment->minimum_replicas }}" aria-label="Minimum replicas"><input class="input secondary rounded" type="number" min="1" max="20" name="maximum_replicas" value="{{ min(20, $environment->maximum_replicas) }}" aria-label="Maximum replicas"><input class="input secondary rounded" type="number" min="1" max="20" name="desired_replicas" value="{{ $environment->desired_replicas }}" aria-label="Desired replicas"><input type="hidden" name="hibernate_after_minutes" value="{{ $environment->hibernate_after_minutes }}"><button type="submit" class="button primary col-span-3 justify-center">{{ __('Apply capacity') }}</button></form>@else<p class="mt-4 text-sm text-secondary"><a class="font-bold text-ternary" href="{{ route('billing.index') }}">{{ __('Upgrade to Business') }}</a> {{ __('for scheduled scaling.') }}</p>@endif
                    <div class="mt-4 border-t border-primary pt-4"><p class="text-xs font-bold uppercase tracking-wide text-secondary">{{ __('Schedules') }}</p>@foreach($environment->deploymentSchedules as $schedule)<div class="mt-2 flex justify-between text-xs text-secondary"><span>{{ $schedule->name }} · <code>{{ $schedule->cron_expression }}</code></span><form method="POST" action="{{ route('automation.deployment-schedules.destroy', $schedule) }}">@csrf @method('DELETE')<button type="submit" class="font-bold text-red-600">×</button></form></div>@endforeach
                        @if($features['scheduled_deployments'])<form method="POST" action="{{ route('automation.deployment-schedules.store', $environment) }}" class="mt-3 grid gap-2 sm:grid-cols-3">@csrf<input required name="name" class="input secondary rounded text-xs" placeholder="Nightly"><input required name="cron_expression" class="input secondary rounded font-mono text-xs" value="0 3 * * *"><input required name="timezone" class="input secondary rounded text-xs" value="UTC"><button type="submit" class="button secondary sm:col-span-3 justify-center">{{ __('Add deployment schedule') }}</button></form>@endif
                    </div>
                    <div class="mt-4 border-t border-primary pt-4"><div class="flex items-center justify-between"><p class="text-xs font-bold uppercase tracking-wide text-secondary">{{ __('Application tasks') }}</p><span class="text-[10px] text-secondary">{{ __('Encrypted commands') }}</span></div>
                        <div class="mt-3 space-y-2">@foreach($environment->scheduledTasks as $task)<div class="rounded-lg border border-primary bg-primary p-3"><div class="flex items-center gap-2"><div class="min-w-0 flex-1"><p class="font-bold text-primary">{{ $task->name }}</p><p class="text-xs text-secondary"><code>{{ $task->cron_expression }}</code> · {{ $task->timezone }} · {{ $task->last_status ? ucfirst($task->last_status) : __('Never run') }}</p></div><form method="POST" action="{{ route('automation.tasks.run',$task) }}">@csrf<button type="submit" class="text-xs font-bold text-ternary">{{ __('Run') }}</button></form><form method="POST" action="{{ route('automation.tasks.destroy',$task) }}">@csrf @method('DELETE')<button type="submit" class="text-xs font-bold text-red-600">{{ __('Delete') }}</button></form></div>@if($task->runs->isNotEmpty())<div class="mt-2 flex flex-wrap gap-2">@foreach($task->runs->take(5) as $run)<a href="{{ route('automation.task-runs.output',$run) }}" class="rounded bg-secondary px-2 py-1 text-[10px] text-secondary">{{ $run->status }} · {{ $run->created_at->diffForHumans() }}</a>@endforeach</div>@endif</div>@endforeach</div>
                        <form method="POST" action="{{ route('automation.tasks.store',$environment) }}" class="mt-3 grid gap-2 sm:grid-cols-2">@csrf<input name="name" maxlength="100" required class="input secondary rounded text-xs" placeholder="Warm cache"><input name="cron_expression" maxlength="100" required class="input secondary rounded font-mono text-xs" value="0 * * * *"><input name="timezone" required class="input secondary rounded text-xs" value="UTC"><input type="number" name="timeout_seconds" min="10" max="3600" value="300" required class="input secondary rounded text-xs" aria-label="Timeout seconds"><textarea name="command" maxlength="4000" required class="input secondary rounded font-mono text-xs sm:col-span-2" rows="2" placeholder="php artisan cache:warm"></textarea><input type="hidden" name="without_overlapping" value="0"><label class="flex items-center gap-2 text-xs text-secondary"><input type="checkbox" name="without_overlapping" value="1" checked>{{ __('Prevent overlap') }}</label><input type="hidden" name="alert_on_failure" value="0"><label class="flex items-center gap-2 text-xs text-secondary"><input type="checkbox" name="alert_on_failure" value="1" checked>{{ __('Alert on failure') }}</label><button type="submit" class="button secondary sm:col-span-2 justify-center">{{ __('Add scheduled task') }}</button></form>
                    </div></article>@endforeach</div>
            </div></details>@empty<div class="rounded-2xl border border-primary bg-primary p-8 text-center text-secondary">{{ __('Create an application to configure automation.') }}</div>@endforelse</div>
    </section>
</x-layouts.app>
