<?php

return [
    'monitors' => [
        'location' => env('MONITOR_LOCATION', 'This server'),
    ],
    'alerts' => [
        'mailer' => env('MONITOR_ALERT_MAILER', env('ALERT_MAILER')),
    ],
    'usage_alerts' => [
        'enabled' => (bool) env('MONITOR_USAGE_ALERTS_ENABLED', env('BEACON_USAGE_ALERTS_ENABLED', true)),
        'thresholds' => [80, 100],
        'sending_lock_minutes' => 15,
    ],
    'billing' => [
        'stripe' => [
            'secret' => env('MONITOR_STRIPE_SECRET', env('STRIPE_SECRET')),
            'webhook_secret' => env('MONITOR_STRIPE_WEBHOOK_SECRET'),
            'api_url' => env('MONITOR_STRIPE_API_URL', env('STRIPE_API_URL', 'https://api.stripe.com')),
            'portal_enabled' => env('MONITOR_STRIPE_PORTAL_ENABLED', env('STRIPE_PORTAL_ENABLED', true)),
            'webhook_tolerance_seconds' => (int) env('MONITOR_STRIPE_WEBHOOK_TOLERANCE_SECONDS', env('STRIPE_WEBHOOK_TOLERANCE_SECONDS', 300)),
        ],
    ],
    'telemetry' => [
        'queue_connection' => env('MONITOR_TELEMETRY_QUEUE_CONNECTION', 'telemetry'),
        'collection_stale_after_minutes' => (int) env('MONITOR_COLLECTION_STALE_AFTER_MINUTES', env('BEACON_COLLECTION_STALE_AFTER_MINUTES', 60)),
        'max_request_bytes' => 1_048_576,
        'max_decoded_bytes' => 4_194_304,
        'max_json_depth' => 32,
        'max_json_nodes' => 100_000,
        'max_events_per_batch' => 500,
        'max_attributes_per_record' => 128,
        'max_normalized_bytes' => 8_388_608,
        'sensitive_keys' => [
            '*password*', '*passwd*', 'pwd', '*secret*', '*token', '*apikey*',
            '*authorization*', '*cookie*', '*privatekey*', '*sessionid',
            '*connectionstring*', '*cardnumber', 'cvv', 'ssn', '*email', '*emailaddress',
        ],
        'redacted_paths' => [],
    ],
    'plans' => [
        'free' => [
            'name' => 'Free',
            'price' => 0,
            'description' => 'A clear starting point for small projects.',
            'event_limit' => 500_000,
            'retention_days' => 7,
            'apps' => 1,
            'seats' => 1,
            'dashboards' => 1,
            'escalation_steps' => 0,
            'deployment_context_minutes' => 0,
            'telemetry_guardrails' => false,
            'slo_burn_rate' => false,
            'slo_burn_rate_alerts' => false,
            'slo_reports' => false,
            'anomaly_detection' => false,
            'log_pattern_alerts' => false,
            'audit_log' => false,
            'issue_digest' => true,
            'accent' => 'slate',
            'features' => ['500k events / month', '7-day retention', '1 application', '1 saved dashboard', 'Email issue digest'],
        ],
        'pro' => [
            'name' => 'Pro',
            'price' => 29,
            'stripe_price_id' => env('MONITOR_STRIPE_PRO_PRICE_ID'),
            'description' => 'For teams shipping production software every day.',
            'event_limit' => 10_000_000,
            'retention_days' => 30,
            'apps' => 'Unlimited',
            'seats' => 5,
            'dashboards' => 5,
            'escalation_steps' => 3,
            'deployment_context_minutes' => 60,
            'telemetry_guardrails' => true,
            'slo_burn_rate' => true,
            'slo_burn_rate_alerts' => true,
            'slo_reports' => false,
            'anomaly_detection' => true,
            'log_pattern_alerts' => true,
            'audit_log' => true,
            'issue_digest' => true,
            'accent' => 'violet',
            'features' => ['10M events / month', '30-day retention', 'Unlimited applications', '5 saved dashboards', '3-step alert escalation', '60-minute deployment context', 'Telemetry volume and freshness alerts', 'SLO burn-rate analysis and alerts', 'Metric anomaly detection and alerts', 'Log pattern alerts', 'Team audit log', 'Email issue digest', 'Slack, Teams, PagerDuty and signed webhooks'],
        ],
        'team' => [
            'name' => 'Team',
            'price' => 99,
            'stripe_price_id' => env('MONITOR_STRIPE_TEAM_PRICE_ID'),
            'description' => 'Shared observability for growing engineering teams.',
            'event_limit' => 50_000_000,
            'retention_days' => 90,
            'apps' => 'Unlimited',
            'seats' => 15,
            'dashboards' => 15,
            'escalation_steps' => 5,
            'deployment_context_minutes' => 120,
            'telemetry_guardrails' => true,
            'slo_burn_rate' => true,
            'slo_burn_rate_alerts' => true,
            'slo_reports' => true,
            'anomaly_detection' => true,
            'log_pattern_alerts' => true,
            'audit_log' => true,
            'issue_digest' => true,
            'accent' => 'sky',
            'features' => ['50M events / month', '90-day retention', '15 seats included', '15 saved dashboards', '5-step alert escalation', '2-hour deployment context', 'Telemetry volume and freshness alerts', 'SLO burn-rate analysis and alerts', 'Metric anomaly detection and alerts', 'Log pattern alerts', 'Team audit log', 'Email issue digest', 'Slack, Teams, PagerDuty and signed webhooks', 'SLO reports and exports'],
        ],
        'scale' => [
            'name' => 'Scale',
            'price' => 299,
            'stripe_price_id' => env('MONITOR_STRIPE_SCALE_PRICE_ID'),
            'description' => 'High-volume telemetry with a direct line to our team.',
            'event_limit' => 180_000_000,
            'retention_days' => 180,
            'apps' => 'Unlimited',
            'seats' => 'Unlimited',
            'dashboards' => 'Unlimited',
            'escalation_steps' => 10,
            'deployment_context_minutes' => 240,
            'telemetry_guardrails' => true,
            'slo_burn_rate' => true,
            'slo_burn_rate_alerts' => true,
            'slo_reports' => true,
            'anomaly_detection' => true,
            'log_pattern_alerts' => true,
            'audit_log' => true,
            'issue_digest' => true,
            'accent' => 'amber',
            'features' => ['180M events / month', '180-day retention', 'Unlimited seats', 'Unlimited saved dashboards', '10-step alert escalation', '4-hour deployment context', 'Telemetry volume and freshness alerts', 'SLO burn-rate analysis and alerts', 'Metric anomaly detection and alerts', 'Log pattern alerts', 'Team audit log', 'Email issue digest', 'Slack, Teams, PagerDuty and signed webhooks', 'Priority support and custom limits'],
        ],
    ],
];
