<x-layouts.app>
    <x-layouts.partials.breadcrumbs :route="route('websites.index')" :title="__('Back to websites')" />
    <x-layouts.partials.heading :title="__('Import existing application')" :description="__('Adopt an application already stored under /var/www on an active server. BuildPusher verifies the directory and does not change files or proxy configuration during import.')" />
    <form method="POST" action="{{ route('websites.import.store') }}" class="mt-8 max-w-3xl space-y-5 rounded-2xl border border-primary bg-primary p-6">@csrf
        <label class="block"><span class="mb-1 block text-sm font-bold text-primary">{{ __('Active server') }}</span><select name="server_id" required class="input secondary w-full rounded"><option value="">{{ __('Choose a server') }}</option>@foreach($servers as $server)<option value="{{ $server->id }}" @selected(old('server_id') == $server->id)>{{ $server->label }} · {{ $server->public_ip }}</option>@endforeach</select><x-forms.errors name="server_id" /></label>
        <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1 block text-sm font-bold text-primary">{{ __('Application name') }}</span><input name="name" required maxlength="100" value="{{ old('name') }}" class="input secondary w-full rounded"></label><label><span class="mb-1 block text-sm font-bold text-primary">{{ __('Domain') }}</span><input name="url" required maxlength="255" value="{{ old('url') }}" placeholder="app.example.com" class="input secondary w-full rounded"></label></div>
        <label class="block"><span class="mb-1 block text-sm font-bold text-primary">{{ __('Directory name under /var/www') }}</span><div class="flex items-center"><span class="rounded-l border border-r-0 border-primary bg-secondary px-3 py-2 text-secondary">/var/www/</span><input name="deployment_slug" required maxlength="32" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="{{ old('deployment_slug') }}" placeholder="my-app" class="input secondary rounded-l-none rounded-r"></div><x-forms.errors name="deployment_slug" /></label>
        <label class="block"><span class="mb-1 block text-sm font-bold text-primary">{{ __('Description') }}</span><textarea name="description" required maxlength="1000" class="input secondary w-full rounded">{{ old('description') }}</textarea></label>
        <p class="rounded-lg bg-secondary p-3 text-sm text-secondary">{{ __('Health monitoring starts disabled so importing cannot generate a false incident. Enable it after confirming the domain and health path.') }}</p>
        <button type="submit" class="button primary" @disabled(!$planUsage['allowed'] || $servers->isEmpty())>{{ __('Verify and import') }}</button>
    </form>
</x-layouts.app>
