<x-layouts.app title="{{ __('Databases') }}">
    <x-layouts.partials.heading icon="database" :title="__('Database operations')" :description="__('Inspect managed databases, issue expiring credentials, and safely clone data into non-production environments.')" />
    @unless($featureAvailable)<div class="mt-6 rounded-xl border border-ternary bg-primary p-4 text-sm text-secondary"><strong class="text-primary">{{ __('Pro feature') }}</strong> · {{ __('Upgrade to inspect databases, issue credentials, and run safe clones.') }} <a href="{{ route('pricing') }}" class="font-bold text-ternary underline">{{ __('Compare plans') }}</a></div>@endunless
    @if(session('databasePassword'))<div class="mt-6 rounded-xl border border-warning bg-warning p-4"><p class="font-bold text-primary">{{ __('Copy this password now') }}</p><code class="mt-2 block break-all rounded bg-primary p-3 text-sm text-primary">{{ session('databasePassword') }}</code></div>@endif
    <div class="mt-8 grid gap-5 xl:grid-cols-2">
        @forelse($resources as $resource)
            @php($latest = $resource->snapshots->first())
            <section class="rounded-2xl border border-primary bg-primary p-5">
                <div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wider text-ternary">{{ strtoupper($resource->type) }}</p><h2 class="mt-1 text-lg font-black text-primary">{{ $resource->name }}</h2><p class="text-sm text-secondary">{{ $resource->environment->project->name }} · {{ $resource->environment->name }}</p></div><form method="POST" action="{{ route('databases.inspect', $resource) }}">@csrf<button type="submit" class="button secondary">{{ __('Inspect') }}</button></form></div>
                <div class="mt-4 grid grid-cols-2 gap-3"><div class="rounded-xl bg-secondary p-3"><p class="text-xs text-secondary">{{ __('Size') }}</p><p class="font-bold text-primary">{{ $latest?->size_bytes ? number_format($latest->size_bytes / 1048576, 1).' MB' : '—' }}</p></div><div class="rounded-xl bg-secondary p-3"><p class="text-xs text-secondary">{{ __('Connections') }}</p><p class="font-bold text-primary">{{ $latest?->active_connections ?? '—' }}</p></div></div>
                @if($latest?->schema_tables)<details class="mt-3"><summary class="cursor-pointer text-sm font-bold text-secondary">{{ count($latest->schema_tables) }} {{ __('tables') }}</summary><p class="mt-2 break-words font-mono text-xs text-secondary">{{ implode(' · ', $latest->schema_tables) }}</p></details>@endif
                @if($canManage)
                    <form method="POST" action="{{ route('databases.users.store', $resource) }}" class="mt-5 grid gap-2 border-t border-primary pt-4 sm:grid-cols-2">@csrf<input name="username" class="input secondary rounded" placeholder="report_reader" required><select name="privilege" class="input secondary rounded"><option value="read">{{ __('Read only') }}</option><option value="write">{{ __('Read/write') }}</option><option value="admin">{{ __('Admin') }}</option></select><select name="expires_in_days" class="input secondary rounded"><option value="">{{ __('Never expires') }}</option><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select><button type="submit" class="button primary">{{ __('Create credential') }}</button></form>
                    <div class="mt-3 space-y-2">@foreach($resource->databaseUsers as $databaseUser)<div class="flex items-center justify-between rounded-lg bg-secondary p-3"><div><p class="text-sm font-bold text-primary">{{ $databaseUser->username }}</p><p class="text-xs text-secondary">{{ ucfirst($databaseUser->privilege) }} · {{ $databaseUser->expires_at ? __('expires').' '.$databaseUser->expires_at->diffForHumans() : __('permanent') }}</p></div><form method="POST" action="{{ route('databases.users.destroy', $databaseUser) }}">@csrf @method('DELETE')<button type="submit" class="text-xs font-bold text-danger">{{ __('Revoke') }}</button></form></div>@endforeach</div>
                    <form method="POST" action="{{ route('databases.clone', $resource) }}" class="mt-5 grid gap-2 border-t border-primary pt-4">@csrf<select name="target_resource_id" class="input secondary rounded" required><option value="">{{ __('Clone into…') }}</option>@foreach($resources->where('type', $resource->type)->where('id', '!=', $resource->id)->filter(fn($target) => $target->environment->type !== 'production') as $target)<option value="{{ $target->id }}">{{ $target->environment->project->name }} / {{ $target->environment->name }} / {{ $target->name }}</option>@endforeach</select><input name="confirmation" class="input secondary rounded" placeholder="{{ __('Type the target resource name to confirm') }}" required><button type="submit" class="button secondary">{{ __('Queue destructive clone') }}</button></form>
                @endif
            </section>
        @empty<p class="text-secondary">{{ __('Attach a MySQL or PostgreSQL resource to use database operations.') }}</p>@endforelse
    </div>
    @if($clones->isNotEmpty())<section class="mt-6 rounded-2xl border border-primary bg-primary p-5"><h2 class="font-black text-primary">{{ __('Clone history') }}</h2><div class="mt-3 space-y-2">@foreach($clones as $clone)<div class="flex justify-between gap-3 rounded-lg bg-secondary p-3 text-sm"><span class="text-primary">{{ $clone->source->name }} → {{ $clone->target->name }}</span><span class="font-bold text-secondary">{{ ucfirst($clone->status) }}</span></div>@endforeach</div></section>@endif
</x-layouts.app>
