<?php

namespace App\Http\Requests;

use App\Models\Provider;
use App\Models\Repository;
use Illuminate\Foundation\Http\FormRequest;

class RepositoryWebhookSettingsRequest extends FormRequest
{
    /**
     * Keep resource authorization ahead of GitLab signing-token validation, matching the existing controller ordering.
     */
    public function authorize(): bool
    {
        $repository = $this->route('repository');

        return $repository instanceof Repository
            && ($this->user()?->can('update', $repository) ?? false);
    }

    /**
     * Validate a GitLab-generated signing token only for repositories using GitLab.
     *
     * @return array<string, list<string|callable>>
     */
    public function rules(): array
    {
        $repository = $this->route('repository');
        if (! $repository instanceof Repository) {
            return [];
        }

        $repository->loadMissing('provider');
        if ($repository->provider->provider !== Provider::TYPE_GITLAB) {
            return [];
        }

        return [
            'signing_token' => [
                'required',
                'string',
                'max:512',
                function (string $attribute, mixed $value, \Closure $fail): void {
                    $encoded = is_string($value) && str_starts_with($value, 'whsec_')
                        ? substr($value, 6)
                        : '';
                    $decoded = base64_decode($encoded, true);
                    if ($decoded === false || strlen($decoded) < 16) {
                        $fail(__('Enter the whsec_ signing token generated by GitLab.'));
                    }
                },
            ],
        ];
    }

    /**
     * Return the explicitly validated GitLab signing token, or null for providers that generate their own secret.
     */
    public function signingToken(): ?string
    {
        $token = $this->validated('signing_token');

        return is_string($token) ? $token : null;
    }
}
