<section class="mt-8 rounded-2xl border border-primary bg-primary p-6" id="operational-incidents">
    <div class="flex flex-wrap items-end justify-between gap-3">
        <div><p class="text-xs font-bold uppercase tracking-widest text-ternary">{{ __('Private response') }}</p><h2 class="mt-1 text-xl font-black text-primary">{{ __('Operational incidents') }}</h2><p class="mt-1 text-sm text-secondary">{{ __('Failures are grouped by resource, assigned to a responder, and closed automatically when recovery is detected.') }}</p></div>
        @if($canExportIncidents)<a class="button secondary" href="{{ route('observability.operational-incidents.export') }}">{{ __('Export evidence') }}</a>@endif
    </div>
    <div class="mt-5 space-y-3">
        @forelse($operationalIncidents as $incident)
            <article class="rounded-xl border border-primary bg-secondary p-4">
                <div class="flex flex-wrap items-start gap-3"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full px-2 py-1 text-[10px] font-bold uppercase {{ $incident->status === 'resolved' ? 'bg-green-100 text-green-800' : ($incident->severity === 'critical' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800') }}">{{ str($incident->status)->headline() }}</span><span class="text-xs text-secondary">{{ str($incident->severity)->headline() }} · {{ str($incident->category)->headline() }} #{{ $incident->resource_id }} · {{ trans_choice(':count occurrence|:count occurrences', $incident->occurrences, ['count'=>$incident->occurrences]) }}</span></div><h3 class="mt-2 font-black text-primary">{{ $incident->title }}</h3><p class="mt-1 text-sm text-secondary">{{ $incident->summary }}</p><p class="mt-2 text-xs text-secondary">{{ __('Detected :time · Owner: :owner', ['time'=>$incident->detected_at->diffForHumans(), 'owner'=>$incident->assignee?->name ?? __('Unassigned')]) }}</p></div>
                    @if($canOperate && $incident->status !== 'resolved')<form method="POST" action="{{ route('observability.operational-incidents.acknowledge',$incident) }}">@csrf<button type="submit" class="button secondary">{{ __('Acknowledge') }}</button></form>@endif
                </div>
                <details class="mt-4"><summary class="cursor-pointer text-xs font-bold text-ternary">{{ __('Timeline and response') }}</summary><ol class="mt-3 space-y-2 border-l border-primary pl-4">@foreach($incident->events->sortByDesc('occurred_at') as $event)<li><p class="text-xs font-bold text-primary">{{ str($event->type)->headline() }} · {{ $event->occurred_at->utc()->format('M j H:i').' UTC' }} @if($event->actor)· {{ $event->actor->name }}@endif</p><p class="text-sm text-secondary">{{ $event->message }}</p></li>@endforeach</ol>
                    @if($canOperate && $incident->status !== 'resolved')<div class="mt-4 grid gap-3 lg:grid-cols-3"><form method="POST" action="{{ route('observability.operational-incidents.assign',$incident) }}" class="flex gap-2">@csrf @method('PATCH')<select name="assigned_to" class="input secondary min-w-0 rounded-sm"><option value="">{{ __('Unassigned') }}</option>@foreach($incidentResponders as $responder)<option value="{{ $responder->id }}" @selected($incident->assigned_to === $responder->id)>{{ $responder->name }}</option>@endforeach</select><button type="submit" class="button secondary">{{ __('Assign') }}</button></form><form method="POST" action="{{ route('observability.operational-incidents.notes.store',$incident) }}" class="flex gap-2">@csrf<input name="message" maxlength="5000" required class="input secondary min-w-0 rounded-sm" placeholder="{{ __('Investigation note') }}"><button type="submit" class="button secondary">{{ __('Add note') }}</button></form><form method="POST" action="{{ route('observability.operational-incidents.resolve',$incident) }}" class="flex gap-2">@csrf<input name="resolution" maxlength="5000" required class="input secondary min-w-0 rounded-sm" placeholder="{{ __('Resolution and evidence') }}"><button type="submit" class="button primary">{{ __('Resolve') }}</button></form></div>@endif
                    @if($incident->resolution)<div class="mt-4 rounded-lg border border-primary bg-primary p-3"><p class="text-xs font-bold uppercase text-secondary">{{ __('Resolution') }}</p><p class="mt-1 text-sm text-primary">{{ $incident->resolution }}</p></div>@endif
                </details>
            </article>
        @empty
            <div class="rounded-xl border border-dashed border-primary p-4 text-sm text-secondary">{{ __('No operational incidents. New failures will appear here automatically.') }}</div>
        @endforelse
    </div>
</section>
