<?php

declare(strict_types=1);

use App\Http\Controllers\Account\AcceptInvitationController;
use App\Http\Controllers\Account\ChangeMemberRoleController;
use App\Http\Controllers\Account\ChangePlanController;
use App\Http\Controllers\Account\CreateApiTokenController;
use App\Http\Controllers\Account\DeleteAccountController;
use App\Http\Controllers\Account\EditAccountSettingsController;
use App\Http\Controllers\Account\InviteMemberController;
use App\Http\Controllers\Account\OpenBillingPortalController;
use App\Http\Controllers\Account\RemoveMemberController;
use App\Http\Controllers\Account\RenameAccountController;
use App\Http\Controllers\Account\ResumePlanController;
use App\Http\Controllers\Account\RevokeApiTokenController;
use App\Http\Controllers\Account\RevokeInvitationController;
use App\Http\Controllers\Account\ShowApiTokensController;
use App\Http\Controllers\Account\ShowAuditLogController;
use App\Http\Controllers\Account\ShowBillingController;
use App\Http\Controllers\Account\ShowInvitationController;
use App\Http\Controllers\Account\ShowMembersController;
use App\Http\Controllers\Account\SwitchAccountController;
use App\Http\Controllers\Account\UpdateMemberServicesController;
use App\Http\Controllers\Analytics\DeleteGoalController;
use App\Http\Controllers\Analytics\DeleteSiteController;
use App\Http\Controllers\Analytics\DownloadExportController;
use App\Http\Controllers\Analytics\RequestExportController;
use App\Http\Controllers\Analytics\ShowExportController;
use App\Http\Controllers\Analytics\ShowGoalsController;
use App\Http\Controllers\Analytics\ShowOverviewController;
use App\Http\Controllers\Analytics\ShowSiteController;
use App\Http\Controllers\Analytics\ShowSitesController;
use App\Http\Controllers\Analytics\StoreGoalController;
use App\Http\Controllers\Analytics\StoreSiteController;
use App\Http\Controllers\Analytics\UpdateGoalController;
use App\Http\Controllers\Analytics\UpdateSiteController;
use App\Http\Controllers\Analytics\VerifySiteController;
use App\Http\Controllers\Auth\ConfirmWithProviderController;
use App\Http\Controllers\Auth\ConnectProviderController;
use App\Http\Controllers\Auth\DisconnectProviderController;
use App\Http\Controllers\Auth\HandleProviderCallbackController;
use App\Http\Controllers\Auth\RedirectToProviderController;
use App\Http\Controllers\ComponentGalleryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Monitoring\ArchiveAlertDestinationController;
use App\Http\Controllers\Monitoring\ArchiveAlertRuleController;
use App\Http\Controllers\Monitoring\ArchiveMonitorController;
use App\Http\Controllers\Monitoring\ArchiveObjectiveController;
use App\Http\Controllers\Monitoring\CreateAlertRuleController;
use App\Http\Controllers\Monitoring\CreateMonitorController;
use App\Http\Controllers\Monitoring\CreateObjectiveController;
use App\Http\Controllers\Monitoring\CreateStatusPageController;
use App\Http\Controllers\Monitoring\DeleteMaintenanceWindowController;
use App\Http\Controllers\Monitoring\DeleteStatusPageController;
use App\Http\Controllers\Monitoring\EditAlertRuleController;
use App\Http\Controllers\Monitoring\EditMonitorController;
use App\Http\Controllers\Monitoring\EditObjectiveController;
use App\Http\Controllers\Monitoring\EditStatusPageController;
use App\Http\Controllers\Monitoring\ExportObjectiveController;
use App\Http\Controllers\Monitoring\RetryAlertDeliveryController;
use App\Http\Controllers\Monitoring\RevokeMonitorKeyController;
use App\Http\Controllers\Monitoring\RotateAlertDestinationSecretController;
use App\Http\Controllers\Monitoring\RotateMonitorKeyController;
use App\Http\Controllers\Monitoring\SendTestAlertController;
use App\Http\Controllers\Monitoring\ShowAlertDestinationController;
use App\Http\Controllers\Monitoring\ShowAlertDestinationsController;
use App\Http\Controllers\Monitoring\ShowAlertRuleController;
use App\Http\Controllers\Monitoring\ShowAlertRulesController;
use App\Http\Controllers\Monitoring\ShowIncidentController;
use App\Http\Controllers\Monitoring\ShowIncidentsController;
use App\Http\Controllers\Monitoring\ShowMaintenanceWindowsController;
use App\Http\Controllers\Monitoring\ShowMonitorController;
use App\Http\Controllers\Monitoring\ShowMonitorsController;
use App\Http\Controllers\Monitoring\ShowObjectiveController;
use App\Http\Controllers\Monitoring\ShowObjectivesController;
use App\Http\Controllers\Monitoring\ShowStatusPageController;
use App\Http\Controllers\Monitoring\ShowStatusPagesController;
use App\Http\Controllers\Monitoring\StoreAlertDestinationController;
use App\Http\Controllers\Monitoring\StoreAlertRuleController;
use App\Http\Controllers\Monitoring\StoreMaintenanceWindowController;
use App\Http\Controllers\Monitoring\StoreMonitorController;
use App\Http\Controllers\Monitoring\StoreObjectiveController;
use App\Http\Controllers\Monitoring\StoreStatusPageController;
use App\Http\Controllers\Monitoring\StoreStatusUpdateController;
use App\Http\Controllers\Monitoring\UpdateAlertDestinationController;
use App\Http\Controllers\Monitoring\UpdateAlertEscalationsController;
use App\Http\Controllers\Monitoring\UpdateAlertRoutingController;
use App\Http\Controllers\Monitoring\UpdateAlertRuleController;
use App\Http\Controllers\Monitoring\UpdateIncidentController;
use App\Http\Controllers\Monitoring\UpdateMaintenanceWindowController;
use App\Http\Controllers\Monitoring\UpdateMonitorController;
use App\Http\Controllers\Monitoring\UpdateObjectiveController;
use App\Http\Controllers\Monitoring\UpdateStatusPageController;
use App\Http\Controllers\Monitoring\UpdateStatusUpdateController;
use App\Http\Controllers\Notifications\MarkAllNotificationsReadController;
use App\Http\Controllers\Notifications\OpenNotificationController;
use App\Http\Controllers\Notifications\ShowNotificationsController;
use App\Http\Controllers\Projects\AddDomainController;
use App\Http\Controllers\Projects\CreateProjectController;
use App\Http\Controllers\Projects\DeleteEnvironmentController;
use App\Http\Controllers\Projects\DeleteProjectController;
use App\Http\Controllers\Projects\DisableProjectServiceController;
use App\Http\Controllers\Projects\DismissChecklistController;
use App\Http\Controllers\Projects\EditProjectSettingsController;
use App\Http\Controllers\Projects\EnableProjectServiceController;
use App\Http\Controllers\Projects\RemoveDomainController;
use App\Http\Controllers\Projects\ShowDomainsController;
use App\Http\Controllers\Projects\ShowProjectController;
use App\Http\Controllers\Projects\ShowProjectServiceController;
use App\Http\Controllers\Projects\StoreEnvironmentController;
use App\Http\Controllers\Projects\StoreProjectController;
use App\Http\Controllers\Projects\UpdateProjectController;
use App\Http\Controllers\Projects\VerifyDomainController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\Services\ShowServiceController;
use App\Http\Controllers\Settings\DeleteUserController;
use App\Http\Controllers\Settings\ExportPersonalDataController;
use App\Http\Controllers\Settings\ShowPrivacyController;
use App\Http\Controllers\Settings\ShowProfileController;
use App\Http\Controllers\Settings\ShowSecurityController;
use App\Http\Controllers\Settings\ShowSessionsController;
use App\Http\Controllers\Settings\SignOutBrowserController;
use App\Http\Controllers\Settings\SignOutOtherBrowsersController;
use App\Http\Controllers\StatusPages\ConfirmStatusSubscriptionController;
use App\Http\Controllers\StatusPages\RedirectLegacyStatusPageController;
use App\Http\Controllers\StatusPages\ShowPublicStatusPageController;
use App\Http\Controllers\StatusPages\ShowStatusPageReportController;
use App\Http\Controllers\StatusPages\ShowUnsubscribeController;
use App\Http\Controllers\StatusPages\SubscribeToStatusPageController;
use App\Http\Controllers\StatusPages\UnsubscribeFromStatusPageController;
use App\Http\Controllers\Telemetry\CreateIngestTokenController;
use App\Http\Controllers\Telemetry\RetryIngestReceiptController;
use App\Http\Controllers\Telemetry\RevokeIngestTokenController;
use App\Http\Controllers\Telemetry\RotateIngestTokenController;
use App\Http\Controllers\Telemetry\ShowDependencyMapController;
use App\Http\Controllers\Telemetry\ShowDeploymentController;
use App\Http\Controllers\Telemetry\ShowEventController;
use App\Http\Controllers\Telemetry\ShowEventsController;
use App\Http\Controllers\Telemetry\ShowIngestReceiptsController;
use App\Http\Controllers\Telemetry\ShowIssueController;
use App\Http\Controllers\Telemetry\ShowIssuesController;
use App\Http\Controllers\Telemetry\ShowReleaseController;
use App\Http\Controllers\Telemetry\ShowReleasesController;
use App\Http\Controllers\Telemetry\ShowTelemetrySetupController;
use App\Http\Controllers\Telemetry\ShowTraceController;
use App\Http\Controllers\Telemetry\StoreDeploymentController;
use App\Http\Controllers\Telemetry\UpdateIssueController;
use App\Http\Controllers\Webhooks\StripeWebhookController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');

Route::get('/_gallery', ComponentGalleryController::class)->name('gallery');

Route::get('/invitations/{token}', ShowInvitationController::class)->name('invitations.show');

// Public status pages (the old apps' URLs).
Route::get('/status/subscriptions/{subscription}/confirm/{token}', ConfirmStatusSubscriptionController::class)->whereNumber('subscription')->middleware('throttle:20,1')->name('status.subscriptions.confirm');
Route::get('/status/subscriptions/{subscription}/unsubscribe/{token}', ShowUnsubscribeController::class)->whereNumber('subscription')->middleware('throttle:20,1')->name('status.subscriptions.unsubscribe');
Route::post('/status/subscriptions/{subscription}/unsubscribe/{token}', UnsubscribeFromStatusPageController::class)->whereNumber('subscription')->middleware('throttle:20,1')->name('status.subscriptions.unsubscribe.store');
Route::get('/status/{product}/{slug}', RedirectLegacyStatusPageController::class)->whereIn('product', ['deployer', 'monitor'])->where('slug', '[a-z0-9-]+');
Route::get('/status/{slug}', ShowPublicStatusPageController::class)->where('slug', '[a-z0-9-]+')->middleware('throttle:120,1')->name('status.show');
Route::get('/status/{slug}/report.json', ShowStatusPageReportController::class)->where('slug', '[a-z0-9-]+')->middleware('throttle:120,1')->name('status.report');
Route::post('/status/{slug}/subscribe', SubscribeToStatusPageController::class)->where('slug', '[a-z0-9-]+')->middleware('throttle:5,1')->name('status.subscribe');

Route::post('/webhooks/stripe', StripeWebhookController::class)->middleware('throttle:600,1')->name('webhooks.stripe');

Route::get('/auth/{provider}/redirect', RedirectToProviderController::class)->middleware(['guest', 'throttle:20,1'])->name('social.redirect');
// Shared by sign-in, connecting a provider and sudo-mode confirmation; the controller tells them apart.
Route::get('/auth/{provider}/callback', HandleProviderCallbackController::class)->middleware('throttle:20,1')->name('social.callback');
Route::post('/user/confirm-password/{provider}', ConfirmWithProviderController::class)->middleware(['auth', 'throttle:10,1'])->name('social.confirm');

Route::middleware(['auth', 'verified'])->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/invitations/{token}', AcceptInvitationController::class)->middleware('throttle:10,1')->name('invitations.accept');

    Route::get('/search', SearchController::class)->middleware('throttle:120,1')->name('search');
    Route::get('/notifications', ShowNotificationsController::class)->name('notifications.index');
    Route::post('/notifications/read', MarkAllNotificationsReadController::class)->name('notifications.read-all');
    Route::get('/notifications/{notification}', OpenNotificationController::class)->name('notifications.open');

    Route::get('/services/{service}', ShowServiceController::class)->name('services.show');
    Route::get('/projects/create', CreateProjectController::class)->name('projects.create');
    Route::post('/projects', StoreProjectController::class)->middleware('throttle:30,1')->name('projects.store');
    Route::prefix('/projects/{project}')->middleware('project.context')->group(function (): void {
        Route::prefix('/analytics')->middleware('service:analytics')->name('analytics.')->group(function (): void {
            Route::get('/', ShowOverviewController::class)->name('overview');
            Route::get('/sites', ShowSitesController::class)->name('sites');
            Route::post('/sites', StoreSiteController::class)->middleware('throttle:30,1')->name('sites.store');
            Route::get('/sites/{site}', ShowSiteController::class)->whereNumber('site')->name('sites.show');
            Route::put('/sites/{site}', UpdateSiteController::class)->whereNumber('site')->name('sites.update');
            Route::post('/sites/{site}/verify', VerifySiteController::class)->whereNumber('site')->middleware('throttle:20,1')->name('sites.verify');
            Route::delete('/sites/{site}', DeleteSiteController::class)->whereNumber('site')->middleware('password.confirm')->name('sites.destroy');
            Route::get('/goals', ShowGoalsController::class)->name('goals');
            Route::post('/sites/{site}/goals', StoreGoalController::class)->whereNumber('site')->name('goals.store');
            Route::put('/sites/{site}/goals/{goal}', UpdateGoalController::class)->whereNumber(['site', 'goal'])->name('goals.update');
            Route::delete('/sites/{site}/goals/{goal}', DeleteGoalController::class)->whereNumber(['site', 'goal'])->name('goals.destroy');
            Route::post('/sites/{site}/exports', RequestExportController::class)->whereNumber('site')->middleware('throttle:10,1')->name('exports.store');
            Route::get('/exports/{token}', ShowExportController::class)->name('exports.show');
            Route::get('/exports/{token}/download', DownloadExportController::class)->name('exports.download');
        });

        Route::prefix('/monitoring')->middleware('service:monitoring')->name('monitoring.')->group(function (): void {
            Route::get('/', ShowMonitorsController::class)->name('monitors');
            Route::get('/monitors/create', CreateMonitorController::class)->name('monitors.create');
            Route::post('/monitors', StoreMonitorController::class)->middleware('throttle:30,1')->name('monitors.store');
            Route::get('/monitors/{monitor}', ShowMonitorController::class)->whereNumber('monitor')->name('monitors.show');
            Route::get('/monitors/{monitor}/edit', EditMonitorController::class)->whereNumber('monitor')->name('monitors.edit');
            Route::put('/monitors/{monitor}', UpdateMonitorController::class)->whereNumber('monitor')->middleware('throttle:30,1')->name('monitors.update');
            Route::delete('/monitors/{monitor}', ArchiveMonitorController::class)->whereNumber('monitor')->middleware('throttle:30,1')->name('monitors.archive');
            Route::post('/monitors/{monitor}/key', RotateMonitorKeyController::class)->whereNumber('monitor')->middleware('throttle:10,1')->name('monitors.key.rotate');
            Route::delete('/monitors/{monitor}/key', RevokeMonitorKeyController::class)->whereNumber('monitor')->middleware('throttle:10,1')->name('monitors.key.revoke');
            Route::get('/incidents', ShowIncidentsController::class)->name('incidents');
            Route::get('/incidents/{incident}', ShowIncidentController::class)->whereNumber('incident')->name('incidents.show');
            Route::patch('/incidents/{incident}', UpdateIncidentController::class)->whereNumber('incident')->middleware('throttle:60,1')->name('incidents.update');
            Route::get('/alerts', ShowAlertDestinationsController::class)->name('destinations');
            Route::post('/alerts', StoreAlertDestinationController::class)->middleware('throttle:30,1')->name('destinations.store');
            Route::get('/alerts/{destination}', ShowAlertDestinationController::class)->whereNumber('destination')->name('destinations.show');
            Route::put('/alerts/{destination}', UpdateAlertDestinationController::class)->whereNumber('destination')->middleware('throttle:30,1')->name('destinations.update');
            Route::delete('/alerts/{destination}', ArchiveAlertDestinationController::class)->whereNumber('destination')->middleware('throttle:30,1')->name('destinations.archive');
            Route::post('/alerts/{destination}/rotate', RotateAlertDestinationSecretController::class)->whereNumber('destination')->middleware('throttle:10,1')->name('destinations.rotate');
            Route::post('/alerts/{destination}/test', SendTestAlertController::class)->whereNumber('destination')->middleware('throttle:alert-tests')->name('destinations.test');
            Route::post('/deliveries/{delivery}/retry', RetryAlertDeliveryController::class)->whereUlid('delivery')->middleware('throttle:10,1')->name('deliveries.retry');
            Route::get('/maintenance', ShowMaintenanceWindowsController::class)->name('maintenance');
            Route::post('/maintenance', StoreMaintenanceWindowController::class)->middleware('throttle:30,1')->name('maintenance.store');
            Route::put('/maintenance/{window}', UpdateMaintenanceWindowController::class)->whereNumber('window')->middleware('throttle:30,1')->name('maintenance.update');
            Route::delete('/maintenance/{window}', DeleteMaintenanceWindowController::class)->whereNumber('window')->middleware('throttle:30,1')->name('maintenance.destroy');

            Route::get('/status-pages', ShowStatusPagesController::class)->name('status-pages');
            Route::get('/status-pages/create', CreateStatusPageController::class)->name('status-pages.create');
            Route::post('/status-pages', StoreStatusPageController::class)->middleware('throttle:30,1')->name('status-pages.store');
            Route::get('/status-pages/{page}', ShowStatusPageController::class)->whereNumber('page')->name('status-pages.show');
            Route::get('/status-pages/{page}/edit', EditStatusPageController::class)->whereNumber('page')->name('status-pages.edit');
            Route::put('/status-pages/{page}', UpdateStatusPageController::class)->whereNumber('page')->middleware('throttle:30,1')->name('status-pages.update');
            Route::delete('/status-pages/{page}', DeleteStatusPageController::class)->whereNumber('page')->middleware('throttle:30,1')->name('status-pages.destroy');
            Route::post('/status-pages/{page}/updates', StoreStatusUpdateController::class)->whereNumber('page')->middleware('throttle:30,1')->name('status-pages.updates.store');
            Route::put('/status-pages/{page}/updates/{update}', UpdateStatusUpdateController::class)->whereNumber(['page', 'update'])->middleware('throttle:30,1')->name('status-pages.updates.update');

            Route::get('/rules', ShowAlertRulesController::class)->name('rules');
            Route::get('/rules/create', CreateAlertRuleController::class)->name('rules.create');
            Route::post('/rules', StoreAlertRuleController::class)->middleware('throttle:60,1')->name('rules.store');
            Route::get('/rules/{rule}', ShowAlertRuleController::class)->whereNumber('rule')->name('rules.show');
            Route::get('/rules/{rule}/edit', EditAlertRuleController::class)->whereNumber('rule')->name('rules.edit');
            Route::put('/rules/{rule}', UpdateAlertRuleController::class)->whereNumber('rule')->middleware('throttle:60,1')->name('rules.update');
            Route::delete('/rules/{rule}', ArchiveAlertRuleController::class)->whereNumber('rule')->middleware('throttle:60,1')->name('rules.archive');
            Route::put('/rules/{rule}/routing', UpdateAlertRoutingController::class)->whereNumber('rule')->middleware('throttle:30,1')->name('rules.routing');
            Route::put('/rules/{rule}/escalations', UpdateAlertEscalationsController::class)->whereNumber('rule')->middleware('throttle:30,1')->name('rules.escalations');
            Route::get('/objectives', ShowObjectivesController::class)->name('objectives');
            Route::get('/objectives/create', CreateObjectiveController::class)->name('objectives.create');
            Route::post('/objectives', StoreObjectiveController::class)->middleware('throttle:30,1')->name('objectives.store');
            Route::get('/objectives/{objective}', ShowObjectiveController::class)->whereNumber('objective')->name('objectives.show');
            Route::get('/objectives/{objective}/edit', EditObjectiveController::class)->whereNumber('objective')->name('objectives.edit');
            Route::put('/objectives/{objective}', UpdateObjectiveController::class)->whereNumber('objective')->middleware('throttle:30,1')->name('objectives.update');
            Route::delete('/objectives/{objective}', ArchiveObjectiveController::class)->whereNumber('objective')->middleware('throttle:30,1')->name('objectives.archive');
            Route::get('/objectives/{objective}/export', ExportObjectiveController::class)->whereNumber('objective')->middleware('throttle:30,1')->name('objectives.export');

            Route::get('/issues', ShowIssuesController::class)->name('issues');
            Route::get('/issues/{issue}', ShowIssueController::class)->whereNumber('issue')->name('issues.show');
            Route::patch('/issues/{issue}', UpdateIssueController::class)->whereNumber('issue')->middleware('throttle:60,1')->name('issues.update');
            Route::get('/events', ShowEventsController::class)->name('events');
            Route::get('/events/{event}', ShowEventController::class)->whereNumber('event')->name('events.show');
            Route::get('/traces/{trace}', ShowTraceController::class)->where('trace', '[A-Za-z0-9._:-]{1,64}')->name('traces.show');
            Route::get('/dependencies', ShowDependencyMapController::class)->name('dependencies');
            Route::get('/releases', ShowReleasesController::class)->name('releases');
            Route::get('/releases/{release}', ShowReleaseController::class)->whereNumber('release')->name('releases.show');
            Route::post('/deployments', StoreDeploymentController::class)->middleware('throttle:60,1')->name('deployments.store');
            Route::get('/deployments/{deployment}', ShowDeploymentController::class)->whereNumber('deployment')->name('deployments.show');
            Route::get('/setup', ShowTelemetrySetupController::class)->name('setup');
            Route::post('/environments/{environment}/keys', CreateIngestTokenController::class)->middleware('throttle:30,1')->name('keys.store');
            Route::post('/keys/{token}/rotate', RotateIngestTokenController::class)->whereNumber('token')->middleware('throttle:30,1')->name('keys.rotate');
            Route::delete('/keys/{token}', RevokeIngestTokenController::class)->whereNumber('token')->middleware('throttle:30,1')->name('keys.revoke');
            Route::get('/environments/{environment}/deliveries', ShowIngestReceiptsController::class)->name('ingest.deliveries');
            Route::post('/ingest-deliveries/{receipt}/retry', RetryIngestReceiptController::class)->whereUlid('receipt')->middleware('throttle:30,1')->name('ingest.retry');
        });

        Route::get('/', ShowProjectController::class)->name('projects.show');
        Route::delete('/checklist', DismissChecklistController::class)->name('projects.checklist.dismiss');
        Route::get('/settings', EditProjectSettingsController::class)->name('projects.settings');
        Route::put('/settings', UpdateProjectController::class)->name('projects.update');
        Route::delete('/', DeleteProjectController::class)->middleware('password.confirm')->name('projects.destroy');
        Route::post('/environments', StoreEnvironmentController::class)->name('projects.environments.store');
        Route::delete('/environments/{environment}', DeleteEnvironmentController::class)->name('projects.environments.destroy');
        Route::get('/domains', ShowDomainsController::class)->name('projects.domains');
        Route::post('/domains', AddDomainController::class)->middleware('throttle:30,1')->name('projects.domains.store');
        Route::post('/domains/{domain}/verify', VerifyDomainController::class)->middleware('throttle:20,1')->name('projects.domains.verify');
        Route::delete('/domains/{domain}', RemoveDomainController::class)->name('projects.domains.destroy');
        Route::get('/services/{service}', ShowProjectServiceController::class)->name('projects.services.show');
        Route::post('/services/{service}', EnableProjectServiceController::class)->name('projects.services.store');
        Route::delete('/services/{service}', DisableProjectServiceController::class)->name('projects.services.destroy');
    });

    Route::post('/accounts/{account}/switch', SwitchAccountController::class)->name('accounts.switch');
    Route::redirect('/account', '/account/members')->name('account');
    Route::get('/account/members', ShowMembersController::class)->name('account.members');
    Route::post('/account/invitations', InviteMemberController::class)->middleware('throttle:20,1')->name('account.invitations.store');
    Route::delete('/account/invitations/{invitation}', RevokeInvitationController::class)->name('account.invitations.destroy');
    Route::put('/account/members/{membership}', ChangeMemberRoleController::class)->name('account.members.update');
    Route::delete('/account/members/{membership}', RemoveMemberController::class)->name('account.members.destroy');
    Route::put('/account/members/{membership}/services', UpdateMemberServicesController::class)->name('account.members.services');
    Route::get('/account/api-tokens', ShowApiTokensController::class)->name('account.api-tokens');
    Route::post('/account/api-tokens', CreateApiTokenController::class)->middleware(['password.confirm', 'throttle:20,1'])->name('account.api-tokens.store');
    Route::delete('/account/api-tokens/{token}', RevokeApiTokenController::class)->whereNumber('token')->name('account.api-tokens.destroy');
    Route::get('/account/billing', ShowBillingController::class)->name('account.billing');
    Route::post('/account/billing/portal', OpenBillingPortalController::class)->name('account.billing.portal');
    Route::post('/account/billing/{service}', ChangePlanController::class)->middleware('throttle:20,1')->name('account.billing.change');
    Route::post('/account/billing/{service}/resume', ResumePlanController::class)->name('account.billing.resume');
    Route::get('/account/audit-log', ShowAuditLogController::class)->name('account.audit-log');
    Route::get('/account/settings', EditAccountSettingsController::class)->name('account.settings');
    Route::put('/account/settings', RenameAccountController::class)->name('account.settings.update');
    Route::delete('/account/settings', DeleteAccountController::class)->middleware('password.confirm')->name('account.settings.destroy');

    Route::redirect('/settings', '/settings/profile')->name('settings');
    Route::get('/settings/profile', ShowProfileController::class)->name('settings.profile');
    // Security changes need a recent password (or passkey) confirmation, like Fortify's own 2FA and passkey routes.
    Route::get('/settings/security', ShowSecurityController::class)->middleware('password.confirm')->name('settings.security');
    Route::post('/settings/security/social/{provider}', ConnectProviderController::class)->middleware(['password.confirm', 'throttle:10,1'])->name('social.connect');
    Route::get('/settings/sessions', ShowSessionsController::class)->name('settings.sessions');
    Route::get('/settings/privacy', ShowPrivacyController::class)->name('settings.privacy');
    Route::get('/settings/privacy/export', ExportPersonalDataController::class)->middleware('throttle:6,1')->name('settings.privacy.export');
    Route::delete('/settings/privacy/user', DeleteUserController::class)->middleware('password.confirm')->name('settings.privacy.destroy');
    Route::delete('/settings/sessions', SignOutOtherBrowsersController::class)->name('settings.sessions.destroy-others');
    Route::delete('/settings/sessions/{session}', SignOutBrowserController::class)->name('settings.sessions.destroy');
    Route::delete('/settings/security/social/{provider}', DisconnectProviderController::class)->middleware('password.confirm')->name('social.disconnect');
});
