<x-layouts.core :title="__('Privacy Policy')" :description="__('How BuildPusher collects, uses, protects, and deletes account and infrastructure data.')" :canonical="route('privacy')" :indexable="true" :livewire="false">
    <main class="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
        <a href="/" class="text-sm font-black uppercase tracking-[.18em] text-ternary">{{ config('app.name') }}</a>
        <h1 class="mt-5 text-4xl font-black tracking-tight text-primary">{{ __('Privacy Policy') }}</h1>
        <p class="mt-2 text-sm text-secondary">{{ __('Effective :date', ['date' => config('legal.effective_date')]) }}</p>
        <div class="mt-10 space-y-8 leading-7 text-secondary">
            <section><h2 class="text-xl font-bold text-primary">{{ __('Information we process') }}</h2><p class="mt-2">{{ __('BuildPusher processes account details, workspace membership, sign-in and security records, infrastructure metadata, deployment history, logs you request us to retain, and encrypted credentials required to perform actions you authorize. Payment information is handled by the configured payment processor when billing is enabled; BuildPusher does not store full card numbers.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('How information is used') }}</h2><p class="mt-2">{{ __('We use information to authenticate users, review access requests, provision and manage infrastructure, execute deployments, monitor service health, deliver alerts, prevent abuse, provide support, and improve reliability. We do not sell personal information or use private application data for advertising.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Access requests') }}</h2><p class="mt-2">{{ __('When registration is invitation-only, we retain the contact details, team information, plan interest, and deployment use case you voluntarily submit. These fields are encrypted at rest and visible only to platform administrators. Declined and accepted requests are automatically removed after the configured retention period; pending requests remain available so we can respond.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Storage and sharing') }}</h2><p class="mt-2">{{ __('Sensitive values are encrypted at rest. Information is shared only with infrastructure, source-control, email, monitoring, and payment providers needed to deliver features you choose, or when legally required. Your connected providers may process requests under their own terms.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Retention and control') }}</h2><p class="mt-2">{{ __('Operational records are retained only for bounded product and security purposes. You can export your account data from Account settings. You can also delete an eligible account after removing teammates and finishing active operations. Provider-side servers and resources remain in your provider account unless you delete them there.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Your choices') }}</h2><p class="mt-2">{{ __('You may request access, correction, export, or deletion of personal information. You can disconnect integrations, revoke sessions and tokens, and change notification settings available in the product.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Contact') }}</h2><p class="mt-2">{{ __('Privacy questions can be sent to') }} <a class="font-semibold text-ternary underline" href="mailto:{{ config('legal.contact_email') }}">{{ config('legal.contact_email') }}</a>.</p></section>
        </div>
        <footer class="mt-12 border-t border-primary pt-6 text-sm text-secondary"><a class="underline" href="{{ route('terms') }}">{{ __('Terms of Service') }}</a> · <a class="underline" href="{{ route('platform-status.show') }}">{{ __('Service status') }}</a></footer>
    </main>
</x-layouts.core>
