<x-layouts.core :title="__('Terms of Service')" :description="__('Terms governing use of BuildPusher infrastructure and deployment services.')" :canonical="route('terms')" :indexable="true" :livewire="false">
    <main class="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
        <a href="/" class="text-sm font-black uppercase tracking-[.18em] text-ternary">{{ config('app.name') }}</a>
        <h1 class="mt-5 text-4xl font-black tracking-tight text-primary">{{ __('Terms of Service') }}</h1>
        <p class="mt-2 text-sm text-secondary">{{ __('Effective :date', ['date' => config('legal.effective_date')]) }}</p>
        <div class="mt-10 space-y-8 leading-7 text-secondary">
            <section><h2 class="text-xl font-bold text-primary">{{ __('Using BuildPusher') }}</h2><p class="mt-2">{{ __('You must provide accurate account information, protect your credentials and recovery codes, and use BuildPusher only for systems you are authorized to manage. You are responsible for activity performed through your account and connected provider accounts.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Acceptable use') }}</h2><p class="mt-2">{{ __('Do not use the service to break the law, compromise systems, distribute malware, evade provider limits, interfere with other users, or deploy content that violates another person’s rights. We may restrict access needed to protect the service or others.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Your infrastructure and content') }}</h2><p class="mt-2">{{ __('You retain ownership of your code and data. Infrastructure generally runs in provider accounts you connect. Provider charges, provider availability, domain configuration, licensing, backups, and the legality of deployed content remain your responsibility.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Operational safety') }}</h2><p class="mt-2">{{ __('Deployment, command, restore, scaling, and deletion operations can change live systems. Review targets and maintain independent backups. BuildPusher supplies guardrails and logs but cannot guarantee that every third-party service, script, or application will behave as expected.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Availability and termination') }}</h2><p class="mt-2">{{ __('The service may change, experience interruption, or suspend unsafe activity. You may stop using BuildPusher and delete an eligible account. Account deletion removes BuildPusher control-plane data but does not automatically destroy resources remaining in external provider accounts.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Warranty and liability') }}</h2><p class="mt-2">{{ __('To the extent permitted by applicable law, BuildPusher is provided without warranties of uninterrupted or error-free operation. BuildPusher is not responsible for indirect or consequential loss, lost profits, or provider-side outages. Rights that cannot legally be excluded remain unaffected.') }}</p></section>
            <section><h2 class="text-xl font-bold text-primary">{{ __('Contact') }}</h2><p class="mt-2">{{ __('Questions about these terms can be sent to') }} <a class="font-semibold text-ternary underline" href="mailto:{{ config('legal.contact_email') }}">{{ config('legal.contact_email') }}</a>.</p></section>
        </div>
        <footer class="mt-12 border-t border-primary pt-6 text-sm text-secondary"><a class="underline" href="{{ route('privacy') }}">{{ __('Privacy Policy') }}</a> · <a class="underline" href="{{ route('platform-status.show') }}">{{ __('Service status') }}</a></footer>
    </main>
</x-layouts.core>
