<x-layouts.core :title="__('Terms of Service')" :description="__('Terms governing use of :app infrastructure and deployment services.', ['app' => config('app.name')])" :canonical="route('terms')" :indexable="true" :livewire="false">
    <x-layouts.public-header navigation-label="Terms navigation" />
    <main class="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
        <h1 class="mt-5 text-4xl font-extrabold tracking-tight text-ink">{{ __('Terms of Service') }}</h1>
        <p class="mt-2 text-sm text-muted">{{ __('Effective :date', ['date' => config('legal.effective_date')]) }}</p>
        <div class="mt-10 space-y-8 leading-7 text-muted">
            <section><h2 class="text-xl font-bold text-ink">{{ __('Using :app', ['app' => config('app.name')]) }}</h2><p class="mt-2">{{ __('You must provide accurate account information, protect your credentials and recovery codes, and use :app only for systems you are authorized to manage. You are responsible for activity performed through your account and connected provider accounts.', ['app' => config('app.name')]) }}</p></section>
            <section><h2 class="text-xl font-bold text-ink">{{ __('Acceptable use') }}</h2><p class="mt-2">{{ __('Do not use the service to break the law, compromise systems, distribute malware, evade provider limits, interfere with other users, or deploy content that violates another person’s rights. We may restrict access needed to protect the service or others.') }}</p></section>
            <section><h2 class="text-xl font-bold text-ink">{{ __('Your infrastructure and content') }}</h2><p class="mt-2">{{ __('You retain ownership of your code and data. Infrastructure generally runs in provider accounts you connect. Provider charges, provider availability, domain configuration, licensing, backups, and the legality of deployed content remain your responsibility.') }}</p></section>
            <section><h2 class="text-xl font-bold text-ink">{{ __('Operational safety') }}</h2><p class="mt-2">{{ __('Deployment, command, restore, scaling, and deletion operations can change live systems. Review targets and maintain independent backups. :app supplies guardrails and logs but cannot guarantee that every third-party service, script, or application will behave as expected.', ['app' => config('app.name')]) }}</p></section>
            <section><h2 class="text-xl font-bold text-ink">{{ __('Availability and termination') }}</h2><p class="mt-2">{{ __('The service may change, experience interruption, or suspend unsafe activity. You may stop using :app and delete an eligible account. Account deletion removes :app control-plane data but does not automatically destroy resources remaining in external provider accounts.', ['app' => config('app.name')]) }}</p></section>
            <section><h2 class="text-xl font-bold text-ink">{{ __('Warranty and liability') }}</h2><p class="mt-2">{{ __('To the extent permitted by applicable law, :app is provided without warranties of uninterrupted or error-free operation. :app is not responsible for indirect or consequential loss, lost profits, or provider-side outages. Rights that cannot legally be excluded remain unaffected.', ['app' => config('app.name')]) }}</p></section>
            <section><h2 class="text-xl font-bold text-ink">{{ __('Contact') }}</h2><p class="mt-2">{{ __('Questions about these terms can be sent to') }} <a class="ui-link" href="mailto:{{ config('legal.contact_email') }}">{{ config('legal.contact_email') }}</a>.</p></section>
        </div>
        <footer class="mt-12 border-t border-line pt-6 text-sm text-muted"><a class="ui-link" href="{{ route('privacy') }}">{{ __('Privacy Policy') }}</a> · <a class="ui-link" href="{{ route('platform-status.show') }}">{{ __('Service status') }}</a></footer>
    </main>
</x-layouts.core>
