<x-layouts.app>
    <x-layouts.partials.breadcrumbs :route="route('projects.index')" :title="__('Back to applications')" />

    <div class="mt-6 flex flex-wrap items-start justify-between gap-4">
        <x-layouts.partials.heading icon="view-grid" :title="$project->name" :description="$project->description ?: __('Application environments and resources.')" />
        @if($canManage)<a href="{{ route('projects.configuration.create', $project) }}" class="button secondary">{{ __('Configuration as code') }}</a>@endif
        @if($canManage)<form method="POST" action="{{ route('projects.destroy', $project) }}">@csrf @method('DELETE')<button type="submit" class="button tertiary">{{ __('Delete application') }}</button></form>@endif
    </div>

    <section class="mt-8 grid overflow-hidden rounded-2xl border border-primary bg-primary sm:grid-cols-2 xl:grid-cols-4">
        <div class="border-b border-primary p-4 sm:border-r xl:border-b-0"><p class="text-xs font-bold uppercase tracking-wider text-secondary">{{ __('Environments') }}</p><p class="mt-1 text-2xl font-black text-primary">{{ $project->environments->count() }}</p></div>
        <div class="border-b border-primary p-4 xl:border-b-0 xl:border-r"><p class="text-xs font-bold uppercase tracking-wider text-secondary">{{ __('Attached sites') }}</p><p class="mt-1 text-2xl font-black text-primary">{{ $project->environments->whereNotNull('website_id')->count() }}</p></div>
        <div class="border-b border-primary p-4 sm:border-r sm:border-b-0"><p class="text-xs font-bold uppercase tracking-wider text-secondary">{{ __('Runtime') }}</p><p class="mt-1 font-black text-primary">{{ $project->environments->contains(fn ($environment) => $environment->hibernated_at) ? __('Partially hibernated') : __('Running') }}</p></div>
        <div class="p-4"><p class="text-xs font-bold uppercase tracking-wider text-secondary">{{ __('Previews') }}</p><p class="mt-1 font-black text-primary">{{ $project->preview_enabled ? __('Enabled') : __('Disabled') }}</p></div>
    </section>

    <div class="mt-5 space-y-4">
        @foreach($project->environments as $environment)
            @php
                $environmentRepositories = $environment->website?->repositories ?? collect();
                $repository = $environmentRepositories->firstWhere('branch', $environment->branch);
                $deploymentInProgress = $environmentRepositories->contains(fn ($source) => $source->latestBuild && in_array($source->latestBuild->status, \App\Models\Build::ACTIVE_STATUSES, true));
                $deploymentReady = $repository?->isDeploymentReady() === true;
                $successfulBuild = $repository?->latestSuccessfulBuild;
                if ($successfulBuild?->environment_id !== $environment->id) $successfulBuild = null;
                $environmentRanks = ['preview' => 0, 'development' => 1, 'staging' => 2, 'production' => 3];
                $promotionTargets = $project->environments->filter(function ($candidate) use ($environmentRanks, $environment, $repository) {
                    $targetRepository = $candidate->website?->repositories->firstWhere('branch', $candidate->branch);
                    return ($environmentRanks[$candidate->type] ?? -1) > ($environmentRanks[$environment->type] ?? -1)
                        && $repository && $targetRepository
                        && strtolower(rtrim($repository->url, '/')) === strtolower(rtrim($targetRepository->url, '/'))
                        && $repository->provider?->provider === $targetRepository->provider?->provider;
                });
            @endphp
            <section class="overflow-hidden rounded-2xl border border-primary bg-primary shadow-sm">
                <div class="flex flex-wrap items-center gap-4 border-b border-primary px-5 py-4">
                    <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary font-black text-ternary">{{ strtoupper(substr($environment->name, 0, 1)) }}</div>
                    <div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="text-lg font-black text-primary">{{ $environment->name }}</h2>@if($environment->is_protected)<span class="rounded-full bg-ternary px-2 py-0.5 text-[10px] font-bold uppercase text-white">{{ __('Protected') }}</span>@endif @if($environment->hibernated_at)<span class="rounded-full bg-secondary px-2 py-0.5 text-[10px] font-bold uppercase text-secondary">{{ __('Hibernated') }}</span>@endif</div><p class="mt-0.5 truncate font-mono text-xs text-secondary">{{ $environment->branch }} · {{ ucfirst($environment->type) }}</p></div>
                    <div class="flex flex-wrap gap-2 text-xs"><span class="rounded-lg bg-secondary px-3 py-2 text-secondary">{{ $environment->server?->label ?? __('No server') }}</span><span class="rounded-lg bg-secondary px-3 py-2 text-secondary">{{ $environment->website?->name ?? __('No site') }}</span><span class="rounded-lg bg-secondary px-3 py-2 font-bold text-secondary">{{ $environment->minimum_replicas }}–{{ $environment->maximum_replicas }}×</span></div>
                </div>

                @if(!$repository?->builds()->where('status', \App\Models\Build::STATUS_SUCCEEDED)->exists())
                    @php($readiness = [
                        ['label' => __('Active server attached'), 'ready' => $environment->server?->provisioning_status === \App\Models\Server::STATUS_ACTIVE, 'url' => route('servers.index')],
                        ['label' => __('Active website attached'), 'ready' => $environment->website?->provisioning_status === \App\Models\Website::STATUS_ACTIVE, 'url' => route('websites.index')],
                        ['label' => __('Repository and branch connected'), 'ready' => (bool) $repository, 'url' => $environment->website ? route('repositories.create', ['website_id' => $environment->website_id, 'branch' => $environment->branch]) : route('websites.create')],
                        ['label' => __('Provider credentials available'), 'ready' => (bool) $repository?->provider_id, 'url' => route('providers.index')],
                    ])
                    @php($readyCount = collect($readiness)->where('ready', true)->count())
                    <aside class="border-b border-primary bg-blue-50 px-5 py-4" aria-label="{{ __('First deployment readiness') }}">
                        <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="font-bold text-blue-950">{{ __('First deployment readiness') }}</p><p class="mt-1 text-xs text-blue-800">{{ __(':ready of :total checks passed. Deployment stays disabled until every dependency is active.', ['ready' => $readyCount, 'total' => count($readiness)]) }}</p></div><a href="{{ route('docs') }}#first-deploy" class="text-xs font-bold text-blue-800 underline">{{ __('Open setup guide') }}</a></div>
                        <ul class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($readiness as $check)<li class="flex items-center gap-2 text-xs {{ $check['ready'] ? 'text-green-800' : 'text-blue-900' }}"><span aria-hidden="true" class="font-black">{{ $check['ready'] ? '✓' : '○' }}</span>@if($check['ready'])<span>{{ $check['label'] }}</span>@else<a href="{{ $check['url'] }}" class="font-bold underline">{{ $check['label'] }}</a>@endif</li>@endforeach</ul>
                    </aside>
                @endif

                <div class="flex flex-wrap items-center gap-3 border-b border-primary bg-secondary px-5 py-3">
                    <div class="min-w-0 flex-1">
                        @if($repository)
                            <p class="truncate text-sm font-bold text-primary">{{ $repository->name }} <span class="font-mono font-normal text-secondary">· {{ $repository->branch }}</span></p>
                            <p class="mt-0.5 text-xs text-secondary">@if($repository->latestBuild){{ __('Latest deployment: :status', ['status' => str($repository->latestBuild->status)->replace('_', ' ')]) }}@else{{ __('Ready for the first deployment') }}@endif</p>
                        @elseif($environment->website)
                            <p class="text-sm font-bold text-primary">{{ __('Connect source control') }}</p><p class="mt-0.5 text-xs text-secondary">{{ __('Attach a repository to complete this environment.') }}</p>
                        @else
                            <p class="text-sm font-bold text-primary">{{ __('Attach infrastructure') }}</p><p class="mt-0.5 text-xs text-secondary">{{ __('Select a ready server and website before connecting source control.') }}</p>
                        @endif
                    </div>
                    @if($repository)
                        <a href="{{ route('repositories.show', $repository) }}" class="button secondary">{{ __('View source') }}</a>
                        @if($canDeploy)<form method="POST" action="{{ route('repositories.deploy', $repository) }}">@csrf<button type="submit" class="button primary" @disabled(!$deploymentReady || $deploymentInProgress)>{{ $deploymentInProgress ? __('Deploying…') : ($deploymentReady ? __('Deploy now') : __('Not ready')) }}</button></form>@endif
                    @elseif($environment->website && $canDeploy)
                        <a href="{{ route('repositories.create', ['website_id' => $environment->website_id, 'branch' => $environment->branch]) }}" class="button primary">{{ __('Connect repository') }}</a>
                    @elseif($canDeploy)
                        <a href="{{ route('websites.create') }}" class="button primary">{{ __('Create website') }}</a>
                    @endif
                </div>

                @if($canDeploy && $successfulBuild && $successfulBuild->revision && $promotionTargets->isNotEmpty())
                    <aside class="border-b border-primary bg-blue-50 px-5 py-4">
                        <div class="flex flex-wrap items-center gap-3"><div class="min-w-0 flex-1"><p class="font-bold text-blue-950">{{ __('Promote tested release') }}</p><p class="mt-1 text-xs text-blue-800">{{ __('Rebuild exact revision :revision with the target environment configuration. Target approval and maintenance policies still apply.', ['revision'=>$successfulBuild->shortRevision()]) }}</p></div><form method="POST" action="{{ route('builds.promote',$successfulBuild) }}" class="flex w-full min-w-0 flex-wrap gap-2 lg:w-auto">@csrf<select name="target_environment_id" required class="input secondary min-w-0 rounded" aria-label="{{ __('Target environment') }}"><option value="">{{ __('Choose target') }}</option>@foreach($promotionTargets as $target)<option value="{{ $target->id }}">{{ $target->name }}</option>@endforeach</select><input name="promotion_note" maxlength="2000" class="input secondary min-w-0 rounded" aria-label="{{ __('Change ticket or release note') }}" placeholder="{{ __('Change ticket or release note') }}"><button type="submit" class="button primary">{{ __('Promote') }}</button></form></div>
                    </aside>
                @endif

                <div class="grid gap-px bg-secondary lg:grid-cols-3">
                    <details class="group bg-primary p-5">
                        <summary class="flex cursor-pointer list-none items-center justify-between font-bold text-primary"><span>{{ __('Environment settings') }}</span><span class="text-secondary group-open:rotate-45">+</span></summary>
                        <form method="POST" action="{{ route('environments.update', $environment) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf @method('PATCH')
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Name') }}</span><input name="name" value="{{ $environment->name }}" class="input secondary rounded" required></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Type') }}</span><select name="type" class="input secondary rounded">@foreach(\App\Models\Environment::TYPES as $type)<option value="{{ $type }}" @selected($environment->type === $type)>{{ ucfirst($type) }}</option>@endforeach</select></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Branch') }}</span><input name="branch" value="{{ $environment->branch }}" class="input secondary rounded" required></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Runtime') }}</span><select name="runtime_type" class="input secondary rounded">@foreach(\App\Models\Environment::RUNTIME_TYPES as $runtime)<option value="{{ $runtime }}" @selected(($environment->runtime_type ?: 'php') === $runtime)>{{ ucfirst($runtime) }}</option>@endforeach</select></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Runtime version') }}</span><input name="runtime_version" value="{{ $environment->runtime_version }}" placeholder="20" class="input secondary rounded"></label>
                            <label class="sm:col-span-2"><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Build command') }}</span><input name="build_command" value="{{ $environment->build_command }}" placeholder="npm run build" class="input secondary rounded font-mono"></label>
                            <label class="sm:col-span-2"><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Start command') }}</span><input name="start_command" value="{{ $environment->start_command }}" placeholder="npm start" class="input secondary rounded font-mono"></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Application port') }}</span><input type="number" min="1" max="65535" name="container_port" value="{{ $environment->container_port }}" placeholder="3000" class="input secondary rounded"></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Dockerfile path') }}</span><input name="dockerfile_path" value="{{ $environment->dockerfile_path }}" placeholder="Dockerfile" class="input secondary rounded font-mono"></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Server') }}</span><select name="server_id" class="input secondary rounded"><option value="">{{ __('None') }}</option>@foreach($servers as $server)<option value="{{ $server->id }}" @selected($environment->server_id === $server->id)>{{ $server->label }}</option>@endforeach</select></label>
                            <label class="sm:col-span-2"><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Website') }}</span><select name="website_id" class="input secondary rounded"><option value="">{{ __('None') }}</option>@foreach($websites as $website)<option value="{{ $website->id }}" @selected($environment->website_id === $website->id)>{{ $website->name }}</option>@endforeach</select></label>
                            @if($featureAccess['hibernation'])<label class="sm:col-span-2"><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Hibernate after inactivity') }}</span><select name="hibernate_after_minutes" class="input secondary rounded"><option value="">{{ __('Never') }}</option>@foreach([5, 15, 30, 60, 120, 1440] as $minutes)<option value="{{ $minutes }}" @selected($environment->hibernate_after_minutes === $minutes)>{{ trans_choice(':count minute|:count minutes', $minutes, ['count' => $minutes]) }}</option>@endforeach</select></label>@endif
                            <input type="hidden" name="is_protected" value="0"><label class="flex items-center gap-2"><input type="checkbox" name="is_protected" value="1" @checked($environment->is_protected)><span class="text-sm text-secondary">{{ __('Protect') }}</span></label>
                            <input type="hidden" name="requires_deployment_approval" value="0"><label class="flex items-center gap-2"><input type="checkbox" name="requires_deployment_approval" value="1" @checked($environment->requires_deployment_approval)><span class="text-sm text-secondary">{{ __('Require approval') }}</span></label>
                            @can('update', $environment)<button type="submit" class="button primary sm:col-span-2">{{ __('Save settings') }}</button>@endcan
                        </form>
                    </details>

                    <details class="group bg-primary p-5">
                        <summary class="flex cursor-pointer list-none items-center justify-between font-bold text-primary"><span>{{ __('Deployment controls') }}</span><span class="text-secondary group-open:rotate-45">+</span></summary>
                        <div class="mt-3 flex flex-wrap gap-2 text-xs"><span class="rounded-full px-2.5 py-1 font-bold {{ $environment->deployment_locked_at ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700' }}">{{ $environment->deployment_locked_at ? __('Locked') : __('Unlocked') }}</span>@if($environment->deployment_window_days)<span class="rounded-full bg-secondary px-2.5 py-1 text-secondary">{{ __('Maintenance window active') }}</span>@endif</div>
                        @can('update', $environment)
                            <form method="POST" action="{{ route('environments.deployment-controls.update', $environment) }}" class="mt-4 space-y-4">@csrf @method('PATCH')
                                <label class="flex items-start gap-3"><input type="hidden" name="deployment_locked" value="0"><input type="checkbox" name="deployment_locked" value="1" class="mt-1" @checked($environment->deployment_locked_at)><span><span class="block text-sm font-bold text-primary">{{ __('Lock deployments') }}</span><span class="text-xs text-secondary">{{ __('Manual, API, scheduled, and webhook deployments will wait.') }}</span></span></label>
                                <input name="deployment_lock_reason" maxlength="500" value="{{ old('deployment_lock_reason', $environment->deployment_lock_reason) }}" class="input secondary rounded" placeholder="{{ __('Reason for the lock (optional)') }}">
                                <div class="border-t border-primary pt-4"><label class="flex items-start gap-3"><input type="hidden" name="deployment_window_enabled" value="0"><input type="checkbox" name="deployment_window_enabled" value="1" class="mt-1" @checked($environment->deployment_window_days)><span><span class="block text-sm font-bold text-primary">{{ __('Restrict deployment times') }}</span><span class="text-xs text-secondary">{{ __('Allow new deployments only within this weekly window.') }}</span></span></label></div>
                                <fieldset><legend class="text-xs font-bold uppercase text-secondary">{{ __('Window days') }}</legend><div class="mt-2 flex flex-wrap gap-3">@foreach([1 => __('Mon'), 2 => __('Tue'), 3 => __('Wed'), 4 => __('Thu'), 5 => __('Fri'), 6 => __('Sat'), 7 => __('Sun')] as $day => $label)<label class="flex items-center gap-1.5 text-sm text-primary"><input type="checkbox" name="deployment_window_days[]" value="{{ $day }}" @checked(in_array($day, old('deployment_window_days', $environment->deployment_window_days ?? [])))>{{ $label }}</label>@endforeach</div></fieldset>
                                <div class="grid gap-3 sm:grid-cols-2"><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Starts') }}</span><input type="time" name="deployment_window_start" value="{{ old('deployment_window_start', $environment->deployment_window_start ? substr($environment->deployment_window_start, 0, 5) : '09:00') }}" class="input secondary mt-1 rounded"></label><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Ends') }}</span><input type="time" name="deployment_window_end" value="{{ old('deployment_window_end', $environment->deployment_window_end ? substr($environment->deployment_window_end, 0, 5) : '17:00') }}" class="input secondary mt-1 rounded"></label></div>
                                <label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Timezone') }}</span><input name="deployment_window_timezone" list="deployment-timezones-{{ $environment->id }}" value="{{ old('deployment_window_timezone', $environment->deployment_window_timezone ?: 'UTC') }}" class="input secondary mt-1 rounded" placeholder="Europe/London"><datalist id="deployment-timezones-{{ $environment->id }}"><option value="UTC"><option value="Europe/London"><option value="Europe/Berlin"><option value="America/New_York"><option value="America/Chicago"><option value="America/Denver"><option value="America/Los_Angeles"><option value="Asia/Singapore"><option value="Asia/Tokyo"><option value="Australia/Sydney"></datalist></label>
                                <div class="border-t border-primary pt-4"><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Release strategy') }}</span><select name="deployment_strategy" class="input secondary mt-1 w-full rounded"><option value="blue_green" @selected($environment->deployment_strategy === 'blue_green')>{{ __('Blue/green atomic switch') }}</option><option value="canary" @selected($environment->deployment_strategy === 'canary')>{{ __('Canary candidate validation') }}</option><option value="rolling" @selected($environment->deployment_strategy === 'rolling')>{{ __('Rolling worker restart') }}</option></select></label><p class="mt-2 text-xs leading-5 text-secondary">{{ __('Blue/green atomically switches release directories. Canary sends loopback HTTP requests to the candidate before the switch. Rolling keeps replicated workers available while restarting them one at a time; web traffic still switches atomically.') }}</p></div>
                                <label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Pause between rolling workers') }}</span><select name="rolling_pause_seconds" class="input secondary mt-1 w-full rounded">@foreach([0,1,2,5,10,30] as $seconds)<option value="{{ $seconds }}" @selected((int) $environment->rolling_pause_seconds === $seconds)>{{ trans_choice(':count second|:count seconds', $seconds, ['count' => $seconds]) }}</option>@endforeach</select></label>
                                <label class="flex items-start gap-3 rounded-xl border border-primary bg-secondary p-3"><input type="hidden" name="automatic_rollback" value="0"><input type="checkbox" name="automatic_rollback" value="1" class="mt-1" @checked($environment->automatic_rollback)><span><span class="block text-sm font-bold text-primary">{{ __('Automatic rollback') }}</span><span class="text-xs leading-5 text-secondary">{{ __('If an activated release fails, immediately switch back to the most recent retained successful release.') }}</span></span></label>
                                <x-forms.errors name="deployment_window_days" /><x-forms.errors name="deployment_window_start" /><x-forms.errors name="deployment_window_end" /><x-forms.errors name="deployment_window_timezone" />
                                <button type="submit" class="button primary">{{ __('Save deployment controls') }}</button>
                            </form>
                        @endcan
                    </details>

                    <details class="group bg-primary p-5">
                        <summary class="flex cursor-pointer list-none items-center justify-between font-bold text-primary"><span>{{ __('Runtime capacity') }}</span><span class="text-secondary group-open:rotate-45">+</span></summary>
                        <p class="mt-3 text-sm text-secondary">{{ __('Pre-provision worker capacity and pause idle environments. Runtime changes are applied from Automation.') }}</p>
                        <div class="mt-4 grid grid-cols-2 gap-3">
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Minimum') }}</span><input value="{{ $environment->minimum_replicas }}" class="input secondary rounded" disabled></label>
                            <label><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Maximum') }}</span><input value="{{ $environment->maximum_replicas }}" class="input secondary rounded" disabled></label>
                            <label class="col-span-2"><span class="mb-1 block text-xs font-bold uppercase text-secondary">{{ __('Idle hibernation') }}</span><input value="{{ $environment->hibernate_after_minutes ? __('After :minutes minutes', ['minutes' => $environment->hibernate_after_minutes]) : __('Never') }}" class="input secondary rounded" disabled></label>
                        </div>
                        @if($featureAccess['scaling'] || $featureAccess['hibernation'])<a href="{{ route('automation.index') }}" class="button secondary mt-4">{{ __('Open automation') }}</a>@else<p class="mt-4 text-sm text-secondary"><a href="{{ route('pricing') }}" class="font-bold text-ternary">{{ __('View plans') }}</a> {{ __('to unlock runtime controls.') }}</p>@endif
                    </details>

                    <details class="group bg-primary p-5">
                        <summary class="flex cursor-pointer list-none items-center justify-between font-bold text-primary"><span>{{ __('Encrypted variables') }} <span class="text-secondary">({{ $environment->variables->count() }})</span></span><span class="text-secondary group-open:rotate-45">+</span></summary>
                        <div class="mt-4 space-y-2">@forelse($environment->variables as $variable)<div class="flex items-center gap-2 rounded-lg border border-primary bg-secondary px-3 py-2"><div class="min-w-0 flex-1"><code class="block truncate text-xs text-primary">{{ $variable->key }}</code><span class="text-[11px] text-secondary">{{ str($variable->scope)->replace('_', ' ')->headline() }} · v{{ $variable->current_version }}@if($variable->rotation_due_at) · <span class="{{ $variable->rotation_due_at->isPast() ? 'text-red-600' : '' }}">{{ __('rotate :date', ['date' => $variable->rotation_due_at->toDateString()]) }}</span>@endif</span></div><span class="text-xs text-secondary">{{ $variable->is_secret ? '••••••••' : __('Encrypted') }}</span>@can('update', $environment)<form method="POST" action="{{ route('environments.variables.destroy', [$environment, $variable]) }}">@csrf @method('DELETE')<button type="submit" class="text-xs font-bold text-secondary">{{ __('Delete') }}</button></form>@endcan</div>@empty<p class="text-sm text-secondary">{{ __('No variables yet.') }}</p>@endforelse</div>
                        @can('update', $environment)<form method="POST" action="{{ route('environments.variables.store', $environment) }}" class="mt-4 space-y-3">@csrf<input name="key" placeholder="APP_SETTING" class="input secondary rounded font-mono" required><textarea name="value" rows="2" placeholder="{{ __('Encrypted value') }}" class="input secondary rounded" required></textarea><div class="grid gap-3 sm:grid-cols-2"><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Scope') }}</span><select name="scope" class="input secondary mt-1 rounded"><option value="runtime">{{ __('Runtime only') }}</option><option value="build">{{ __('Build only') }}</option><option value="all">{{ __('Build and runtime') }}</option></select></label><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Rotate by (optional)') }}</span><input type="date" name="rotation_due_at" min="{{ now()->addDay()->toDateString() }}" class="input secondary mt-1 rounded"></label></div><label class="flex items-center gap-2"><input type="checkbox" name="is_secret" value="1" checked><span class="text-sm text-secondary">{{ __('Mask as secret') }}</span></label><button type="submit" class="button primary">{{ __('Save new version') }}</button></form>@endcan
                    </details>
                </div>

                <div class="grid gap-5 border-t border-primary p-5 lg:grid-cols-2">
                    <details class="group rounded-xl border border-primary bg-secondary p-4">
                        <summary class="flex cursor-pointer list-none items-center justify-between font-bold text-primary"><span>{{ __('Workers and scheduler') }} <span class="text-secondary">({{ $environment->processes->count() }})</span></span><span class="text-secondary group-open:rotate-45">+</span></summary>
                        <div class="mt-3 space-y-2">@foreach($environment->processes as $process)<div class="flex items-center gap-3 rounded-lg border border-primary bg-primary p-3"><div class="min-w-0 flex-1"><p class="font-bold text-primary">{{ $process->name }} <span class="font-normal text-secondary">· {{ $process->type }} · ×{{ $process->replicas }}</span></p><p class="mt-1 text-xs text-secondary">{{ __('Command encrypted · applied on next deployment') }}</p></div>@can('update', $environment)<form method="POST" action="{{ route('environments.processes.destroy', [$environment, $process]) }}">@csrf @method('DELETE')<button type="submit" class="text-xs font-bold text-secondary">{{ __('Delete') }}</button></form>@endcan</div>@endforeach</div>
                        @can('update', $environment)@if($featureAccess['workers'])<form method="POST" action="{{ route('environments.processes.store', $environment) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="name" placeholder="queue" class="input secondary rounded" required><select name="type" class="input secondary rounded"><option value="worker">{{ __('Worker') }}</option><option value="scheduler">{{ __('Scheduler') }}</option></select><input name="command" placeholder="php artisan queue:work" class="input secondary rounded font-mono sm:col-span-2" required><input type="number" name="replicas" min="1" max="20" value="1" class="input secondary rounded"><select name="restart_policy" class="input secondary rounded"><option value="always">{{ __('Always restart') }}</option><option value="on-failure">{{ __('Restart on failure') }}</option><option value="no">{{ __('Never restart') }}</option></select><input type="number" name="restart_delay_seconds" min="0" max="300" value="5" class="input secondary rounded" aria-label="{{ __('Restart delay seconds') }}"><input type="hidden" name="is_enabled" value="1"><button type="submit" class="button primary">{{ __('Save process') }}</button></form>@else<p class="mt-4 text-sm text-secondary">{{ __('Available on Starter and higher.') }} <a href="{{ route('pricing') }}" class="font-bold text-ternary">{{ __('View plans') }}</a></p>@endif @endcan
                    </details>

                    <details class="group rounded-xl border border-primary bg-secondary p-4">
                        <summary class="flex cursor-pointer list-none items-center justify-between font-bold text-primary"><span>{{ __('Attached resources') }} <span class="text-secondary">({{ $environment->resources->count() }})</span></span><span class="text-secondary group-open:rotate-45">+</span></summary>
                        <div class="mt-3 space-y-2">@foreach($environment->resources as $resource)<div class="flex items-center gap-3 rounded-lg border border-primary bg-primary p-3"><div class="min-w-0 flex-1"><p class="font-bold text-primary">{{ $resource->name }}</p><p class="text-xs text-secondary">{{ str($resource->type)->replace('_', ' ')->title() }} · {{ $resource->is_managed ? __('Managed') : __('External') }} · {{ ucfirst($resource->status) }}</p></div>@can('update', $environment)<form method="POST" action="{{ route('environments.resources.destroy', [$environment, $resource]) }}">@csrf @method('DELETE')<button type="submit" class="text-xs font-bold text-secondary">{{ __('Detach') }}</button></form>@endcan</div>@endforeach</div>
                        @can('update', $environment)@if($featureAccess['resources'])<form method="POST" action="{{ route('environments.resources.store', $environment) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="name" placeholder="primary-database" class="input secondary rounded" required><select name="type" class="input secondary rounded"><option value="mysql">MySQL</option><option value="postgresql">PostgreSQL</option><option value="redis">Redis</option><option value="valkey">Valkey</option><option value="object_storage">{{ __('Object storage') }}</option></select><label class="flex items-center gap-2 sm:col-span-2"><input type="hidden" name="is_managed" value="0"><input type="checkbox" name="is_managed" value="1"><span class="text-sm text-secondary">{{ __('Manage on attached server') }}</span></label><textarea name="variables" rows="3" placeholder="REDIS_HOST=cache.example.com&#10;REDIS_PASSWORD=…" class="input secondary rounded font-mono sm:col-span-2"></textarea><button type="submit" class="button primary sm:col-span-2">{{ __('Attach resource') }}</button></form>@else<p class="mt-4 text-sm text-secondary">{{ __('Available on Pro and higher.') }} <a href="{{ route('pricing') }}" class="font-bold text-ternary">{{ __('View plans') }}</a></p>@endif @endcan
                    </details>
                </div>
            </section>
        @endforeach
    </div>

    <div class="mt-5 grid gap-5 xl:grid-cols-2">
        @if($canDeploy)
            <details class="rounded-2xl border border-primary bg-primary p-5"><summary class="cursor-pointer font-black text-primary">{{ __('Add environment') }}</summary><form method="POST" action="{{ route('environments.store', $project) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf<input name="name" placeholder="Staging" class="input secondary rounded" required><select name="type" class="input secondary rounded">@foreach(\App\Models\Environment::TYPES as $type)<option value="{{ $type }}">{{ ucfirst($type) }}</option>@endforeach</select><input name="branch" placeholder="develop" class="input secondary rounded sm:col-span-2" required><input type="hidden" name="is_protected" value="0"><input type="hidden" name="requires_deployment_approval" value="0"><button type="submit" class="button primary sm:col-span-2">{{ __('Create environment') }}</button></form></details>
        @endif

        <details class="rounded-2xl border border-primary bg-primary p-5" @if($project->previews->isNotEmpty()) open @endif>
            <summary class="flex cursor-pointer list-none items-center justify-between font-black text-primary"><span>{{ __('Preview environments') }} <span class="text-secondary">({{ $project->previews->count() }})</span></span><span class="rounded-full px-2.5 py-1 text-xs {{ $project->preview_enabled ? 'bg-green-100 text-green-700' : 'bg-secondary text-secondary' }}">{{ $project->preview_enabled ? __('Enabled') : __('Disabled') }}</span></summary>
            @if($canManage && $featureAccess['previews'])
                <form method="POST" action="{{ route('projects.previews.update', $project) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf @method('PATCH')<label class="flex items-center gap-2"><input type="hidden" name="preview_enabled" value="0"><input type="checkbox" name="preview_enabled" value="1" @checked($project->preview_enabled)><span class="text-sm text-primary">{{ __('Enable previews') }}</span></label><input type="number" name="preview_ttl_hours" min="1" max="720" value="{{ old('preview_ttl_hours', $project->preview_ttl_hours ?: 72) }}" class="input secondary rounded" aria-label="{{ __('Lifetime in hours') }}"><input name="preview_domain" value="{{ old('preview_domain', $project->preview_domain) }}" placeholder="previews.example.com" class="input secondary rounded sm:col-span-2"><button type="submit" class="button primary sm:col-span-2">{{ __('Save previews') }}</button></form>
            @elseif($canManage)
                <p class="mt-4 text-sm text-secondary">{{ __('Available on Pro and higher.') }} <a href="{{ route('pricing') }}" class="font-bold text-ternary">{{ __('View plans') }}</a></p>
            @endif
            <div class="mt-4 space-y-2">@forelse($project->previews->sortByDesc('last_activity_at') as $preview)<article class="rounded-xl border border-primary bg-secondary p-3"><div class="flex items-center gap-3"><div class="min-w-0 flex-1"><p class="font-bold text-primary">#{{ $preview->pull_request_number }} · {{ $preview->title ?: $preview->source_branch }}</p><p class="truncate font-mono text-xs text-secondary">{{ $preview->source_branch }} · {{ substr($preview->revision, 0, 12) }}</p></div><span class="text-xs font-bold text-secondary">{{ ucfirst($preview->status) }}</span></div>@if($preview->url)<a href="https://{{ $preview->url }}" target="_blank" rel="noopener noreferrer" class="mt-2 block truncate text-sm font-medium text-ternary">{{ $preview->url }}</a>@endif</article>@empty<p class="text-sm text-secondary">{{ __('No pull-request previews yet.') }}</p>@endforelse</div>
        </details>
    </div>
</x-layouts.app>
