@extends('monitor::layouts.app')
@section('title', $alertRule ? 'Edit alert rule' : 'Create alert rule')
@section('breadcrumb', 'Alert rules')
@section('content')
<div class="mx-auto max-w-3xl space-y-6">
    <a href="{{ $alertRule ? route('monitor.alerts.show', $alertRule) : route('monitor.alerts.index') }}" class="text-xs font-bold text-primary hover:underline dark:text-primary">← Alert rules</a>
    <x-monitor::ui.page-header :title="$alertRule ? 'Edit alert rule' : 'Create alert rule'" description="A rule monitors one environment and optionally one exact service label." />
    @if($environmentOptions === [])
        <p class="ui-card shadow-none p-6">Create an application and environment before adding a rule. <a href="{{ route('monitor.applications.index') }}" class="font-semibold text-primary dark:text-primary">Manage applications →</a></p>
    @else
    <form method="POST" action="{{ $alertRule ? route('monitor.alerts.update', $alertRule) : route('monitor.alerts.store') }}" class="ui-panel space-y-5 p-6">
        @csrf
        @if($alertRule) @method('PATCH') <input type="hidden" name="version" value="{{ $alertRule->state_version }}"> @endif
        <x-monitor::ui.input name="name" label="Rule name (no secrets)" :value="$alertRule?->name" maxlength="120" required />
        <x-monitor::ui.select name="environment_id" label="Environment" :value="$alertRule?->environment_id" :options="$alertRule ? [$alertRule->environment_id => $environmentOptions[$alertRule->environment_id]] : $environmentOptions" required />
        @php($metricValue = old('metric', $alertRule?->metric->value ?? ($selectedSeries ? 'numeric_metric' : 'request_error_rate')))
        <x-monitor::ui.select name="metric" label="Metric" :value="$metricValue" :options="$metricOptions" required />
        <x-monitor::ui.select name="metric_series_id" label="Metric series (required for numeric or anomaly alerts)" :value="old('metric_series_id', $alertRule?->metric_series_id ?? $selectedSeries?->id)" :options="$metricSeriesOptions" placeholder="Choose a resource-specific series" />
        <x-monitor::ui.select name="service_level_objective_id" label="SLO (required for burn-rate alerts)" :value="old('service_level_objective_id', $alertRule?->service_level_objective_id)" :options="$objectiveOptions" placeholder="Choose a service level objective" />
        <div class="grid gap-5 sm:grid-cols-3"><x-monitor::ui.select name="aggregation" label="Numeric calculation" :value="old('aggregation', $alertRule?->aggregation ?? 'last')" :options="['last' => 'Latest value', 'mean' => 'Mean', 'min' => 'Minimum', 'max' => 'Maximum', 'rate' => 'Counter rate']" /><x-monitor::ui.select name="comparison" label="Comparison" :value="old('comparison', $alertRule?->comparison ?? 'gte')" :options="['gte' => 'At or above', 'lte' => 'At or below']" /><x-monitor::ui.input name="freshness_seconds" label="Freshness (seconds)" type="number" min="30" max="3600" :value="old('freshness_seconds', $alertRule?->freshness_seconds ?? 120)" /></div>
        <x-monitor::ui.input name="service" label="Exact service label (optional; blank means all services)" :value="$alertRule?->service" maxlength="100" />
        <x-monitor::ui.input name="match_text" label="Log / event pattern (required for pattern alerts)" :value="$alertRule?->match_text" maxlength="120" placeholder="payment provider timeout" />
        <div class="grid gap-5 sm:grid-cols-2"><x-monitor::ui.input name="threshold" label="Threshold" type="number" step="0.001" min="0" :value="$alertRule?->threshold ?? 5" required /><x-monitor::ui.select name="window_minutes" label="Rolling window" :value="$alertRule?->window_minutes ?? 5" :options="$windowOptions" required /></div>
        <x-monitor::ui.input name="minimum_samples" label="Minimum eligible samples per window" type="number" min="1" max="1000000" :value="$alertRule?->minimum_samples ?? 20" required />
        @if($metricValue === 'telemetry_volume')<p class="text-xs leading-5 text-muted dark:text-subtle">Telemetry volume breaches when matching events in the rolling window are at or below the threshold. This is useful for detecting a stopped worker, broken instrumentation or a quiet ingestion path. Minimum samples is ignored for this guardrail.</p>@elseif($metricValue === 'telemetry_freshness')<p class="text-xs leading-5 text-muted dark:text-subtle">Telemetry freshness breaches when the latest matching event is at least the threshold number of seconds old. No event since monitoring began is treated as increasingly stale. Minimum samples is ignored for this guardrail.</p>@elseif($metricValue === 'slo_burn_rate')<p class="text-xs leading-5 text-muted dark:text-subtle">SLO burn-rate alerts use the selected objective's rolling error budget. A value of 1× consumes budget at the planned rate; higher values indicate faster-than-planned bad-request consumption. Choose an escalation policy when a sustained burn should wake another team.</p>@elseif($metricValue === 'metric_anomaly')<p class="text-xs leading-5 text-muted dark:text-subtle">Anomaly alerts compare the latest gauge or delta-sum value with a robust rolling baseline from the same series. Threshold is a deviation score from 3 to 20; 3.5 is a useful starting point. The rule needs enough valid samples to establish a baseline and opens an incident only when the latest value is unusual.</p>@elseif($metricValue === 'log_pattern_count')<p class="text-xs leading-5 text-muted dark:text-subtle">Pattern alerts count matching text across received telemetry names, routes, services, trace IDs and common log payload fields. Add an exact service filter to narrow the signal. The threshold is the number of matches in the rolling window; minimum samples is ignored because zero matches is a valid healthy observation.</p>@else<p class="text-xs leading-5 text-muted dark:text-subtle">For a resource / custom numeric metric, choose a series, calculation and comparison above. Counter rate is reset-aware. Error rate uses request samples; duration uses requests with a non-negative duration. Count rules use all matching events. No samples, stale values, gaps or resets mean unknown and never automatic recovery. Fields that do not apply to the selected metric are ignored.</p>@endif
        <div class="grid gap-5 sm:grid-cols-2"><x-monitor::ui.input name="trigger_checks" label="Consecutive breaching checks to open" type="number" min="1" max="10" :value="$alertRule?->trigger_checks ?? 2" required /><x-monitor::ui.input name="recovery_checks" label="Consecutive below-threshold checks to recover" type="number" min="1" max="10" :value="$alertRule?->recovery_checks ?? 2" required /></div>
        <x-monitor::ui.select name="enabled" label="Evaluation" :value="$alertRule ? (int) $alertRule->enabled : 1" :options="[1 => 'Enabled', 0 => 'Paused']" required />
        <div class="space-y-2 rounded-control bg-surface-muted p-4 text-xs leading-5 text-muted dark:bg-surface-muted dark:text-muted">
            <p>Checks run every minute using source timestamps, with a one-minute delay for ingestion. Rolling windows overlap: consecutive checks are not independent samples. Late events can affect later checks while still inside their window; completed checks are not replayed.</p>
            <p>HTTP 5xx or error/critical severity flags a failed request. These are collected request records, including instrumented internal/outbound requests—not a customer-availability SLO. Sampling or incomplete instrumentation can bias results.</p>
            @if($alertRule)<p>Changing monitoring conditions closes any active incident as “rule changed” and starts a new warm-up. Pausing retains active incidents; resuming starts a full new observation window.</p>@endif
        </div>
        <x-monitor::ui.button>{{ $alertRule ? 'Save rule' : 'Create rule' }}</x-monitor::ui.button>
    </form>
    @endif
</div>
@endsection
