<?php

return [
    'laravel' => [
        'name' => 'Laravel',
        'description' => 'Laravel web application with queue and scheduler workers.',
        'runtime_type' => 'php',
        'build_command' => null,
        'start_command' => null,
        'container_port' => null,
        'dockerfile_path' => null,
        'processes' => [
            ['name' => 'queue', 'type' => 'worker', 'command' => 'php artisan queue:work --sleep=3 --tries=3 --timeout=90'],
            ['name' => 'scheduler', 'type' => 'scheduler', 'command' => 'php artisan schedule:work'],
        ],
    ],
    'laravel-inertia' => [
        'name' => 'Laravel + Inertia',
        'description' => 'Full-stack Laravel and Inertia application.',
        'runtime_type' => 'php',
        'build_command' => 'npm run build',
        'start_command' => null,
        'container_port' => null,
        'dockerfile_path' => null,
        'processes' => [
            ['name' => 'queue', 'type' => 'worker', 'command' => 'php artisan queue:work --sleep=3 --tries=3 --timeout=90'],
            ['name' => 'scheduler', 'type' => 'scheduler', 'command' => 'php artisan schedule:work'],
        ],
    ],
    'laravel-api' => [
        'name' => 'Laravel API',
        'description' => 'Laravel API with queues and scheduled jobs.',
        'runtime_type' => 'php',
        'build_command' => null,
        'start_command' => null,
        'container_port' => null,
        'dockerfile_path' => null,
        'processes' => [
            ['name' => 'queue', 'type' => 'worker', 'command' => 'php artisan queue:work --sleep=3 --tries=3 --timeout=90'],
            ['name' => 'scheduler', 'type' => 'scheduler', 'command' => 'php artisan schedule:work'],
        ],
    ],
    'wordpress' => [
        'name' => 'WordPress',
        'description' => 'PHP application preset for a Composer-managed WordPress repository.',
        'runtime_type' => 'php',
        'build_command' => null,
        'start_command' => null,
        'container_port' => null,
        'dockerfile_path' => null,
        'processes' => [],
    ],
    'statamic' => [
        'name' => 'Statamic',
        'description' => 'Statamic site with queue and scheduler processes.',
        'runtime_type' => 'php',
        'build_command' => 'npm run build',
        'start_command' => null,
        'container_port' => null,
        'dockerfile_path' => null,
        'processes' => [
            ['name' => 'queue', 'type' => 'worker', 'command' => 'php artisan queue:work --sleep=3 --tries=3'],
            ['name' => 'scheduler', 'type' => 'scheduler', 'command' => 'php artisan schedule:work'],
        ],
    ],
    'node' => [
        'name' => 'Node.js',
        'description' => 'Node service installed with npm and served behind Caddy.',
        'runtime_type' => 'node',
        'build_command' => 'npm run build --if-present',
        'start_command' => 'npm start',
        'container_port' => 3000,
        'dockerfile_path' => null,
        'processes' => [],
    ],
    'nextjs' => [
        'name' => 'Next.js',
        'description' => 'Production Next.js server with an optimized build.',
        'runtime_type' => 'node',
        'build_command' => 'npm run build',
        'start_command' => 'npm start',
        'container_port' => 3000,
        'dockerfile_path' => null,
        'processes' => [],
    ],
    'nuxt' => [
        'name' => 'Nuxt',
        'description' => 'Production Nuxt server using the generated Nitro output.',
        'runtime_type' => 'node',
        'build_command' => 'npm run build',
        'start_command' => 'node .output/server/index.mjs',
        'container_port' => 3000,
        'dockerfile_path' => null,
        'processes' => [],
    ],
    'django' => [
        'name' => 'Django',
        'description' => 'Python application installed in an isolated virtual environment.',
        'runtime_type' => 'python',
        'build_command' => 'python manage.py collectstatic --noinput',
        'start_command' => '.venv/bin/gunicorn config.wsgi:application --bind 127.0.0.1:${PORT}',
        'container_port' => 8000,
        'dockerfile_path' => null,
        'processes' => [],
    ],
    'docker' => [
        'name' => 'Dockerfile',
        'description' => 'Build a repository Dockerfile and switch traffic after it becomes healthy.',
        'runtime_type' => 'docker',
        'build_command' => null,
        'start_command' => null,
        'container_port' => 8080,
        'dockerfile_path' => 'Dockerfile',
        'processes' => [],
    ],
    'custom' => [
        'name' => 'Custom PHP',
        'description' => 'Empty PHP runtime configuration.',
        'runtime_type' => 'php',
        'build_command' => null,
        'start_command' => null,
        'container_port' => null,
        'dockerfile_path' => null,
        'processes' => [],
    ],
];
