<?php

return [
    'enforce_limits' => (bool) env('BILLING_ENFORCE_LIMITS', true),
    'enforce_entitlements' => (bool) env('BILLING_ENFORCE_ENTITLEMENTS', true),
    'trial_days' => (int) env('BILLING_TRIAL_DAYS', 14),

    'plans' => [
        'free' => [
            'name' => 'Free', 'price' => 0, 'yearly_price' => 0,
            'description' => 'Start deploying on your own infrastructure.',
            'features' => ['1 server', '1 website', 'Git deployments', 'Atomic releases'],
            'entitlements' => ['deployments', 'releases', 'approvals'],
            'limits' => ['servers' => 1, 'websites' => 1, 'members' => 1], 'included_seats' => 1,
        ],
        'starter' => [
            'name' => 'Starter', 'price' => 9, 'yearly_price' => 90,
            'price_id' => env('STRIPE_STARTER_PRICE_ID'),
            'monthly_price_id' => env('STRIPE_STARTER_MONTHLY_PRICE_ID', env('STRIPE_STARTER_PRICE_ID')),
            'yearly_price_id' => env('STRIPE_STARTER_YEARLY_PRICE_ID'),
            'description' => 'For personal projects and small applications.',
            'features' => ['2 servers', '5 websites', 'Health monitoring', 'Workers and idle hibernation'],
            'entitlements' => ['deployments', 'releases', 'approvals', 'monitoring', 'workers', 'hibernation'],
            'limits' => ['servers' => 2, 'websites' => 5, 'members' => 1], 'included_seats' => 1,
        ],
        'pro' => [
            'name' => 'Pro', 'price' => 19, 'yearly_price' => 190,
            'price_id' => env('STRIPE_PRO_PRICE_ID'),
            'monthly_price_id' => env('STRIPE_PRO_MONTHLY_PRICE_ID', env('STRIPE_PRO_PRICE_ID')),
            'yearly_price_id' => env('STRIPE_PRO_YEARLY_PRICE_ID'),
            'description' => 'For developers running production workloads.',
            'features' => ['5 servers', 'Unlimited websites', 'Preview environments', 'Managed backups and resources'],
            'entitlements' => ['deployments', 'releases', 'approvals', 'monitoring', 'workers', 'hibernation', 'previews', 'backups', 'resources', 'status_pages', 'scheduled_deployments', 'cost_controls'],
            'limits' => ['servers' => 5, 'websites' => null, 'members' => 1], 'included_seats' => 1,
        ],
        'team' => [
            'name' => 'Team', 'price' => 49, 'yearly_price' => 490,
            'price_id' => env('STRIPE_TEAM_PRICE_ID'),
            'monthly_price_id' => env('STRIPE_TEAM_MONTHLY_PRICE_ID', env('STRIPE_TEAM_PRICE_ID')),
            'yearly_price_id' => env('STRIPE_TEAM_YEARLY_PRICE_ID'),
            'monthly_seat_price_id' => env('STRIPE_TEAM_MONTHLY_SEAT_PRICE_ID'),
            'yearly_seat_price_id' => env('STRIPE_TEAM_YEARLY_SEAT_PRICE_ID'),
            'description' => 'Collaboration and operations for growing teams.',
            'features' => ['20 servers', '5 seats included', 'Alert integrations', 'Full audit history'],
            'entitlements' => ['deployments', 'releases', 'approvals', 'monitoring', 'workers', 'hibernation', 'previews', 'backups', 'resources', 'status_pages', 'scheduled_deployments', 'cost_controls', 'teams', 'alerts', 'audit'],
            'limits' => ['servers' => 20, 'websites' => null, 'members' => null], 'included_seats' => 5,
        ],
        'business' => [
            'name' => 'Business', 'price' => 99, 'yearly_price' => 990,
            'price_id' => env('STRIPE_BUSINESS_PRICE_ID'),
            'monthly_price_id' => env('STRIPE_BUSINESS_MONTHLY_PRICE_ID', env('STRIPE_BUSINESS_PRICE_ID')),
            'yearly_price_id' => env('STRIPE_BUSINESS_YEARLY_PRICE_ID'),
            'monthly_seat_price_id' => env('STRIPE_BUSINESS_MONTHLY_SEAT_PRICE_ID'),
            'yearly_seat_price_id' => env('STRIPE_BUSINESS_YEARLY_SEAT_PRICE_ID'),
            'description' => 'Automation and scale controls for serious operations.',
            'features' => ['50 servers', '20 seats included', 'API and CLI access', 'Scaling automation'],
            'entitlements' => ['deployments', 'releases', 'approvals', 'monitoring', 'workers', 'hibernation', 'previews', 'backups', 'resources', 'status_pages', 'scheduled_deployments', 'cost_controls', 'teams', 'alerts', 'audit', 'api', 'scaling', 'scheduled_scaling', 'high_availability', 'sso'],
            'limits' => ['servers' => 50, 'websites' => null, 'members' => null], 'included_seats' => 20,
        ],
        'unlimited' => [
            'name' => 'Unlimited', 'price' => 199, 'yearly_price' => 1990,
            'price_id' => env('STRIPE_UNLIMITED_PRICE_ID'),
            'monthly_price_id' => env('STRIPE_UNLIMITED_MONTHLY_PRICE_ID', env('STRIPE_UNLIMITED_PRICE_ID')),
            'yearly_price_id' => env('STRIPE_UNLIMITED_YEARLY_PRICE_ID'),
            'description' => 'No fixed limits for high-scale operations.',
            'features' => ['Unlimited servers and websites', 'Unlimited seats', 'Every BuildPusher feature', 'Priority support'],
            'entitlements' => ['*'],
            'limits' => ['servers' => null, 'websites' => null, 'members' => null], 'included_seats' => null,
        ],
    ],
];
