<?php

declare(strict_types=1);

// What's new, newest first. Each entry: date, title, and the changes people will notice.
return [
    ['date' => '2026-10-01', 'title' => 'Platform: webhooks, SCIM, agency tools, costs by project and your own templates', 'changes' => [
        'Infrastructure as code: a resources API for projects, servers, websites and monitors, and a Terraform provider built on it.',
        'Analytics on its own: choose only the services a new project needs; with just Analytics (or Monitoring) the setup guide skips servers and deploys.',
        'Ask: an assistant that answers questions about your deploys, errors, checks, incidents, Analytics and servers with the numbers behind them, in the app or from Claude, Cursor and other AI tools over MCP.',
        'For agencies: white-label status pages and shared reports with your name, logo and colour; clients with a monthly report in your name; and costs by client with your markup as a CSV.',
        'SCIM provisioning: Okta and Microsoft Entra ID add people when they’re assigned the app and remove them when they leave, alongside single sign-on.',
        'Your own project templates: save a project’s services, environments, release settings, uptime checks and goals, and start new projects from it.',
        'One cost view: Billing → Costs by project shows each project’s share of your plans beside the servers it runs on, with last month’s cloud invoices.',
        'The app in your language: Spanish, French, German and Portuguese as well as English, following your browser or the language you pick in your profile.',
        'Webhooks: send deploys, incidents, servers, websites, backups, security findings, members and plan changes to your own address as signed JSON, with retries, a delivery log and Send again.',
    ]],
    ['date' => '2026-10-01', 'title' => 'Infrastructure: servers that fit', 'changes' => [
        'More DNS providers: domains’ records are managed at DigitalOcean DNS, Hetzner DNS and AWS Route 53 as well as Cloudflare.',
        'Database tools: the week’s slowest queries on each website’s database, and tuning suggestions from the server’s own counters.',
        'Anonymised staging data: copy a database to staging or previews with emails, names, phone numbers, addresses and IP addresses masked.',
        'Backups to two places: send each scheduled backup to a second destination too, for a 3-2-1 setup.',
        'Monthly restore drills: the latest backup is restored into a scratch area and checked each month, and owners hear if it fails.',
        'Snapshots before risky changes: a provider snapshot is taken before updates, security fixes and runtime switches, keeping the three newest.',
        'Self-healing websites: when a health check fails, stopped services are restarted automatically, and the incident shows what was done.',
        'Disk clean-up: see what old releases, logs, caches, Docker images and temporary files take on a server, and clear them safely in one click.',
        'AWS EC2, Google Compute Engine, Microsoft Azure and OVHcloud: create servers in your own account on the big clouds too, with EC2 costs from AWS Cost Explorer and snapshots before risky changes on EC2, Compute Engine and Azure.',
        'Scaleway and UpCloud: create servers in your Scaleway or UpCloud account, with prices in euros on the Costs page.',
        'Move from Forge or Ploi: read your servers and sites with an API token and recreate each site here with its environment file, cron jobs and daemons.',
        'Actual cloud bills: Costs shows what DigitalOcean, Vultr, Linode and Lightsail really charged last month and so far this month, beside the estimate from list prices.',
        'Read replicas: another MySQL or PostgreSQL server in your account copies a database server continuously over the private network (or TLS), with its lag checked every five minutes and one-click promotion.',
        'Right-sizing: Costs suggests a smaller server when yours is mostly idle (with the saving) and a bigger one when it runs hot, from two weeks of CPU and memory.',
    ]],
    ['date' => '2026-10-01', 'title' => 'Deploy: monorepos, GitHub Actions and safer releases', 'changes' => [
        'Build servers: build on another of your servers and pass the built release to the websites through your own storage bucket, so builds don’t slow the websites down.',
        'Release analysis: after each deploy, errors, request time and the conversion rate are compared with before it, and a release that’s worse past your limits is rolled back automatically.',
        'Docker Compose deploys: ship an app as a Compose stack to your own server, with the web service behind Caddy and volumes kept between deploys.',
        'Preview database branches: previews can start from a quick sample of each table, or the schema only, instead of a full copy.',
        'Smarter autoscaling: replicas follow your queue’s backlog as well as CPU, and hibernating environments wake within seconds of their first request.',
        'Secrets from password managers: sync environment variables from Doppler, 1Password Connect or AWS Secrets Manager instead of pasting them in.',
        'Branch environments: preview any branch, not only pull requests, with a closing date you choose.',
        'Deploy pipelines: deploy several repositories in order, each after the one before goes live, stopping if one fails.',
        'Approve deploys from Slack: approval requests arrive with Approve and Reject buttons that take you straight to a one-tap confirmation.',
        'Release notes written from each deploy’s commits, on the deploy page, in Slack and Discord deploy notifications, and on an optional public page.',
        'Migration safety checks: deploys stop before migrations that drop, truncate or rename, until someone else approves them.',
        'Clone an environment: make staging from production’s settings, workers, recipes and variables in one step, choosing whether secrets come too.',
        'Monorepos: deploy one app from a subfolder, and only when a push changes its files.',
        'The GitHub Action now comments each deploy’s result on the pull request and reports it in the job summary and outputs.',
    ]],
    ['date' => '2026-10-01', 'title' => 'Monitoring: quieter, clearer alerts', 'changes' => [
        'Push notifications for on-call: turn them on for your phone or computer, add a Push destination for yourself or whoever is on call, and alerts arrive even with BuildPusher closed.',
        'Multi-step checks: script a login or checkout as a series of requests, with cookies, redirects and values carried between steps, and get told which step broke.',
        'Status pages: group components under headings, a public uptime report for every month, and an optional monthly email of it to subscribers.',
        'Send a server’s logs to Monitoring: system warnings and errors, and its websites’ Laravel errors with stack traces, searchable beside traces and ready for log alerts.',
        'Create a ticket for any issue in GitHub Issues, Linear or Jira, with the error’s details and a link back; closing the ticket resolves the issue.',
        'A Laravel package: composer require buildpusher/laravel, set one key, and every request arrives with a timeline of its queries, mail and notifications, plus exceptions with the number of people affected, slow and N+1 queries, jobs, scheduled tasks, commands and logs.',
        'Browser error tracking: a script tag catches JavaScript errors and unhandled promise rejections in visitors’ browsers and groups them into issues beside your server errors.',
        'Follow the status of the services you depend on, such as GitHub, Cloudflare and DigitalOcean, beside your own monitors.',
        'Post-mortems start as a draft written from the incident: its length, what the check saw, who responded, your notes, and the deploys just before it as leads.',
        'An alert noise report ranks the rules and monitors that fired most, shows which flap or get ignored, and suggests how to tune them.',
    ]],
    ['date' => '2026-10-01', 'title' => 'Analytics: lighter, and more in your control', 'changes' => [
        'The tracker is under half its old size (about 2 KB compressed); link, download and page speed tracking load only when you turn them on.',
        'Leave out visits from your office or other addresses, count clicks on any element by adding a CSS class, and track single-page apps that route with #/paths.',
        'Give a client view-only access to one site with their own link, without adding them to your account.',
        'Send pageviews and events from your server through the API and SDKs, for things that happen outside the browser.',
        'New in Explore: first- and last-touch attribution for goals and revenue, click maps, and form analytics that show which field people give up on.',
        'A Looker Studio connector, and an API of daily rows by page, source, channel, campaign, country, device and more, for spreadsheets and dashboards.',
        'Import ad spend from Google Ads, Meta or any ad platform’s CSV, and Campaigns shows each campaign’s cost, cost per conversion and return on ad spend.',
        'Scheduled CSV exports of any saved view, by email every week or month, and alerts when yesterday’s visitors or conversions were far from normal for that day of the week.',
        'A/B tests: call buildpusher.variant() on your page, pick the goal that decides it, and Explore shows each variant’s conversion rate, lift and whether the difference is statistically significant.',
        'Group pages (such as everything under /blog), see what people search for on your site and which searches find nothing, and keep referrer spam and bots out, with a count of what was left out.',
    ]],
    ['date' => '2026-09-30', 'title' => 'Security, a fifth service', 'changes' => [
        'A security score for each project, with every finding explained and a fix beside it.',
        'Vulnerable Composer and npm packages, leaked keys in code and logs, and weak domains (certificates, TLS, headers, SPF, DMARC, and DNS records that could be taken over).',
        'A deploy gate that stops releases with known critical vulnerabilities before they go live.',
        'Server hardening with one-click fixes, weekly security update windows, and SSH access with each person’s own keys.',
        'Attackers blocked automatically from access logs, plus Cloudflare security level, bot fight mode and under attack mode.',
        'Access reviews and a compliance evidence pack for SOC 2 and ISO 27001.',
    ]],
    ['date' => '2026-09-30', 'title' => 'Analytics: explore, compare and share', 'changes' => [
        'Pick any dates and compare with the period before or the same period last year. Save filter sets as segments.',
        'New in reports: channels, regions and cities, screen sizes, browser and system versions, UTM term and content, and time on page and scroll depth for each page.',
        'A new Explore page: what changed most, where visitors go before and after a page, custom property breakdowns, items sold, and weekly retention.',
        'Email or Slack a weekly or monthly report, and get an alert when a lot of people are on the site at once.',
        'Embed a shared report on another site, serve the tracker from your own domain so blockers don’t stop it, and add notes to the chart.',
        'Import your history from Google Analytics 4, and export raw events each night to your own storage, ready for BigQuery.',
    ]],
    ['date' => '2026-09-30', 'title' => 'Servers and environments do more', 'changes' => [
        'Add cron jobs, background processes, firewall rules, and Meilisearch, Typesense or Redis to a server in a click. Set up Reverb for a website in one step.',
        'Edit a website’s web server settings (with an automatic undo if they’re invalid), browse its files, and tail or search its logs.',
        'Put a domain behind Cloudflare’s CDN, block countries or addresses, and rate-limit it. The cache is cleared after each deploy.',
        'Storage buckets for your apps, previews that start with a copy of another website’s database, and trusted private networking between your servers.',
        'Autoscale an environment on CPU, put it into maintenance mode with a secret link for your team, and see which regions it runs in.',
        'Traces now show the deploy that served them. Go past a plan’s allowance and pay only for what you use, with an optional spend cap.',
    ]],
    ['date' => '2026-09-29', 'title' => 'Quicker to get around', 'changes' => [
        'Creating a server, your notifications and many more forms now open in place, without leaving the page.',
        'A footer with the platform’s status and quick links on every page, and breadcrumbs that step back through where you are.',
        'Billing shows each service on its own tab.',
    ]],
    ['date' => '2026-09-29', 'title' => 'Analytics: today, countries, page speed and revenue', 'changes' => [
        'A Today view with visits per hour, and a “Right now” panel that updates itself.',
        'See which countries visitors come from, how long visits last, and which Google searches brought them (connect Search Console).',
        'Count outbound links, file downloads, missing pages and page speed (Core Web Vitals) by adding one attribute to the snippet.',
        'Add revenue to your events to see what each goal and campaign earns.',
        'Share a site’s report with a link, with or without a password, and read reports through the API and SDKs.',
        'Reports stay fast on busy sites, and ?bp_ignore=1 leaves your own visits out.',
    ]],
    ['date' => '2026-09-29', 'title' => 'Deploy safely, page the right person, and grow', 'changes' => [
        'Deploy any branch, tag or commit, book a deploy for later, freeze an environment for the holidays, and let a jump in errors roll a deploy back.',
        'On-call schedules, text and phone alerts, incident post-mortems for your status page, and status updates in Slack or a webhook.',
        'Funnels, campaign links and results, and releases marked on your analytics chart.',
        'Linode and AWS Lightsail servers, PostgreSQL with point-in-time recovery, per-site PHP versions and budget alerts.',
        'Limit members to some projects, protect production, stream your audit log, require a second person for secrets, and SAML single sign-on.',
        'Pay yearly with two months free, and see what’s new right here.',
    ]],
    ['date' => '2026-09-29', 'title' => 'Set up faster, and follow things live', 'changes' => [
        'The setup guide now shows one step at a time, and you can connect a provider, add a website or add an Analytics site without leaving it.',
        'Explore a sample project with a month of made-up visits and a day of made-up errors before connecting anything real.',
        'Deploys stream their stages and log live, and incidents, monitors, servers, websites and backups update without a reload.',
        'A welcome email, and one reminder if a project’s setup stalls. Turn them off from any of them.',
    ]],
    ['date' => '2026-09-28', 'title' => 'Single sign-on, saved views and a help centre', 'changes' => [
        'Account → Security: require two-factor authentication, limit email domains and IP ranges, sign people out when idle, and sign in with your identity provider (OpenID Connect).',
        'Save the filters on the audit log, notifications and Monitoring’s events, issues and metrics, and export the audit log and notifications as CSV.',
        'Compare any two deploys: outcome, timing, the code changes and every setting that changed.',
        'Short guides for every part of BuildPusher in the new help centre, and a way to send us feedback from the app.',
        'Quick actions such as a new project, an invitation, an API token or a domain open in place instead of on a new page.',
        'Server setup is followed live, and new servers wait properly for their address.',
    ]],
    ['date' => '2026-09-27', 'title' => 'One platform', 'changes' => [
        'Deploy, Infrastructure, Monitoring and Analytics now live in one app, with one account, one bill and one set of permissions.',
    ]],
];
