<?php

declare(strict_types=1);

// The help centre: short task guides, grouped by service. Each step names the page it happens on, so keep them in step
// with the navigation when pages move.
return [
    'groups' => [
        'platform' => ['title' => 'Your account', 'summary' => 'Projects, your team, billing, security and the API.', 'icon' => 'layers'],
        'infrastructure' => ['title' => 'Infrastructure', 'summary' => 'Providers, servers, websites, services, storage and backups.', 'icon' => 'server'],
        'deploy' => ['title' => 'Deploy', 'summary' => 'Repositories, environments, previews, scaling and releases.', 'icon' => 'cloud-upload'],
        'monitoring' => ['title' => 'Monitoring', 'summary' => 'Checks, telemetry, alerts, incidents and status pages.', 'icon' => 'pulse'],
        'security' => ['title' => 'Security', 'summary' => 'Scans, findings, servers, domains, attacks and compliance.', 'icon' => 'shield-check'],
        'analytics' => ['title' => 'Analytics', 'summary' => 'Sites, the tracker, reports, exploring, sharing and your data.', 'icon' => 'chart'],
    ],

    'guides' => [
        'getting-started' => [
            'group' => 'platform',
            'title' => 'Get started',
            'summary' => 'Create a project, turn on the services it needs, and find your way around.',
            'steps' => [
                ['Create a project', 'From Projects, choose New project. A project is one application or site; it gets production, staging and development environments to start with.'],
                ['Turn on services', 'In the project’s settings, switch on Deploy, Infrastructure, Monitoring or Analytics. Each appears in the project’s sidebar once it’s on.'],
                ['Start from a template', 'Projects → From a template sets up a project in one go: Laravel, Next.js, WordPress or a static site, or one of your own. To make your own, open a project’s Settings → Save as a template; it keeps the services, other environments, release settings, uptime checks on its domain and Analytics goals, and variable names with empty values.'],
                ['Find anything', 'Press Ctrl K (or ⌘ K) to open search from any page, and jump straight to a project, server or page.'],
                ['Follow what happens', 'The bell opens your notifications. Choose which ones you get in Your settings → Notifications.'],
            ],
        ],
        'team-and-access' => [
            'group' => 'platform',
            'title' => 'Invite your team and set access',
            'summary' => 'Add people to the account, give them a role, and choose which services they can use.',
            'steps' => [
                ['Invite someone', 'Go to Account → Members and choose Invite someone. Pick a role: owners and admins manage the account, members do day-to-day work, and viewers can only look.'],
                ['Limit services', 'On the member’s row, choose the services they can use. People only see the services you give them.'],
                ['Review changes', 'Account → Audit log records invitations, role changes, deletions and other important actions, with who made them.'],
            ],
        ],
        'billing' => [
            'group' => 'platform',
            'title' => 'Plans and billing',
            'summary' => 'Choose a plan for each service; they’re all billed together on one subscription.',
            'steps' => [
                ['Pick plans', 'Account → Billing shows each service’s plan. Every service has a free tier; upgrade only the ones that need more.'],
                ['Pay', 'Checkout and card details are handled by Stripe. Invoices and payment methods are in the billing portal, linked from the billing page.'],
                ['Change or cancel', 'Change a plan whenever you like. A cancelled plan stays active until the end of the period you’ve paid for, then moves to the free tier.'],
                ['Pay as you go', 'On a paid monthly plan, open the service’s tab on the billing page and turn on Pay as you go. Usage past your allowance is billed per unit instead of stopping, and you can set a monthly spend cap.'],
                ['Costs by project', 'Account → Billing → Costs by project puts what we charge beside what your servers cost, for each project: each service’s charge is split across the projects using it, and each server’s cost across the projects with websites on it. Last month’s cloud invoices are shown beside the estimate.'],
            ],
        ],
        'account-security' => [
            'group' => 'platform',
            'title' => 'Keep your account secure',
            'summary' => 'Two-factor authentication, passkeys, sessions and account-wide security rules.',
            'steps' => [
                ['Turn on two-factor authentication', 'Your settings → Security. Scan the code with an authenticator app, and keep the recovery codes somewhere safe.'],
                ['Add a passkey', 'On the same page, add a passkey to sign in with your device’s fingerprint, face or PIN.'],
                ['Check your sessions', 'Your settings → Sessions lists where you’re signed in and your recent sign-ins. Sign out anything you don’t recognise.'],
                ['Set rules for everyone', 'Owners can require two-factor authentication, limit sign-in to certain email domains or IP addresses, sign people out after a period of inactivity, and set up single sign-on, all from Account → Security.'],
                ['Provision people from your identity provider', 'On Account → Security, turn on SCIM provisioning and copy the base URL and token into Okta or Microsoft Entra ID. People you assign the app to join with the role you choose; unassigning or deactivating them removes them, and reactivating brings them back. The last owner is never removed.'],
            ],
        ],
        'api' => [
            'group' => 'platform',
            'title' => 'Use the API',
            'summary' => 'Automate deploys and more with API tokens.',
            'steps' => [
                ['Create a token', 'Account → API tokens → Create an API token. Choose only the abilities it needs and an expiry date. The token is shown once, so copy it straight away.'],
                ['Call the API', 'Send it as a bearer token. The API reference lists every endpoint, and the OpenAPI document can generate a client for you.'],
                ['Old scripts', 'Deployer API v1 scripts keep working unchanged, including old numeric IDs.'],
            ],
        ],
        'agencies' => [
            'group' => 'platform',
            'title' => 'Run client work (agencies)',
            'summary' => 'Your branding on what clients see, a monthly report for each client, and costs passed on with your markup.',
            'steps' => [
                ['White label', 'Account → Clients → White label. Set your name, an HTTPS logo and a colour; status pages, shared Analytics reports and client reports then show them instead of ours, without “Powered by”. It comes with the Deploy Team plan and above.'],
                ['Add clients', 'Add a client with the projects you run for them, who gets their report and your markup on costs. Preview last month’s report from the client’s card.'],
                ['Monthly reports', 'On the 1st, each client gets last month’s uptime, incidents, releases and visitors for their projects, with what they cost including your markup, sent in your name.'],
                ['Pass costs on', 'Download costs by client gives a CSV of each client’s projects with your plan share and server costs, marked up, ready for your invoices.'],
                ['Give clients access', 'To let a client look around, invite them as a Viewer on the Members page and limit them to their projects.'],
            ],
        ],
        'webhooks' => [
            'group' => 'platform',
            'title' => 'Webhooks',
            'summary' => 'Send deploys, incidents, servers, backups, findings and billing changes to your own automation.',
            'steps' => [
                ['Add an endpoint', 'Account → Webhooks → Add an endpoint. Give a public HTTPS address and choose the events, or Everything to get new kinds of event as they’re added. The signing secret is shown once.'],
                ['What arrives', 'A POST with JSON: id, event (such as deploy.succeeded, incident.opened, server.ready, backup.failed, security.finding or billing.plan_changed), created_at, account_id and data about what happened.'],
                ['Check it came from us', 'X-BuildPusher-Signature is v1= followed by HMAC-SHA256 of the X-BuildPusher-Timestamp header, a dot and the raw body, using the secret. The Webhooks page has a code sample. Ignore repeats of an X-BuildPusher-Delivery ID you’ve already handled.'],
                ['Retries', 'Answer with any 2xx within 10 seconds. Otherwise the delivery is tried up to six times over about three hours; after 20 failed deliveries in a row the endpoint is paused until you turn it back on. Send a test and Send again are on the same page, with the last deliveries’ results.'],
            ],
        ],
        'connect-a-provider' => [
            'group' => 'infrastructure',
            'title' => 'Connect a cloud provider',
            'summary' => 'Let BuildPusher create servers in your DigitalOcean, Hetzner Cloud, Vultr, Linode, AWS Lightsail, Scaleway or UpCloud account.',
            'steps' => [
                ['Create a token at the provider', 'In your provider’s dashboard, create an API token with read and write access.'],
                ['Add it here', 'Account → Providers → Add a provider. Choose the provider, paste the token and save. We check it straight away.'],
                ['Credentials that aren’t one token', 'AWS Lightsail takes an access key as ACCESS_KEY_ID:SECRET_ACCESS_KEY. Scaleway takes the project ID and an API secret key as PROJECT_ID:SECRET_KEY; servers go in that project and its SSH keys are added to them. UpCloud takes an API user (Account → People, with API access) as USERNAME:PASSWORD. Scaleway and UpCloud prices are shown in euros.'],
                ['Source control and DNS', 'GitHub, GitLab, Bitbucket and DNS providers (Cloudflare, Hetzner DNS and AWS Route 53, whose credential is ACCESS_KEY_ID:SECRET) are added the same way, from the same page. A DigitalOcean provider manages DigitalOcean DNS too.'],
            ],
        ],
        'create-a-server' => [
            'group' => 'infrastructure',
            'title' => 'Create a server',
            'summary' => 'Provision a server in your cloud account and follow its setup live.',
            'steps' => [
                ['Start', 'In your project, go to Infrastructure → Servers → Create a server.'],
                ['Choose what it’s for', 'Pick a provider, the server type (an app server runs PHP, Node, Caddy, MySQL and Redis together), a region and a size. Add recipes to run your own scripts once it’s set up.'],
                ['Watch it come up', 'The server page follows setup live: first waiting for the provider to give it an address, then each installation step. It usually takes a few minutes.'],
                ['Already have a server?', 'Import an Ubuntu server over SSH instead; we check it before managing it.'],
            ],
        ],
        'add-a-website' => [
            'group' => 'infrastructure',
            'title' => 'Add a website',
            'summary' => 'Host a website on a server, with a domain, TLS and a database.',
            'steps' => [
                ['Heal it automatically', 'With the health check on, tick Heal it automatically: when the check fails, BuildPusher restarts Caddy, PHP-FPM or the website’s workers if any have stopped (or reloads them when all are running), at most three times an hour, and notes what it did on the incident.'],
                ['Create it', 'Infrastructure → Websites → Add a website. Choose the server and the website’s main domain.'],
                ['Point the domain', 'Point the domain’s DNS at the server’s IP address, or choose a DNS provider (Cloudflare, DigitalOcean, Hetzner DNS or Route 53) and we’ll create the record in its zone. A certificate is issued automatically.'],
                ['Aliases and redirects', 'Add more domains on the website’s page, as aliases or as redirects to the main one.'],
                ['Database', 'App-server websites get their own MySQL database. You can inspect it, add users that expire, and copy data from another website.'],
            ],
        ],
        'server-tasks' => [
            'group' => 'infrastructure',
            'title' => 'Cron jobs, processes, firewall and services',
            'summary' => 'Schedule commands, keep workers running, open ports and install search or cache on a server.',
            'steps' => [
                ['Cron jobs', 'On the server’s Cron jobs tab, add a command and a schedule (or pick a preset such as every minute). It runs as the server’s user.'],
                ['Processes', 'The Processes tab keeps commands running and restarts them if they stop: queue workers, Horizon, Reverb, Pulse or your own. Restart one after a deploy from its row.'],
                ['Firewall', 'The Firewall tab opens or closes ports, for everyone or only some addresses. Turn on Private network there to let your other servers in the same region connect.'],
                ['Services', 'The Services tab installs Meilisearch, Typesense or Redis, listening on the server only or on the private network. Its address and key are shown once it’s running.'],
            ],
        ],
        'website-tools' => [
            'group' => 'infrastructure',
            'title' => 'Web server, files, logs and CDN',
            'summary' => 'Adjust how a website is served, look at its files and logs, and put it behind a CDN.',
            'steps' => [
                ['Web server settings', 'On the website’s Settings tab, add your own Caddy settings under Web server (Caddy). They’re checked first, and the previous settings come back if they’re invalid.'],
                ['WebSockets', 'Under WebSockets (Laravel Reverb) on the Settings tab, set up Reverb in one step: it runs as a process and the web server forwards its traffic.'],
                ['Files and logs', 'The Files tab lets you browse the website’s files, follow the end of a log, and search the logs for a phrase.'],
                ['CDN and firewall', 'On the Domains tab, choose CDN and firewall on a domain to serve it through Cloudflare, block countries or addresses, and rate-limit requests. The cache is cleared after every deploy.'],
                ['Slow queries and tuning', 'The Database tab shows the week’s slowest queries on the website’s database (with values replaced by ?, so repeats group together) once the slow query log is on; choose Turn on the slow query log to start it (queries over a second, for the whole MySQL server). It also suggests settings to change: the InnoDB buffer pool, temporary tables written to disk, connections near the limit and joins without indexes.'],
            ],
        ],
        'storage-buckets' => [
            'group' => 'infrastructure',
            'title' => 'Storage buckets',
            'summary' => 'Object storage for your apps, from S3, Spaces, R2, Google Cloud Storage and others.',
            'steps' => [
                ['Add a bucket', 'Infrastructure → Storage → Add a bucket. Create a new one or connect an existing bucket with its access key.'],
                ['Use it in an app', 'Attach the bucket to an environment and its details are added as environment variables (the usual AWS_ names), ready for Laravel’s s3 disk.'],
            ],
        ],
        'move-from-forge-or-ploi' => [
            'group' => 'infrastructure',
            'title' => 'Move from Forge or Ploi',
            'summary' => 'Read your servers and sites from Laravel Forge or Ploi and recreate them here, one site at a time.',
            'steps' => [
                ['Connect', 'Infrastructure → Servers → Move from Forge or Ploi. Paste an API token from Forge (Account → API tokens) or Ploi (Profile → API keys). It’s only read from, and stored encrypted; Forget the token removes it and everything read.'],
                ['What’s read', 'Each server’s sites with their domain, repository, branch, PHP version, environment file and deploy script, and the server’s cron jobs and daemons.'],
                ['Move a site', 'Choose one of your servers here and Move. A website is created for the domain with the same environment file, and the cron jobs and daemons that run in the site’s directory are added to the new server, pointed at the new directory and run as its user. Any that don’t fit, such as an unusual schedule, are listed for you to add yourself.'],
                ['Finish', 'Connect the repository in Deploy and deploy once, copy the database and uploaded files across, then point DNS at the new server. Nothing changes in Forge or Ploi, so the old site keeps serving until DNS moves.'],
            ],
        ],
        'costs' => [
            'group' => 'infrastructure',
            'title' => 'Costs and right-sizing',
            'summary' => 'See what your servers cost and what your providers billed, set a budget, and size them to what they actually use.',
            'steps' => [
                ['Costs', 'Infrastructure → Costs lists each server’s monthly price from your provider, its recent CPU and the projects on it, with totals.'],
                ['Actual bills', 'For DigitalOcean, Vultr, Linode and Lightsail credentials, Costs also shows what the provider actually charged: last month’s invoice beside the estimate from list prices, and this month so far. They’re read daily, or when you choose Check prices and bills now. The credential needs billing read access (for Lightsail, an AWS key allowed ce:GetCostAndUsage); if it hasn’t, Costs says so. Invoices cover everything in the provider account, such as bandwidth, volumes and backups, so they’re usually above the estimate. Hetzner has no billing API.'],
                ['Budget', 'Set a monthly budget there to be told when your servers go over it.'],
                ['Snapshots', 'On a server’s Settings tab, tick Snapshot before risky changes (DigitalOcean, Hetzner, Vultr, Linode and Lightsail servers). A provider snapshot is then taken before updates are installed, security fixes run or Node.js changes, and the three newest are kept; restore one from your provider’s dashboard if a change goes wrong. Take a snapshot now takes one straight away. Your provider charges for the storage.'],
                ['Disk clean-up', 'On a server’s Diagnostics tab, choose Measure the disk to see how much space old releases, old logs, package caches, unused Docker images and old temporary files take, then Clear any of them. The live release and the releases each website keeps stay, and logs from the last two weeks stay.'],
                ['Right-sizing', 'Once a server has a few days of readings, Costs suggests a smaller size when even its busiest 5% of the time leaves most of it idle (with the monthly saving), or a bigger one when it runs hot. Suggestions keep headroom: at most 60% CPU and 70% memory at the same load. Resize in your provider’s dashboard.'],
            ],
        ],
        'backups' => [
            'group' => 'infrastructure',
            'title' => 'Back up and restore',
            'summary' => 'Scheduled, verified backups to your own storage.',
            'steps' => [
                ['Add storage', 'Connect S3-compatible storage from Account → Providers.'],
                ['Schedule backups', 'On the website’s page, add a backup schedule. Every backup is checked after it’s written.'],
                ['Restore', 'Infrastructure → Backups lists every backup. Choose Restore and follow its progress.'],
                ['A second copy', 'When scheduling backups, choose Also copy to for a second destination (another provider or region). Each backup is sent there too, for a 3-2-1 setup; the backup list shows whether the second copy was made.'],
                ['Restore drills', 'Leave Monthly restore drill ticked and, once a month, the latest backup is restored into a scratch area on the server and checked (the database loads and the app starts), then cleaned up. If it fails, the account’s owners are emailed.'],
            ],
        ],
        'deploy-from-git' => [
            'group' => 'deploy',
            'title' => 'Deploy from Git',
            'summary' => 'Connect a repository and deploy it to a website on every push.',
            'steps' => [
                ['Connect the repository', 'Deploy → Repositories → Connect a repository. Choose the provider, the repository and branch, the environment, and the website it deploys to.'],
                ['Set up the build', 'Add your build commands, and the environment’s variables (see Environments and variables).'],
                ['Pipelines', 'Deploy → Pipelines chains repositories, such as the API and then the frontend. Choose Run: the first deploys, each next one starts only once the one before is live, and the run stops if a deploy fails, is rejected or is cancelled. Each step deploys its branch’s latest commit, with the usual approvals and checks.'],
                ['Monorepos', 'For one app in a larger repository, set Subdirectory to its folder (such as apps/api), and under Push deploys only for these paths list its folder (apps/api/**) plus anything it shares (packages/**). A push that changes nothing there doesn’t deploy it; connect each app in the repository the same way.'],
                ['Deploy', 'Deploy from the repository page, or turn on deploy on push. Each deploy is a new release, and the previous ones are kept.'],
                ['Follow it', 'The deploy page shows each step’s log as it runs, and the release is marked in Monitoring and Analytics once it’s live.'],
            ],
        ],
        'use-the-cli' => [
            'group' => 'deploy',
            'title' => 'Deploy from the command line',
            'summary' => 'Deploy, follow logs and roll back from your terminal or CI with the BuildPusher CLI.',
            'steps' => [
                ['Install it', 'Run curl -fsSL https://buildpusher.com/cli/install.sh | sh. It’s one PHP file, so it needs PHP 8.1 or later.'],
                ['Log in', 'Create an API token with the Deploy scopes under Account → API tokens, then run buildpusher login and paste it. In CI, set BUILDPUSHER_TOKEN instead.'],
                ['Deploy', 'Run buildpusher deploy <project> [environment] --wait to deploy and follow the log; add --ref=v1.4.0 to deploy a tag, branch or commit. It exits non-zero if the deploy fails, so CI jobs fail with it.'],
                ['Follow and undo', 'buildpusher status lists recent deploys, buildpusher logs <id> --follow streams one, and buildpusher rollback <id> goes back to the release a deploy shipped.'],
                ['Set defaults', 'Put {"project": "shop", "environment": "staging"} in .buildpusher.json at the root of your repository to leave them off each command.'],
                ['In GitHub Actions or code', 'Deploy from a workflow with the BuildPusher GitHub Action (buildpusher/deploy-action), which waits for the result, fails the job if the deploy fails, and comments the result on the pull request; or from your own code with the PHP (buildpusher/sdk) and JavaScript (@buildpusher/sdk) SDKs.'],
            ],
        ],
        'environments-and-variables' => [
            'group' => 'deploy',
            'title' => 'Environments and variables',
            'summary' => 'Configure each environment: variables, workers, how deploys run, and recipes.',
            'steps' => [
                ['Open the environment', 'Deploy → Environments, then choose production, staging or development.'],
                ['Clone one', 'Project settings → Environments → Copy from: pick an environment, name the new one and choose Clone. Its deploy settings, workers, recipes and variables come across, and its schedules come across switched off. Secret values are copied only if you tick Copy secret values too; otherwise you’re told which secrets to set. Connect a repository to a website for it to deploy.'],
                ['Variables', 'On the Variables tab, add environment variables and secrets. They’re encrypted, and previews never inherit them.'],
                ['From a password manager', 'Under Secrets from a password manager, connect Doppler (a service token for the config), 1Password Connect (your Connect server’s https address, a token, and the vault and item IDs; each field’s label becomes the variable name) or AWS Secrets Manager (a region, an access key that can read the secret, and its name; the secret’s value must be a JSON object). They sync every hour or when you choose Sync now, as secret variables for runtime and build. Variables set here by hand are never overwritten, and keys removed from the source are removed here.'],
                ['How deploys run', 'Choose the strategy (atomic, rolling, blue-green or canary), approvals, deploy locks and weekly windows.'],
                ['Destructive migrations', 'Tick Stop before destructive migrations on the environment’s How deploys run tab. Before migrating, a Laravel deploy lists the SQL its pending migrations would run (with migrate --pretend, which changes nothing) and stops if any of it drops, truncates or renames. The deploy page shows the statements; someone other than the person who deployed can approve them, and the same revision deploys again and migrates.'],
                ['Approve from Slack', 'On the environment’s Notifications tab, send Waiting for approval to a Slack (or Teams) destination. Each deploy that needs approval arrives with Approve and Reject buttons; they open the deploy with that choice ready, so one more tap confirms it. Only people who can approve deploys, other than whoever started it, can confirm.'],
                ['Release analysis', 'Under Watch health after each deploy, choose how long to watch, then the limits: failed requests, how much slower requests may get, and how far the Analytics conversion rate may drop. Each deploy is compared with the same length of time before it; past a limit, it’s marked failed and, with automatic rollback on, the previous release goes back live. The build page shows the before-and-after figures.'],
                ['Docker Compose', 'Choose the Docker Compose runtime on the How deploys run tab, give the Compose file (compose.yaml by default), the service that serves the website and its container port. Each deploy builds and starts the stack on your server as one project; the web service gets the website’s .env and sits behind Caddy with HTTPS, other services (a database, a worker) run beside it, and named volumes are kept between deploys.'],
                ['Workers and recipes', 'Run queue workers and schedulers from the Workers tab, and scripts on the environment’s servers from the Recipes tab.'],
            ],
        ],
        'scaling-and-maintenance' => [
            'group' => 'deploy',
            'title' => 'Autoscaling, maintenance mode and regions',
            'summary' => 'Scale with demand, take the site down for planned work, and see where it runs.',
            'steps' => [
                ['Autoscale', 'On the environment’s How deploys run tab, tick Scale automatically and set a target CPU. Replicas are added and removed within the minimum and maximum you set. Set Waiting jobs per replica too, and replicas are added when the environment’s queue monitors report a backlog, even while CPU is low.'],
                ['Waking from hibernation', 'A hibernating website wakes on its first request: its server tells BuildPusher straight away, and workers start again within seconds.'],
                ['Maintenance mode', 'On the Controls tab, choose Turn on maintenance mode. Visitors see a “back soon” page; open the secret path shown there once to get in yourself. It stays on through deploys until you turn it off.'],
                ['Regions', 'The Controls tab lists every website the environment deploys to and its region. To run in another region, add a website on a server there and connect the repository to it.'],
            ],
        ],
        'previews' => [
            'group' => 'deploy',
            'title' => 'Preview pull requests',
            'summary' => 'Give every pull request its own running copy.',
            'steps' => [
                ['Turn previews on', 'On the repository’s page, turn on previews. Each new pull request gets its own website and environment.'],
                ['Share it', 'GitHub App repositories get a check run and a comment with the preview’s address.'],
                ['Secrets', 'Previews start without secrets; approve the ones a preview needs for its exact revision.'],
                ['Start with data', 'On the repository’s page, choose a website to copy the database from, and each preview starts with a copy of it: everything, a quick branch with the first 1,000 rows of each table (best for big databases), or the schema only for your seeders to fill. Tick Mask personal data to replace emails, names, phone numbers, addresses, IP addresses and dates of birth in each copy.'],
                ['Clean-up', 'A preview is removed when its pull request is closed or merged.'],
                ['Any branch', 'On Previews, use Preview a branch to open one for any branch, not only a pull request, and choose when it closes (1 to 30 days). It deploys the branch’s latest commit; open it again to deploy newer commits or move the date.'],
            ],
        ],
        'rollback-and-promotion' => [
            'group' => 'deploy',
            'title' => 'Roll back, compare and promote',
            'summary' => 'Go back to a known release, see what changed, and move a tested build forward.',
            'steps' => [
                ['Roll back', 'On any earlier successful build, choose Roll back. The previous release is switched back in seconds.'],
                ['Compare', 'Choose Compare on a build to see the commits and settings that changed since another build.'],
                ['Release notes', 'Each deploy lists the commits since the last live release as release notes: feat:, fix: and perf: commits are grouped (use conventional commit prefixes for the best notes), and chores, CI, docs, tests and merges are left out. They’re on the deploy’s page and in Deploy live notifications to Slack and Discord. To publish them, choose Publish release notes on the environment’s Automation tab; the public page shows only the notes, not who wrote them.'],
                ['Promote', 'Promote a build that passed in staging to production; it keeps its history.'],
            ],
        ],
        'monitor-uptime' => [
            'group' => 'monitoring',
            'title' => 'Monitor uptime',
            'summary' => 'Check your sites and jobs, and get told when something breaks.',
            'steps' => [
                ['Add a monitor', 'Monitoring → Monitors → Add a monitor. Choose HTTP, DNS, TLS, TCP, a multi-step check, a heartbeat for scheduled jobs, or a queue.'],
                ['Multi-step checks', 'A multi-step check follows a flow such as signing in or checking out: up to 10 requests in order, sharing cookies, following redirects, checking each status and text, and carrying values like a CSRF token from one step to the next with extract and {{name}}. The steps are stored encrypted; use a dedicated test account. It checks over HTTP, so pages that only work with JavaScript need an API step instead.'],
                ['Choose where alerts go', 'Monitoring → Alerts → Destinations. Add email, push notifications, Slack, Microsoft Teams, PagerDuty, Discord or a webhook.'],
                ['Alerts on your phone', 'In your settings, under Notifications → Push notifications, choose Turn on for this device (on iPhone and iPad, add BuildPusher to your Home Screen first and do it from there). Then add a Push notification destination for yourself or for whoever is on call. Alerts arrive even when BuildPusher isn’t open; tap one to open the incident.'],
                ['Planned work', 'Add a maintenance window before planned work, so expected downtime doesn’t open an incident.'],
                ['Services you depend on', 'Under Services you depend on, follow GitHub, Cloudflare, DigitalOcean, Twilio and others, or any status page built on Atlassian Statuspage. Their status is checked every five minutes and shown beside your monitors, with the affected components and the provider’s incident.'],
            ],
        ],
        'send-telemetry' => [
            'group' => 'monitoring',
            'title' => 'Send errors, traces and metrics',
            'summary' => 'Instrument your application so problems point at the release that caused them.',
            'steps' => [
                ['Get a key', 'Monitoring → Setup. Create an ingestion key for the environment.'],
                ['Server logs', 'On a server’s Logs tab, under Send logs to Monitoring, choose an environment. A small agent then sends the server’s system warnings and errors, and its websites’ Laravel warnings and errors with stack traces, to Monitoring → Events (type log), where you can search them and set alert rules on matching lines. It sends up to 600 lines a minute and uses its own key, revoked when you stop.'],
                ['Tickets', 'Monitoring → Setup → Ticket trackers: connect GitHub Issues (a repository and a fine-grained token that can write issues), Linear (an API key and the team ID) or Jira Cloud (your atlassian.net site, email, API token and project key). Then choose Create ticket on any issue; the ticket gets the error, where it happened, how often, and a link back, and the issue links to it. When the ticket is closed (completed in Linear, done in Jira), the issue is resolved within the hour; if the error happens again, it reopens.'],
                ['Laravel', 'For Laravel apps, composer require buildpusher/laravel and set BUILDPUSHER_TOKEN. Each request is recorded with a timeline of its queries, mail and notifications and its cache hits and misses; exceptions carry a hashed user ID so issues count the people affected; slow queries and N+1 queries (the same query five or more times in a request) are flagged; queue jobs, scheduled tasks, commands and warning-level logs are recorded too. php artisan buildpusher:deploy marks each release.'],
                ['Send data', 'Use the SDK snippet on the setup page, or send OpenTelemetry traces, logs and metrics to the OTLP endpoint shown there.'],
                ['Investigate', 'Errors are grouped into Issues; Events, Metrics and Traces let you dig in, and Releases show what changed.'],
                ['Browser errors', 'Monitoring → Setup → Browser errors. List the origins your pages are served from and turn it on, then add the script tag it shows to every page. JavaScript errors and unhandled promise rejections become issues from the “browser” service, with the browser, operating system and release. Query strings are dropped from page addresses.'],
                ['Link to deploys', 'Every trace shows the deploy that was live when it ran, and each deploy links to its requests and traces, so you can see what a release changed.'],
            ],
        ],
        'alert-rules' => [
            'group' => 'monitoring',
            'title' => 'Alert rules',
            'summary' => 'Open incidents from errors, latency, log lines, metrics and SLO burn, and keep alerts quiet enough to trust.',
            'steps' => [
                ['Add a rule', 'Monitoring → Alerts → Rules → Add a rule. Choose what it measures, the threshold and how many minutes it must hold, then where it notifies.'],
                ['Alerts from log lines', 'Choose “Matching log / event count”, enter text to match (such as “payment declined”), and a threshold: 1 alerts on the first matching line, a higher number when it appears too often.'],
                ['Error budget burn', 'Choose “SLO error-budget burn rate” and an objective. A burn rate of 1 uses the budget exactly over the objective’s period; alert at 2 or more to hear while there’s still budget left, not once it’s breached.'],
                ['Anomalies', 'Choose “Metric anomaly score” to be told when a metric moves far from its usual range, without picking a fixed threshold.'],
                ['Keep it quiet', 'Alerts → Noise ranks the rules and monitors that fired most in the last 30 days, with how often they flapped (recovered within five minutes, unacknowledged) and how often nobody acknowledged them, and suggests how to tune each.'],
            ],
        ],
        'incidents-and-status-pages' => [
            'group' => 'monitoring',
            'title' => 'Incidents and status pages',
            'summary' => 'Respond to problems and keep your users informed.',
            'steps' => [
                ['Respond', 'Monitoring → Incidents. Acknowledge, assign, and add notes; the timeline records it all.'],
                ['Escalate', 'Set escalation steps on an alert rule, so someone else is told if nobody responds.'],
                ['Post-mortems', 'On a resolved incident, choose Write a post-mortem. It starts as a draft built from the incident: how long it lasted, what the check or rule saw, who responded, your notes, and any deploys in the two hours before it opened as leads. Edit each section, save, and publish it to a status page if you like.'],
                ['Publish a status page', 'Monitoring → Status pages → Create. Choose the monitors to show, post updates, and let people subscribe by email.'],
                ['Groups and reports', 'Give components a group (such as API or Website) to show them under a heading with the group’s worst status. Every month has a public uptime report (linked as Monthly uptime at the foot of the page) with each component’s uptime, the incidents and total downtime; tick Email a monthly uptime report to send it to subscribers on the 1st.'],
            ],
        ],
        'security-basics' => [
            'group' => 'security',
            'title' => 'Get started with Security',
            'summary' => 'Turn on Security, read the findings and fix what matters first.',
            'steps' => [
                ['Turn it on', 'In the project’s settings, switch on Security. Each check runs straight away, then as often as your plan allows (weekly on Free, daily on Pro, every six hours on Team).'],
                ['Read the overview', 'Security shows a score out of 100 and a grade, the checks and when they last ran, and the most serious open findings.'],
                ['Fix and confirm', 'Each finding says how to fix it. After fixing, choose Scan now on the check; the finding resolves when the scan no longer sees it.'],
                ['Ignore with a reason', 'For a false positive or an accepted risk, choose Ignore and say why. It stays ignored through later scans until someone reopens it.'],
                ['Domains and email', 'The domain check looks at every domain in the project: certificates, TLS versions, the redirect to HTTPS, security headers, SPF and DMARC, and CNAMEs left pointing at services that could be taken over.'],
            ],
        ],
        'security-code' => [
            'group' => 'security',
            'title' => 'Vulnerable packages, secrets and the deploy gate',
            'summary' => 'Find known vulnerabilities and leaked credentials in what you deploy, and stop risky deploys.',
            'steps' => [
                ['Vulnerable packages', 'Security reads the composer.lock and package-lock.json of each live website and checks every package against the OSV vulnerability database. Each finding names the version that fixes it. Development-only packages count one level lower.'],
                ['Leaked secrets', 'On Pro and above, Security looks for keys and tokens (AWS, Stripe, GitHub, Slack, private keys and more) in each website’s code and in recent error reports and logs, and for .env files committed with the code. Secrets are never stored or shown in full.'],
                ['Deploy gate', 'On the Security overview, choose Block deploys with for an environment. A deploy whose packages have a vulnerability at that level stops before it goes live, and the reason appears on the deploy.'],
                ['Accepting a risk', 'To let a deploy through anyway, ignore the finding in Security with a reason. The gate treats ignored findings as accepted.'],
            ],
        ],
        'security-servers' => [
            'group' => 'security',
            'title' => 'Harden and update servers',
            'summary' => 'See how each server is set up, fix problems in a click, and install security updates on a schedule.',
            'steps' => [
                ['What’s checked', 'On Pro and above, Security audits each server the project runs on: SSH passwords and root sign-in, the firewall and anything open to the internet (such as a database), fail2ban, automatic updates, waiting security updates, a pending reboot, and the Ubuntu release.'],
                ['Fix in a click', 'Findings with a fix have a button, such as Turn the firewall on or Allow SSH keys only. Fixes never remove BuildPusher’s own key access, and the server is checked again afterwards.'],
                ['Update windows', 'Security → Servers sets a weekly window (day and hour, in UTC) when each server installs its security updates, optionally rebooting if they need it. Install updates now runs them straight away.'],
            ],
        ],
        'security-firewall' => [
            'group' => 'security',
            'title' => 'Firewall, bots and attacks',
            'summary' => 'Cloudflare protection for your zones, and automatic blocking of attackers.',
            'steps' => [
                ['Zones', 'Security → Firewall lists the Cloudflare zones behind the project’s domains (their DNS must be managed at Cloudflare through BuildPusher).'],
                ['Security level and bots', 'On the Team plan, choose how suspicious a visitor must look before Cloudflare checks them, and turn on bot fight mode to challenge known bots and scrapers.'],
                ['Under attack', 'During an attack, turn on Under attack mode: every visitor gets a short check before reaching the site. Turn it off again afterwards.'],
                ['Per domain', 'Blocking countries or addresses and rate limits stay on each website’s Domains tab, under CDN and firewall.'],
                ['Automatic blocking', 'On Pro and above, Security checks each website’s access log every five minutes and blocks addresses in the server’s firewall after 20 failed sign-ins, 10 requests for known vulnerable paths (such as /.env) or 3,000 requests in ten minutes. Security → Attacks shows who’s blocked, lets you unblock someone, and sets how long blocks last and which addresses are never blocked.'],
            ],
        ],
        'security-access' => [
            'group' => 'security',
            'title' => 'SSH keys and access reviews',
            'summary' => 'Give people their own SSH access, and review who can reach the account.',
            'steps' => [
                ['Add your key', 'In Your settings → Security, add your SSH public key (the contents of your .pub file).'],
                ['Give access', 'On Pro and above, Security → Servers gives a member SSH access to a server as its deploy user, with the keys on their profile. When they change their keys, or leave the account, the server is updated.'],
                ['Review access', 'On the Team plan, Security → Access lists members (with two-factor status), API tokens and SSH access. Tick anything that should go and choose Complete review; the removals happen and the review is kept as evidence.'],
                ['Reminders', 'A finding appears when the last review is more than 90 days old, and for members without two-factor authentication and API tokens unused for 90 days.'],
            ],
        ],
        'security-compliance' => [
            'group' => 'security',
            'title' => 'Compliance evidence',
            'summary' => 'Download evidence for SOC 2, ISO 27001 and security questionnaires.',
            'steps' => [
                ['Download', 'On the Team plan, Security → Compliance downloads a ZIP covering the last 3, 6 or 12 months.'],
                ['What’s inside', 'Spreadsheets of members and two-factor status, API tokens, access reviews, every deploy with who asked and who approved, vulnerabilities and how each was handled, scans, patching, blocked attacks, backups and restore tests, incidents, and the audit log, with a README mapping each to the controls it supports.'],
                ['Keeping it complete', 'Review access every 90 days, fix or ignore findings with a reason, and keep backup verification on; each shows up in the next pack.'],
            ],
        ],
        'add-analytics' => [
            'group' => 'analytics',
            'title' => 'Add analytics to a website',
            'summary' => 'Count visitors without cookies, and measure the goals that matter.',
            'steps' => [
                ['Add the site', 'Analytics → Sites → Add a site, with the domain it runs on.'],
                ['Install the tracker', 'Copy the one-line script from the site’s page into your website’s head. Visits appear within a minute.'],
                ['Set goals', 'Analytics → Goals. Count visits to a page, or an event you send, as a conversion.'],
                ['Count more', 'Add data-outbound, data-downloads, data-vitals or data-not-found to the script for links, downloads, page speed and missing pages. Engagement (time on page and scroll depth) is counted automatically.'],
                ['Events without code', 'Give any button or link a class such as bp-event-name=Signup, and bp-event-plan=pro for a property; clicking it sends the event.'],
                ['Groups and searches', 'In the site’s settings, name groups of pages (such as Blog: /blog/*) to see them added up. Searches are read from ?q=, ?s= or ?search= (choose with data-search), and buildpusher.search(\'term\', 0) records a search that found nothing.'],
                ['Spam and bots', 'Known referrer spam, bots and ignored addresses are left out automatically; the site’s page says how many. Add your own spam domains in the site’s settings.'],
                ['Leave visits out', 'In the site’s settings, list addresses or networks to ignore (such as your office); their visits aren’t counted. Single-page apps that route with #/paths should add data-hash to the snippet.'],
                ['Custom properties', 'To break events down by your own details, list the property names in the site’s settings, then send them: window.buildpusher.track(\'signup\', {plan: \'pro\'}).'],
            ],
        ],
        'explore-analytics' => [
            'group' => 'analytics',
            'title' => 'Explore your traffic',
            'summary' => 'Choose any period, compare it, save segments, and dig into paths, retention and sales.',
            'steps' => [
                ['Pick a period', 'On the Analytics overview, choose a preset or set From and To dates, and compare with the previous period, the same period last year, or nothing.'],
                ['Filter and save', 'Click any page, channel, country, city, browser or campaign to filter by it, then save the filters as a view (a segment) to come back to.'],
                ['Explore', 'Analytics → Explore has Insights (the biggest changes), Paths (where people came from and went next), Properties, Items (e-commerce), Attribution, Clicks, Forms, Experiments and Retention.'],
                ['A/B tests', 'Start an experiment in Explore → Experiments with a key, its variants (the control first) and a goal. On the page, buildpusher.variant(\'key\', [\'control\', \'b\']) returns the variant to show and keeps it the same for the whole visit. Results show each variant’s conversion rate, lift over the control and whether it’s significant (p below 0.05); wait for a few hundred visitors per variant before deciding.'],
                ['Ad spend', 'On Campaigns, import a daily campaign report exported from Google Ads, Meta, LinkedIn or any ad platform as CSV (date, campaign and cost; source, currency, clicks and impressions if it has them). Each campaign then shows its cost, cost per conversion and return on ad spend. Campaign and source are matched to utm_campaign and utm_source, ignoring case; importing a day again replaces it.'],
                ['Attribution', 'Attribution credits goals and revenue to the channel or campaign that brought the converting visit (last touch) and that first brought the visitor (first touch; needs data-retention to look past one visit).'],
                ['Clicks and forms', 'Add data-clicks to the snippet for click maps, and data-forms for where people give up on forms. Only element descriptions, positions and field names are kept, never what people type.'],
                ['Retention', 'Add data-retention to the script to recognise returning browsers. It keeps a random ID in the browser, so ask for consent where the law requires it.'],
                ['Notes', 'Choose Add a note on the overview to mark a launch or outage on the chart.'],
            ],
        ],
        'share-analytics' => [
            'group' => 'analytics',
            'title' => 'Reports, alerts and sharing',
            'summary' => 'Send regular reports and CSV exports, get told about spikes and unusual days, and share or embed a report.',
            'steps' => [
                ['Reports and alerts', 'On the site’s page, under Reports and alerts, add a weekly or monthly report, or a traffic spike alert, by email or to a Slack incoming webhook.'],
                ['Scheduled CSV exports', 'Save a view of the report with the filters you want (for example, only /pricing, or one campaign), then add a weekly or monthly CSV export and choose that view. The CSV arrives by email on Monday or the 1st, covering the week or month just gone.'],
                ['Unusual traffic alerts', 'An unusual traffic alert compares yesterday’s visitors and conversions with the same weekday over the last eight weeks, and tells you when one was far above or below normal. It needs four weeks of history and at least 20 visitors (or 5 conversions) on a typical day before it judges.'],
                ['Share', 'Under Share the report, create a read-only link, with a password if you like.'],
                ['View-only people', 'Under View-only access, invite someone by email; they get their own link to the report without joining the account, and you can remove it on its own.'],
                ['Embed', 'A link without a password comes with an iframe snippet to put the report on another page.'],
                ['Looker Studio', 'Download the connector (/connectors/looker-studio/Code.gs and appsscript.json), paste both into a new Apps Script project, deploy it as a community connector and open it in Looker Studio. Sign in with an API token that has analytics:read, enter the site ID and choose a breakdown. It reads the same daily rows as the API’s /analytics/sites/{site}/rows, which also suits spreadsheets and other dashboards.'],
                ['Export', 'Export a report as CSV from the overview, or read it through the API.'],
            ],
        ],
        'analytics-data' => [
            'group' => 'analytics',
            'title' => 'Import, export and your own domain',
            'summary' => 'Bring your Google Analytics history, send raw data to BigQuery, and avoid ad blockers.',
            'steps' => [
                ['Import from Google Analytics', 'On the site’s page, choose Connect Google Analytics, then pick the GA4 property and dates. Only days before your site’s own data are imported.'],
                ['Raw data export', 'Under Raw data export, choose one of the project’s storage buckets. Each night, the previous day’s events are written as gzipped JSON lines, one file per day, ready for BigQuery or Athena.'],
                ['From your server', 'Send pageviews and events from your backend with an API token that has the Analytics write scope: POST /api/v1/analytics/sites/{site}/events, or analyticsEvents() in the PHP and JavaScript SDKs. Include each visitor’s IP address and browser so they’re counted like browser visits.'],
                ['Your own domain', 'Under Send through your own domain, copy the proxy rules for Caddy or Nginx and the matching snippet, so the tracker loads from your site and ad blockers don’t stop it.'],
            ],
        ],
    ],
];
