<?php

return [
    'products' => [
        'deployer' => [
            'name' => 'Deployer',
            'accent' => 'deploy',
            'icon' => 'layers',
            'eyebrow' => 'Build and ship',
            'headline' => 'Deploy with clarity. Recover with confidence.',
            'summary' => 'Provision infrastructure, ship Git releases, operate production, and recover with the full history in view.',
            'card_summary' => 'Provision servers and services, release from Git, and operate production from one control plane.',
            'card_features' => ['Infrastructure provisioning', 'Traceable Git releases', 'Configuration plans and promotion controls', 'Operational recovery'],
            'suite_workflow' => [
                'title' => 'Ship a controlled release',
                'description' => 'Connect a Git repository, review configuration plans and preflight checks, promote approved releases, and keep a known recovery point.',
                'features' => ['Pull-request previews with protected-secret controls', 'Atomic, rolling, blue-green, and canary releases', 'Configuration plans, approval gates, and exact-revision rollback'],
            ],
            'highlights' => [
                ['icon' => 'code', 'title' => 'From repository to release', 'description' => 'Connect a Git provider, review preflight and approvals, then follow the release through health verification.'],
                ['icon' => 'server', 'title' => 'Infrastructure in context', 'description' => 'Provision servers and managed services, configure domains, and see provider-catalog cost estimates.'],
                ['icon' => 'clock', 'title' => 'A visible recovery path', 'description' => 'Keep retained releases, verified backups, operational history, and exact-revision rollback close at hand.'],
            ],
            'preview' => [
                'context' => 'Storefront · production',
                'title' => 'Deployment #1841',
                'description' => 'A release record with revision, rollout, and verification in one place.',
                'status' => 'Health verified',
                'status_tone' => 'success',
                'metrics' => [['label' => 'Revision', 'value' => 'a71c8ef'], ['label' => 'Strategy', 'value' => 'Blue/green'], ['label' => 'Recovery', 'value' => 'Available']],
                'activity_label' => 'Release timeline',
                'activity' => [
                    ['title' => 'Preflight checks', 'detail' => 'Risk snapshot and approval recorded', 'state' => 'Passed'],
                    ['title' => 'Release activated', 'detail' => 'New revision serving production traffic', 'state' => 'Complete'],
                    ['title' => 'Health verification', 'detail' => 'Configured checks completed', 'state' => 'Verified'],
                ],
            ],
            'highlights_heading' => 'A delivery control plane with the recovery path in view.',
            'workflows_heading' => 'Connect. Provision. Release.',
            'workflows_intro' => 'Keep the path from source change to production operation visible to the whole team.',
            'guardrails_title' => 'Keep production actions accountable.',
            'guardrails_description' => 'Review authorization, retain operational evidence, and keep recovery actions attached to the resource and release they affect.',
            'groups' => [
                [
                    'label' => 'Build and ship',
                    'title' => 'Make every deployment traceable',
                    'description' => 'From the first commit to a verified release, every step stays visible and recoverable.',
                    'features' => [
                        ['Framework-ready runtimes', 'Laravel, PHP, Node, Python, Docker, Next.js, Nuxt, Django, WordPress, and Statamic.'],
                        ['Connected Git providers', 'GitHub, GitLab, and Bitbucket repositories with signed webhook deployments.'],
                        ['Safe release strategies', 'Atomic, rolling, blue-green, and canary releases with retained versions.'],
                        ['Preview environments', 'Isolated pull-request previews with GitHub checks, durable status comments, protected-secret approval, and expiry cleanup.'],
                        ['Preflight and approvals', 'Risk snapshots, approvals, locks, maintenance windows, cancellation, and release notes.'],
                        ['Configuration plans', 'Compare a proposed configuration plan before applying it as a separately authorized and recorded operation.'],
                        ['Build comparison and promotion', 'Compare build revisions, review acceptance evidence, and promote approved releases with their lineage preserved.'],
                        ['Automatic recovery', 'After an activated release fails, automatically return to the last retained successful version.'],
                    ],
                ],
                [
                    'label' => 'Infrastructure',
                    'title' => 'Provision without the guesswork',
                    'description' => 'Create, connect, and evolve production infrastructure with the important state kept in view.',
                    'features' => [
                        ['Cloud provisioning', 'Provision or import servers, then follow each setup stage through to ready.'],
                        ['Domains and TLS', 'Manage primary domains, aliases, redirects, certificates, IPv4, and IPv6.'],
                        ['Cloudflare automation', 'Create DNS records and temporary domains without leaving the workspace.'],
                        ['High availability', 'Run weighted load-balancer pools with node probes, failover, and safe cleanup.'],
                        ['Managed data services', 'Create databases, Valkey, object storage, credentials, schemas, and connections.'],
                        ['Cost visibility', 'Review provider-catalog estimates, budgets, idle capacity, and right-sizing signals.'],
                    ],
                ],
                [
                    'label' => 'Observe',
                    'title' => 'See health in context',
                    'description' => 'Understand what changed, what is slow, and what needs attention before it becomes guesswork.',
                    'features' => [
                        ['Website health', 'Scheduled checks, response timing, success rates, outage history, and recovery events.'],
                        ['Server telemetry', 'CPU, memory, disk, load, network, and process signals in compact trend charts.'],
                        ['Threshold alerts', 'Configurable warning levels, cooldowns, deduplication, and recovery notifications.'],
                        ['Searchable logs', 'Follow deployment and command output with retention, filtering, and safe downloads.'],
                        ['Status communication', 'Public service health, incident timelines, subscriptions, and safe API responses.'],
                        ['Incident command centre', 'Correlate operational history and retain root cause, remediation, and follow-up reviews.'],
                    ],
                ],
                [
                    'label' => 'Automate',
                    'title' => 'Act safely when it matters',
                    'description' => 'Turn repeatable operations into controlled workflows while preserving human accountability.',
                    'features' => [
                        ['Scheduled tasks', 'Encrypted commands, run history, timeouts, overlap protection, and failure alerts.'],
                        ['Workers and processes', 'Queue workers, restart policies, delays, scaling, hibernation, and resume controls.'],
                        ['Command center', 'Run, cancel, repeat, filter, and export owner-scoped server operations.'],
                        ['API and webhooks', 'Automate environments, deployments, rollback, logs, and infrastructure through OpenAPI.'],
                        ['CLI and MCP', 'Operate Buildpusher from scripts, terminals, or compatible AI tools.'],
                        ['Reusable recipes', 'Build private automation or install reviewable community recipes you can edit.'],
                    ],
                ],
                [
                    'label' => 'Secure and govern',
                    'title' => 'Govern access without slowing delivery',
                    'description' => 'Give teams the access they need, keep sensitive data protected, and retain an audit trail.',
                    'features' => [
                        ['Encrypted secrets', 'Versioned environment variables, provider tokens, keys, scripts, and command output.'],
                        ['Organizations and roles', 'Admin, operator, developer, auditor, billing, and viewer permissions.'],
                        ['Enterprise sign-in', 'OpenID Connect SSO with PKCE, mandatory two-factor authentication, and session controls.'],
                        ['Access policies', 'IP and CIDR restrictions, allowed email domains, and idle-session timeouts.'],
                        ['Complete accountability', 'Activity, sign-in, deployment, incident, and command histories with safe exports.'],
                        ['Scoped ownership', 'Resource authorization, signed callbacks, rate limits, and lockout prevention.'],
                    ],
                ],
                [
                    'label' => 'Recover and reuse',
                    'title' => 'Recover with evidence, not instinct',
                    'description' => 'Keep the history and reusable building blocks needed to resolve the difficult day quickly.',
                    'features' => [
                        ['Verified backups', 'Create, inspect, restore, and retain database backups with clear outcomes.'],
                        ['Release rollback', 'Return to an exact known revision while keeping logs and deployment lineage.'],
                        ['Database recovery', 'Use expiring credentials, inspect schema health, and clone guarded environments.'],
                        ['Incident history', 'Connect failures, alerts, acknowledgement, and recovery to the affected resource.'],
                        ['Recipe library', 'Save working server setups and reuse moderated community automation safely.'],
                        ['Platform diagnostics', 'Review restricted service checks while the public sees a disclosure-safe status page.'],
                    ],
                ],
            ],
            'capabilities' => ['DigitalOcean', 'Hetzner Cloud', 'Vultr', 'Cloudflare DNS', 'GitHub', 'GitLab', 'Bitbucket'],
            'workflows' => [
                ['Launch with confidence', 'Connect a source repository, provision infrastructure, run preflight, and verify the first release.'],
                ['Recover with evidence', 'Correlate the incident, inspect retained logs and backups, and redeploy a known revision.'],
                ['Operate with control', 'Set capacity, schedules, health thresholds, cost budgets, and high-availability routing.'],
            ],
            'guardrails' => ['Encrypted credentials', 'Signed callbacks', 'Bounded history', 'Verified backups', 'Health thresholds', 'Exact-revision recovery'],
            'questions' => [
                ['q' => 'Who is Deployer for?', 'a' => 'Development teams and operators who want a focused control plane while keeping applications in their own cloud accounts.'],
                ['q' => 'Where does my application run?', 'a' => 'On infrastructure in the provider account you connect. Deployer coordinates the operational workflow.'],
                ['q' => 'Can I recover a previous release?', 'a' => 'Yes. Recorded revisions can be redeployed with lineage and logs retained, provided the target is ready.'],
                ['q' => 'How are sensitive values handled?', 'a' => 'Provider tokens, environments, scripts, command text, and retained output are encrypted at rest and owner-scoped.'],
                ['q' => 'What does Deployer not replace?', 'a' => 'Your cloud provider, source host, application architecture, and independent external monitoring remain separate. Provider invoices remain authoritative for cost.'],
            ],
        ],
        'monitor' => [
            'name' => 'Monitor',
            'accent' => 'monitor',
            'icon' => 'pulse',
            'eyebrow' => 'Understand production',
            'headline' => 'See service health, errors, and changes together.',
            'summary' => 'Bring scheduled service checks, queue and heartbeat health, and application telemetry into one operational view, then turn the signals that matter into actionable incidents.',
            'card_summary' => 'Understand uptime, application behavior, and incidents across the projects your team operates.',
            'card_features' => ['HTTP, DNS, TLS, TCP, queue, and heartbeat checks', 'Metrics, logs, traces, and issues', 'Alerts, SLOs, and status pages', 'Saved dashboards and maintenance windows'],
            'suite_workflow' => [
                'title' => 'Detect and respond',
                'description' => 'Bring scheduled service checks, queue and worker health, and application telemetry into a response flow your team can follow.',
                'features' => ['HTTP, DNS, TLS, TCP, queue, heartbeat, and maintenance-window context', 'OpenTelemetry telemetry, grouped issues, and mapped Deployer release context', 'Alert destinations, incident timelines, and service objectives'],
            ],
            'highlights' => [
                ['icon' => 'pulse', 'title' => 'Availability with history', 'description' => 'Schedule HTTP, DNS, TLS, and TCP checks; watch queues, workers, and heartbeat jobs; and put maintenance windows beside service history.'],
                ['icon' => 'activity', 'title' => 'Application signals together', 'description' => 'Inspect OpenTelemetry traces, metrics, structured logs, events, and grouped recurring issues.'],
                ['icon' => 'bell', 'title' => 'A response path for incidents', 'description' => 'Route alert transitions, acknowledge incidents, review SLOs, and publish selected status updates.'],
            ],
            'preview' => [
                'context' => 'Storefront · production',
                'title' => 'Service health',
                'description' => 'Availability, telemetry, and response activity share one service view.',
                'status' => 'Monitoring',
                'status_tone' => 'success',
                'metrics' => [['label' => 'HTTP check', 'value' => 'Healthy'], ['label' => 'Latency', 'value' => '142 ms'], ['label' => 'Objective', 'value' => 'On target']],
                'activity_label' => 'Recent signals',
                'activity' => [
                    ['title' => 'Scheduled check', 'detail' => 'storefront.example · response received', 'state' => 'Healthy'],
                    ['title' => 'Latency alert rule', 'detail' => 'Trigger and recovery conditions configured', 'state' => 'Armed'],
                    ['title' => 'Incident timeline', 'detail' => 'Acknowledgement and resolution remain linked', 'state' => 'Ready'],
                ],
            ],
            'highlights_heading' => 'Follow a service from first signal through recovery.',
            'workflows_heading' => 'Instrument. Detect. Respond.',
            'workflows_intro' => 'Put availability, application telemetry, and team response into a practical sequence.',
            'workflows' => [
                ['Instrument the service', 'Create an application, configure a scoped ingestion credential, and review collection health for its environment.'],
                ['Track availability', 'Add HTTP, DNS, TLS, or TCP checks; monitor queue and worker health; and use heartbeat schedules for recurring jobs. Keep planned work beside service history with maintenance windows.'],
                ['Respond and learn', 'Route alert transitions to a notification destination, manage the incident timeline, and compare reliability with an objective.'],
            ],
            'guardrails' => ['Scoped ingestion credentials', 'Configurable trigger and recovery checks', 'Cooldown and deduplication controls', 'Delivery history and retries', 'Workspace roles and audit history', 'Export controls'],
            'guardrails_title' => 'Keep signals useful and response traceable.',
            'guardrails_description' => 'Control how telemetry enters the workspace, how alert transitions are routed, and who can review operational history.',
            'capabilities' => ['OpenTelemetry', 'Deployer release context', 'Queue and heartbeat checks', 'SLOs', 'Email alerts', 'Signed webhooks', 'Slack', 'Microsoft Teams', 'PagerDuty', 'Discord'],
            'questions' => [
                ['q' => 'What can Monitor collect?', 'a' => 'Monitor supports scheduled HTTP, DNS, TLS, and TCP checks, queue and worker monitoring, cron or interval heartbeats, and application telemetry including OpenTelemetry traces, metrics, logs, events, and grouped issues.'],
                ['q' => 'Can I share service health publicly?', 'a' => 'Yes. Create a public status page for selected services and publish incident timelines and subscriber updates.'],
                ['q' => 'How does Monitor relate to my other Buildpusher apps?', 'a' => 'Connect a Deployer environment and Monitor application to the same Core project to review mapped release context with service health. Monitor keeps its operational records and applies its own workspace access and plan rules.'],
                ['q' => 'Is Monitor billed with Deployer?', 'a' => 'No. Monitor keeps its workspace plan state, access, and operational data separate from Deployer; available billing options depend on the product.'],
            ],
            'groups' => [
                [
                    'label' => 'Availability',
                    'title' => 'Know when a service changes',
                    'description' => 'Track network, queue, and heartbeat checks over time, with maintenance and incident context close at hand.',
                    'features' => [
                        ['HTTP and network monitors', 'Measure HTTP response time and run scheduled DNS, TLS, and TCP checks with retained history and recovery state.'],
                        ['Queue and worker monitors', 'Track ready-job thresholds, queue snapshots, worker liveness, and reported execution outcomes.'],
                        ['Cron and heartbeat monitors', 'Detect missed scheduled jobs and background work using interval or cron schedules, grace periods, and run outcomes.'],
                        ['Maintenance windows', 'Record planned work so expected changes have context alongside service health.'],
                        ['Public status pages', 'Publish selected service health and incident timelines for customers and teams.'],
                    ],
                ],
                [
                    'label' => 'Application telemetry',
                    'title' => 'Follow a request through the system',
                    'description' => 'Explore the application signals that help explain user-visible behavior and operational changes.',
                    'features' => [
                        ['OpenTelemetry traces', 'Inspect traces, spans, and trace events across instrumented services.'],
                        ['Metrics and series', 'Review numeric metrics, resource context, and changes across a selected time range.'],
                        ['Logs and events', 'Search structured activity with severity, route, service, and environment context.'],
                        ['Errors and issues', 'Group recurring application issues and follow their frequency and latest occurrence.'],
                        ['Issue digests', 'Use configurable email digests to review new and recurring application issues.'],
                        ['Deployment context', 'Review release records received from a connected Deployer environment alongside service signals and incident history.'],
                    ],
                ],
                [
                    'label' => 'Alerts and incidents',
                    'title' => 'Turn important signals into clear work',
                    'description' => 'Set explicit alert conditions, route notifications, and keep the incident timeline with the response.',
                    'features' => [
                        ['Configurable alert rules', 'Evaluate service, metric, log-pattern, telemetry-volume, freshness, anomaly, and SLO signals.'],
                        ['Breach and recovery controls', 'Set trigger and recovery checks, cooldowns, and thresholds suited to each signal.'],
                        ['Notification destinations', 'Route incident transitions to configured destinations, test delivery, and retry failed sends.'],
                        ['Incident history', 'Acknowledge, update, and review incidents with linked alerts and operational evidence.'],
                    ],
                ],
                [
                    'label' => 'Service objectives',
                    'title' => 'Measure reliability against your goals',
                    'description' => 'Keep service-level objectives, burn signals, dependencies, and saved views connected to the work.',
                    'features' => [
                        ['Service-level objectives', 'Define reliability targets and review performance over their configured windows.'],
                        ['Burn-rate alerts', 'Surface fast-moving budget consumption before a target is exhausted.'],
                        ['Dependency map', 'Explore service relationships and use them to orient an investigation.'],
                        ['Saved dashboards', 'Arrange dashboard widgets into saved views for the metrics and services your team follows.'],
                    ],
                ],
                [
                    'label' => 'Team controls',
                    'title' => 'Keep the service view accountable',
                    'description' => 'Give collaborators workspace-scoped access while Monitor retains ownership of its operational data and entitlements.',
                    'features' => [
                        ['Workspace roles and invitations', 'Invite team members and manage their Monitor workspace roles.'],
                        ['Environment ingestion', 'Use scoped ingestion credentials and review collection health and retry state.'],
                        ['Audit and exports', 'Review administrative history and export workspace data through controlled flows.'],
                        ['Monitor plan status', 'Review Monitor entitlements and workspace access separately from the other app grants.'],
                    ],
                ],
            ],
        ],
        'analytics' => [
            'name' => 'Analytics',
            'accent' => 'analytics',
            'icon' => 'chart',
            'eyebrow' => 'Understand your audience',
            'headline' => 'Understand the work your website is doing.',
            'summary' => 'A focused, privacy-aware view of visitors, pages, campaigns, and conversion goals for teams who want useful answers without a noisy dashboard.',
            'card_summary' => 'See how visitors find your site, what they read, and which actions turn into meaningful outcomes.',
            'card_features' => ['Cookieless visitor and visit estimates', 'Pages, sources, campaigns, and devices', 'Path and event goals with release context', 'Consent-aware collection and timezone comparisons'],
            'suite_workflow' => [
                'title' => 'Measure what changed',
                'description' => 'Explore traffic, attribution, and conversion goals, then use mapped release and incident annotations to investigate change.',
                'features' => ['Page, referrer, campaign, device, and timezone-aware comparisons', 'Consent-aware browser collection with path and event goals', 'Deployer release and Monitor incident annotations'],
            ],
            'highlights' => [
                ['icon' => 'chart', 'title' => 'Traffic trends at a glance', 'description' => 'Review estimated visitors, page activity, and change over a selected date range.'],
                ['icon' => 'globe', 'title' => 'Sources and campaigns', 'description' => 'Compare referrers and campaign tags to see where visitors come from and what they read.'],
                ['icon' => 'check', 'title' => 'Goals tied to outcomes', 'description' => 'Track meaningful destination paths or explicit events, then compare goal activity with acquisition context.'],
                ['icon' => 'activity', 'title' => 'Changes beside traffic', 'description' => 'For mapped project resources, review Deployer releases and Monitor incidents alongside Analytics reports.'],
            ],
            'preview' => [
                'context' => 'storefront.example · last 30 days',
                'title' => 'Site overview',
                'description' => 'Traffic estimates alongside acquisition, content, and goal reports.',
                'status' => 'Sample report',
                'status_tone' => 'info',
                'metrics' => [['label' => 'Visitors', 'value' => '1,248'], ['label' => 'Top source', 'value' => 'Search'], ['label' => 'Goal events', 'value' => '37']],
                'activity_label' => 'Traffic and change context',
                'activity' => [
                    ['title' => 'Top page', 'detail' => '/pricing · page performance', 'state' => 'Content'],
                    ['title' => 'Deployer release', 'detail' => 'Release annotation for a mapped environment', 'state' => 'Change'],
                    ['title' => 'Monitor incident', 'detail' => 'Incident annotation for a mapped environment', 'state' => 'Context'],
                ],
            ],
            'highlights_heading' => 'Useful audience answers without a noisy dashboard.',
            'workflows_heading' => 'Measure. Explore. Learn.',
            'workflows_intro' => 'Turn a site property into reports your team can use to make its next decision.',
            'workflows' => [
                ['Add a website', 'Create a site property, install the collection snippet, and follow the verification steps.'],
                ['Explore acquisition and content', 'Choose a date range to compare traffic, page paths, referring sources, and campaign tags.'],
                ['Measure outcomes', 'Define a path or event goal, review conversion context, and export a filtered report when you need to share it.'],
                ['Connect changes to results', 'Map the Analytics site and relevant product environments to one Core project to show Deployer releases and Monitor incidents beside traffic reports.'],
            ],
            'guardrails' => ['Cookieless traffic estimates', 'Site-scoped collection setup', 'Workspace roles and invitations', 'Filtered CSV exports with expiry', 'No cross-site identity profile', 'Product-owned workspace access'],
            'guardrails_title' => 'Keep collection and reporting clear.',
            'guardrails_description' => 'Analytics focuses on useful website trends without relying on cross-site tracking cookies; site access, collection setup, and exports stay within the product workspace.',
            'capabilities' => ['Cookieless visitor estimates', 'Consent-aware collection', 'UTM attribution', 'Path and event goals', 'Device and browser reports', 'Timezone comparisons', 'Filtered CSV exports', 'Release and incident context'],
            'questions' => [
                ['q' => 'What does Analytics measure?', 'a' => 'Analytics reports visitor and page trends, referrers, campaigns, path goals, and explicit event goals for configured website properties.'],
                ['q' => 'Does Analytics use cross-site tracking cookies?', 'a' => 'The product is designed around cookieless estimates and does not rely on cross-site tracking cookies for the website trends shown here.'],
                ['q' => 'Can I share a report?', 'a' => 'You can prepare a filtered CSV export from a selected site and report filters. Downloads expire after their configured retention period.'],
                ['q' => 'Can I see releases and incidents with my reports?', 'a' => 'Yes. When the site and product environments are explicitly mapped to the same Core project, Analytics can show Deployer release and Monitor incident annotations beside the site reports. Each product retains its own operational records.'],
                ['q' => 'Does Analytics share data or workspace access with the other apps?', 'a' => 'No. Analytics keeps its own sites, reports, and workspace access. Connect a site and other product resources to the same Core project when you want authorized release or incident context.'],
            ],
            'groups' => [
                [
                    'label' => 'Privacy-aware measurement',
                    'title' => 'Learn from useful trends',
                    'description' => 'Get a clear view of website activity without building a cross-site identity profile.',
                    'features' => [
                        ['Visitor and visit estimates', 'Review cookieless visitor estimates and visits grouped with a 30-minute inactivity window.'],
                        ['Owned site workspaces', 'Keep website properties and collaborators grouped in an Analytics workspace.'],
                        ['Collection controls', 'Configure site collection and review the installation and verification steps.'],
                        ['Consent-aware browser tracker', 'Respect consent and opt-out choices, track single-page navigation, and retry transient delivery failures.'],
                        ['Domain verification', 'Verify ownership before collection starts and manage the domains allowed to send site events.'],
                    ],
                ],
                [
                    'label' => 'Acquisition and content',
                    'title' => 'See how people arrive and what they read',
                    'description' => 'Follow the sources, campaigns, and pages that shape the path through your website.',
                    'features' => [
                        ['Page performance', 'Compare visits and engagement across normalized page paths.'],
                        ['Referrer attribution', 'Understand which referring sources bring people to your site.'],
                        ['Campaign reporting', 'Review campaign tags and source context alongside site activity.'],
                        ['Traffic trends and comparisons', 'Use date ranges, site timezones, and period comparisons to explore changes in audience activity.'],
                        ['Page paths', 'Compare top, entry, and exit pages to see where visits begin, continue, and end.'],
                        ['Device and browser reports', 'Break down audience activity by device, browser, and operating system.'],
                        ['Recent traffic', 'Review recently collected page and event activity in the site dashboard.'],
                    ],
                ],
                [
                    'label' => 'Goals and outcomes',
                    'title' => 'Measure the action that matters',
                    'description' => 'Turn important visitor paths and explicit events into conversion signals.',
                    'features' => [
                        ['Path goals', 'Track visits to thank-you pages or other meaningful destination paths.'],
                        ['Event goals', 'Measure explicit actions such as a demo request or signup event.'],
                        ['Conversion context', 'Compare goal activity with the pages, sources, and campaigns that led to it.'],
                    ],
                ],
                [
                    'label' => 'Reporting and teams',
                    'title' => 'Share useful answers with your team',
                    'description' => 'Keep reports, team access, and data controls inside the Analytics product.',
                    'features' => [
                        ['Filtered CSV exports', 'Prepare reports from your selected site and filters; downloads expire after their configured retention.'],
                        ['Workspace collaboration', 'Invite teammates and assign workspace roles for Analytics sites.'],
                        ['Product-owned workspace access', 'Manage Analytics collaborators and site access separately from Deployer and Monitor.'],
                    ],
                ],
                [
                    'label' => 'Project context',
                    'title' => 'Put product changes beside audience trends',
                    'description' => 'Use a shared Core project to relate mapped product resources while Analytics remains the owner of its reports and site data.',
                    'features' => [
                        ['Deployer release annotations', 'Review release versions and revisions associated with explicitly mapped environments.'],
                        ['Monitor incident annotations', 'See incident status and timing from mapped Monitor environments beside Analytics activity.'],
                        ['Explicit resource mapping', 'Connect the site and product environments to a shared project; project access is checked before product context is shown.'],
                    ],
                ],
            ],
        ],
    ],
    'workspace_capabilities' => [
        [
            'icon' => 'grid',
            'title' => 'A shared project directory',
            'description' => 'Create a project once, then explicitly connect its Deployer environments, Monitor applications, and Analytics sites so the team can follow related work together.',
        ],
        [
            'icon' => 'users',
            'title' => 'Team membership with app-specific access',
            'description' => 'Invite collaborators and manage their Deployer, Monitor, and Analytics access independently. One workspace does not automatically grant access to every app.',
        ],
        [
            'icon' => 'activity',
            'title' => 'An operational view for the team',
            'description' => 'Review authorized project activity, notifications, search results, and current deployment, service-health, and traffic context from the shared workspace.',
        ],
        [
            'icon' => 'settings',
            'title' => 'Workspace tools in one place',
            'description' => 'Review product access and plan status, open Deployer cost breakdowns, manage customer status pages, and find shared help, API documentation, and feedback.',
        ],
    ],
    'connections' => [
        [
            'source' => 'deployer',
            'target' => 'monitor',
            'mode' => 'Deployment context',
            'title' => 'Keep releases beside service health',
            'description' => 'Authorized Deployer release records appear in Monitor so responders can review the version and revision alongside service signals and incident history.',
        ],
        [
            'source' => 'deployer',
            'target' => 'analytics',
            'mode' => 'Release annotation',
            'title' => 'See when a release meets a traffic change',
            'description' => 'A successful, mapped Deployer release adds a revision and time annotation to the Analytics site timeline, separate from visitor event data.',
        ],
        [
            'source' => 'monitor',
            'target' => 'analytics',
            'mode' => 'Incident timeline',
            'title' => 'Keep incident changes with site reports',
            'description' => 'When a connected Monitor incident opens, is acknowledged, or is resolved, Analytics can show that lifecycle event beside the mapped site’s reports.',
        ],
        [
            'source' => 'analytics',
            'target' => 'monitor',
            'mode' => 'Read-only traffic context',
            'title' => 'Bring traffic context into an investigation',
            'description' => 'Monitor incident investigations can compare plan-bounded Analytics pageviews and distinct visitors from before the incident with the preceding window.',
        ],
    ],
];
