<?php

return [
    'products' => [
        'deployer' => [
            'name' => 'Deployer',
            'eyebrow' => 'Build and ship',
            'headline' => 'Deploy with clarity. Recover with confidence.',
            'summary' => 'Provision infrastructure, ship Git releases, operate production, and recover with the full history in view.',
            'card_summary' => 'Provision servers and services, release from Git, and operate production from one control plane.',
            'card_features' => ['Infrastructure provisioning', 'Traceable Git releases', 'Operational recovery'],
            'groups' => [
                [
                    'label' => 'Build and ship',
                    'title' => 'Make every deployment traceable',
                    'description' => 'From the first commit to a verified release, every step stays visible and recoverable.',
                    'features' => [
                        ['Framework-ready runtimes', 'Laravel, PHP, Node, Python, Docker, Next.js, Nuxt, Django, WordPress, and Statamic.'],
                        ['Connected Git providers', 'GitHub, GitLab, and Bitbucket repositories with signed webhook deployments.'],
                        ['Safe release strategies', 'Atomic, rolling, blue-green, and canary releases with retained versions.'],
                        ['Preview environments', 'Isolated pull-request previews with GitHub checks and durable status comments.'],
                        ['Preflight and approvals', 'Risk snapshots, approvals, locks, maintenance windows, cancellation, and release notes.'],
                        ['Automatic recovery', 'After an activated release fails, automatically return to the last retained successful version.'],
                    ],
                ],
                [
                    'label' => 'Infrastructure',
                    'title' => 'Provision without the guesswork',
                    'description' => 'Create, connect, and evolve production infrastructure with the important state kept in view.',
                    'features' => [
                        ['Cloud provisioning', 'Provision or import servers, then follow each setup stage through to ready.'],
                        ['Domains and TLS', 'Manage primary domains, aliases, redirects, certificates, IPv4, and IPv6.'],
                        ['Cloudflare automation', 'Create DNS records and temporary domains without leaving the workspace.'],
                        ['High availability', 'Run weighted load-balancer pools with node probes, failover, and safe cleanup.'],
                        ['Managed data services', 'Create databases, Valkey, object storage, credentials, schemas, and connections.'],
                        ['Cost visibility', 'Review provider-catalog estimates, budgets, idle capacity, and right-sizing signals.'],
                    ],
                ],
                [
                    'label' => 'Observe',
                    'title' => 'See health in context',
                    'description' => 'Understand what changed, what is slow, and what needs attention before it becomes guesswork.',
                    'features' => [
                        ['Website health', 'Scheduled checks, response timing, success rates, outage history, and recovery events.'],
                        ['Server telemetry', 'CPU, memory, disk, load, network, and process signals in compact trend charts.'],
                        ['Threshold alerts', 'Configurable warning levels, cooldowns, deduplication, and recovery notifications.'],
                        ['Searchable logs', 'Follow deployment and command output with retention, filtering, and safe downloads.'],
                        ['Status communication', 'Public service health, incident timelines, subscriptions, and safe API responses.'],
                        ['Incident command centre', 'Correlate operational history and retain root cause, remediation, and follow-up reviews.'],
                    ],
                ],
                [
                    'label' => 'Automate',
                    'title' => 'Act safely when it matters',
                    'description' => 'Turn repeatable operations into controlled workflows while preserving human accountability.',
                    'features' => [
                        ['Scheduled tasks', 'Encrypted commands, run history, timeouts, overlap protection, and failure alerts.'],
                        ['Workers and processes', 'Queue workers, restart policies, delays, scaling, hibernation, and resume controls.'],
                        ['Command center', 'Run, cancel, repeat, filter, and export owner-scoped server operations.'],
                        ['API and webhooks', 'Automate environments, deployments, rollback, logs, and infrastructure through OpenAPI.'],
                        ['CLI and MCP', 'Operate Buildpusher from scripts, terminals, or compatible AI tools.'],
                        ['Reusable recipes', 'Build private automation or install reviewable community recipes you can edit.'],
                    ],
                ],
                [
                    'label' => 'Secure and govern',
                    'title' => 'Govern access without slowing delivery',
                    'description' => 'Give teams the access they need, keep sensitive data protected, and retain an audit trail.',
                    'features' => [
                        ['Encrypted secrets', 'Versioned environment variables, provider tokens, keys, scripts, and command output.'],
                        ['Organizations and roles', 'Admin, operator, developer, auditor, billing, and viewer permissions.'],
                        ['Enterprise sign-in', 'OpenID Connect SSO with PKCE, mandatory two-factor authentication, and session controls.'],
                        ['Access policies', 'IP and CIDR restrictions, allowed email domains, and idle-session timeouts.'],
                        ['Complete accountability', 'Activity, sign-in, deployment, incident, and command histories with safe exports.'],
                        ['Scoped ownership', 'Resource authorization, signed callbacks, rate limits, and lockout prevention.'],
                    ],
                ],
                [
                    'label' => 'Recover and reuse',
                    'title' => 'Recover with evidence, not instinct',
                    'description' => 'Keep the history and reusable building blocks needed to resolve the difficult day quickly.',
                    'features' => [
                        ['Verified backups', 'Create, inspect, restore, and retain database backups with clear outcomes.'],
                        ['Release rollback', 'Return to an exact known revision while keeping logs and deployment lineage.'],
                        ['Database recovery', 'Use expiring credentials, inspect schema health, and clone guarded environments.'],
                        ['Incident history', 'Connect failures, alerts, acknowledgement, and recovery to the affected resource.'],
                        ['Recipe library', 'Save working server setups and reuse moderated community automation safely.'],
                        ['Platform diagnostics', 'Review restricted service checks while the public sees a disclosure-safe status page.'],
                    ],
                ],
            ],
            'providers' => ['DigitalOcean', 'GitHub', 'GitLab', 'Bitbucket'],
            'tour' => [
                [
                    'label' => 'Overview',
                    'title' => 'One calm operational overview',
                    'description' => 'Current infrastructure, active work, and anything needing attention are visible before you open a resource.',
                    'window' => 'Workspace',
                    'metrics' => [['8', 'Websites'], ['3', 'Servers'], ['24', 'Deployments']],
                    'events' => [['System health', 'Operational'], ['Latest deployment', 'Succeeded'], ['Open incidents', '0']],
                ],
                [
                    'label' => 'Provision',
                    'title' => 'Infrastructure with visible progress',
                    'description' => 'Track cloud creation, network assignment, software installation, recipes, and website placement as explicit stages.',
                    'window' => 'Server provisioning',
                    'metrics' => [['5/5', 'Stages'], ['1', 'Public IP'], ['3', 'Recipes']],
                    'events' => [['Cloud server created', 'Complete'], ['Base software installed', 'Complete'], ['Ready for websites', 'Complete']],
                ],
                [
                    'label' => 'Deploy',
                    'title' => 'Every release stays explainable',
                    'description' => 'Follow revision, trigger, timing, heartbeat, output, and health verification from one deployment record.',
                    'window' => 'Deployment #1841',
                    'metrics' => [['a71c8ef', 'Revision'], ['42s', 'Duration'], ['Webhook', 'Trigger']],
                    'events' => [['Fetching revision', 'Complete'], ['Activating release', 'Complete'], ['Health verification', 'Passed']],
                ],
                [
                    'label' => 'Monitor',
                    'title' => 'Health checks that tell a story',
                    'description' => 'Use scheduled and manual checks to understand response time, success rate, outages, and recoveries.',
                    'window' => 'Website health',
                    'metrics' => [['99%', 'Success'], ['184ms', 'Latest'], ['172ms', 'Median']],
                    'events' => [['12:00 check', 'Healthy'], ['11:55 check', 'Healthy'], ['11:50 check', 'Healthy']],
                ],
                [
                    'label' => 'Operate',
                    'title' => 'Actions keep their accountability',
                    'description' => 'Commands, activity, notifications, and incident history remain scoped to the owner and connected to their resources.',
                    'window' => 'Command center',
                    'metrics' => [['2', 'Active'], ['18', 'Succeeded'], ['1', 'Failed']],
                    'events' => [['production-01', 'Running'], ['worker-01', 'Queued'], ['staging-01', 'Succeeded']],
                ],
                [
                    'label' => 'Reuse',
                    'title' => 'Repeat the setup that works',
                    'description' => 'Keep private recipes or install reviewable community snapshots that remain editable in your own account.',
                    'window' => 'Recipe library',
                    'metrics' => [['12', 'Saved'], ['4', 'Installed'], ['1', 'Update']],
                    'events' => [['Harden SSH access', 'Installed'], ['Install PHP runtime', 'Current'], ['Configure Redis', 'Update ready']],
                ],
            ],
            'workflows' => [
                ['Launch with confidence', 'Connect providers, provision infrastructure, run preflight, and verify the first release.'],
                ['Recover without guesswork', 'Correlate the incident, inspect retained evidence, and roll back to an exact release.'],
                ['Scale with control', 'Set capacity, schedules, health thresholds, cost budgets, and high-availability routing.'],
            ],
            'guardrails' => ['Encrypted credentials', 'Signed callbacks', 'Bounded history', 'Verified backups', 'Health thresholds', 'Exact-revision recovery'],
            'questions' => [
                ['q' => 'Who is Deployer for?', 'a' => 'Development teams and operators who want a focused control plane while keeping applications in their own cloud accounts.'],
                ['q' => 'Where does my application run?', 'a' => 'On infrastructure in the provider account you connect. Deployer coordinates the operational workflow.'],
                ['q' => 'Can I recover a previous release?', 'a' => 'Yes. Recorded revisions can be redeployed with lineage and logs retained, provided the target is ready.'],
                ['q' => 'How are sensitive values handled?', 'a' => 'Provider tokens, environments, scripts, command text, and retained output are encrypted at rest and owner-scoped.'],
                ['q' => 'What does Deployer not replace?', 'a' => 'Your cloud provider, source host, application architecture, and independent external monitoring remain separate. Provider invoices remain authoritative for cost.'],
            ],
        ],
        'monitor' => [
            'name' => 'Monitor',
            'eyebrow' => 'Understand production',
            'headline' => 'See service health, errors, and changes together.',
            'summary' => 'Bring uptime checks and application telemetry into one operational view, then turn the signals that matter into actionable incidents.',
            'card_summary' => 'Understand uptime, application behavior, and incidents across the projects your team operates.',
            'card_features' => ['Uptime and heartbeat checks', 'Metrics, logs, traces, and issues', 'Alerts, SLOs, and status pages'],
            'groups' => [
                [
                    'label' => 'Availability',
                    'title' => 'Know when a service changes',
                    'description' => 'Track checks and heartbeats over time, with maintenance and incident context close at hand.',
                    'features' => [
                        ['Scheduled HTTP monitors', 'Measure response time and availability on a schedule, with check history and recovery state.'],
                        ['Heartbeat monitors', 'Detect missed scheduled jobs and background work using controlled heartbeat signals.'],
                        ['Maintenance windows', 'Record planned work so expected changes have context alongside service health.'],
                        ['Public status pages', 'Publish selected service health and incident timelines for customers and teams.'],
                    ],
                ],
                [
                    'label' => 'Application telemetry',
                    'title' => 'Follow a request through the system',
                    'description' => 'Explore the application signals that help explain user-visible behavior and operational changes.',
                    'features' => [
                        ['OpenTelemetry traces', 'Inspect traces, spans, and trace events across instrumented services.'],
                        ['Metrics and series', 'Review numeric metrics, resource context, and changes across a selected time range.'],
                        ['Logs and events', 'Search structured activity with severity, route, service, and environment context.'],
                        ['Errors and issues', 'Group recurring application issues and follow their frequency and latest occurrence.'],
                    ],
                ],
                [
                    'label' => 'Alerts and incidents',
                    'title' => 'Turn important signals into clear work',
                    'description' => 'Set explicit alert conditions, route notifications, and keep the incident timeline with the response.',
                    'features' => [
                        ['Configurable alert rules', 'Evaluate service, metric, log-pattern, telemetry-volume, freshness, anomaly, and SLO signals.'],
                        ['Breach and recovery controls', 'Set trigger and recovery checks, cooldowns, and thresholds suited to each signal.'],
                        ['Notification destinations', 'Route incident transitions to configured destinations, test delivery, and retry failed sends.'],
                        ['Incident history', 'Acknowledge, update, and review incidents with linked alerts and operational evidence.'],
                    ],
                ],
                [
                    'label' => 'Service objectives',
                    'title' => 'Measure reliability against your goals',
                    'description' => 'Keep service-level objectives, burn signals, dependencies, and saved views connected to the work.',
                    'features' => [
                        ['Service-level objectives', 'Define reliability targets and review performance over their configured windows.'],
                        ['Burn-rate alerts', 'Surface fast-moving budget consumption before a target is exhausted.'],
                        ['Dependency map', 'Explore service relationships and use them to orient an investigation.'],
                        ['Saved dashboards', 'Build and revisit dashboards around the metrics and services your team follows.'],
                    ],
                ],
                [
                    'label' => 'Team controls',
                    'title' => 'Keep the service view accountable',
                    'description' => 'Give collaborators workspace-scoped access while retaining data and subscription controls for Monitor.',
                    'features' => [
                        ['Workspace roles and invitations', 'Invite team members and manage their Monitor workspace roles.'],
                        ['Environment ingestion', 'Use scoped ingestion credentials and review collection health and retry state.'],
                        ['Audit and exports', 'Review administrative history and export workspace data through controlled flows.'],
                        ['Independent Monitor plan', 'Manage Monitor entitlements and billing separately from Deployer and Analytics.'],
                    ],
                ],
            ],
        ],
        'analytics' => [
            'name' => 'Analytics',
            'eyebrow' => 'Understand your audience',
            'headline' => 'Understand the work your website is doing.',
            'summary' => 'A focused, privacy-aware view of visitors, pages, campaigns, and conversion goals for teams who want useful answers without a noisy dashboard.',
            'card_summary' => 'See how visitors find your site, what they read, and which actions turn into meaningful outcomes.',
            'card_features' => ['Cookieless traffic estimates', 'Pages, referrers, and campaigns', 'Path and event goals'],
            'groups' => [
                [
                    'label' => 'Privacy-aware measurement',
                    'title' => 'Learn from useful trends',
                    'description' => 'Get a clear view of website activity without building a cross-site identity profile.',
                    'features' => [
                        ['Cookieless estimates', 'See useful visitor and page trends without relying on cross-site tracking cookies.'],
                        ['Owned site workspaces', 'Keep website properties and collaborators grouped in an Analytics workspace.'],
                        ['Collection controls', 'Configure site collection and review the installation and verification steps.'],
                    ],
                ],
                [
                    'label' => 'Acquisition and content',
                    'title' => 'See how people arrive and what they read',
                    'description' => 'Follow the sources, campaigns, and pages that shape the path through your website.',
                    'features' => [
                        ['Page performance', 'Compare visits and engagement across normalized page paths.'],
                        ['Referrer attribution', 'Understand which referring sources bring people to your site.'],
                        ['Campaign reporting', 'Review campaign tags and source context alongside site activity.'],
                        ['Traffic trends', 'Use date ranges and report filters to explore changes in audience activity.'],
                    ],
                ],
                [
                    'label' => 'Goals and outcomes',
                    'title' => 'Measure the action that matters',
                    'description' => 'Turn important visitor paths and explicit events into conversion signals.',
                    'features' => [
                        ['Path goals', 'Track visits to thank-you pages or other meaningful destination paths.'],
                        ['Event goals', 'Measure explicit actions such as a demo request or signup event.'],
                        ['Conversion context', 'Compare goal activity with the pages, sources, and campaigns that led to it.'],
                    ],
                ],
                [
                    'label' => 'Reporting and teams',
                    'title' => 'Share useful answers with your team',
                    'description' => 'Keep reports, team access, and data controls inside the Analytics product.',
                    'features' => [
                        ['Filtered CSV exports', 'Prepare reports from your selected site and filters; downloads expire after their configured retention.'],
                        ['Workspace collaboration', 'Invite teammates and assign workspace roles for Analytics sites.'],
                        ['Separate Analytics subscription', 'Manage Analytics plans independently from Deployer and Monitor.'],
                    ],
                ],
            ],
        ],
    ],
];
