<?php

declare(strict_types=1);

// The help centre: short task guides, grouped by service. Each step names the page it happens on, so keep them in step
// with the navigation when pages move.
return [
    'groups' => [
        'platform' => ['title' => 'Your account', 'summary' => 'Projects, your team, billing, security and the API.', 'icon' => 'layers'],
        'infrastructure' => ['title' => 'Infrastructure', 'summary' => 'Providers, servers, websites, services, storage and backups.', 'icon' => 'server'],
        'deploy' => ['title' => 'Deploy', 'summary' => 'Repositories, environments, previews, scaling and releases.', 'icon' => 'cloud-upload'],
        'monitoring' => ['title' => 'Monitoring', 'summary' => 'Checks, telemetry, alerts, incidents and status pages.', 'icon' => 'pulse'],
        'security' => ['title' => 'Security', 'summary' => 'Scans, findings, servers, domains, attacks and compliance.', 'icon' => 'shield-check'],
        'analytics' => ['title' => 'Analytics', 'summary' => 'Sites, the tracker, reports, exploring, sharing and your data.', 'icon' => 'chart'],
        // Audit's group and guides show once Audit is switched on (config/site_audits.php).
        ...((bool) env('AUDIT_ENABLED', false) ? ['audit' => ['title' => 'Audit', 'summary' => 'Simulated visitors, competitor comparisons and what to improve.', 'icon' => 'search']] : []),
    ],

    'guides' => [
        'getting-started' => [
            'group' => 'platform',
            'title' => 'Get started',
            'summary' => 'Create a project, turn on the services it needs, and find your way around.',
            'steps' => [
                ['Create a project', 'From Projects, choose New project. A project is one application or site; it starts with a production environment, and you can add staging and others in its Settings. Tick the services it needs; Analytics or Monitoring on their own work with any site, wherever it’s hosted, and the setup guide then skips servers and deploys.'],
                ['Turn on services', 'The project’s overview lists every service: choose Turn on beside Deploy, Infrastructure, Monitoring, Security, Analytics or Audit. Opening a service from the sidebar that isn’t on yet offers the same button. The project’s Setup guide then walks you through the first steps.'],
                ['Start from a template', 'Projects → From a template sets up a project in one go: Laravel, Next.js, WordPress or a static site, or one of your own. To make your own, open a project’s Settings → Save as a template; it keeps the services, other environments, release settings, uptime checks on its domain and Analytics goals, and variable names with empty values.'],
                ['Find anything', 'Press Ctrl K (or ⌘ K) to open search from any page, and jump straight to a project, server or page.'],
                ['Follow what happens', 'The bell opens your notifications. Choose which ones you get in Your settings → Notifications.'],
                ['Choose your language', 'The app follows your browser’s language when it’s English, Spanish, French, German or Portuguese. To pick one yourself, open Your settings → Profile and choose a Language.'],
            ],
        ],
        'team-and-access' => [
            'group' => 'platform',
            'title' => 'Invite your team and set access',
            'summary' => 'Add people to the account, give them a role, and choose which services they can use.',
            'steps' => [
                ['Invite someone', 'Go to Account → Members and choose Invite someone. Pick a role: owners and admins manage the account, members do day-to-day work, and viewers can only look.'],
                ['Limit services', 'On the member’s row, choose the services they can use. People only see the services you give them.'],
                ['Review changes', 'Account → Audit log records invitations, role changes, deletions and other important actions, with who made them.'],
            ],
        ],
        'billing' => [
            'group' => 'platform',
            'title' => 'Plans and billing',
            'summary' => 'Choose a plan for each service; they’re all billed together on one subscription.',
            'steps' => [
                ['Pick plans', 'Account → Billing shows each service’s plan. Every service has a free tier; upgrade only the ones that need more.'],
                ['Pay', 'Checkout and card details are handled by Stripe. Invoices and payment methods are in the billing portal, linked from the billing page.'],
                ['Change or cancel', 'Change a plan whenever you like. A cancelled plan stays active until the end of the period you’ve paid for, then moves to the free tier.'],
                ['Pay as you go', 'On a paid monthly plan, open the service’s tab on the billing page and turn on Pay as you go. Usage past your allowance is billed per unit instead of stopping, and you can set a monthly spend cap.'],
                ['Costs by project', 'Account → Billing → Costs by project puts what we charge beside what your servers cost, for each project: each service’s charge is split across the projects using it, and each server’s cost across the projects with websites on it. Last month’s cloud invoices are shown beside the estimate.'],
            ],
        ],
        'account-security' => [
            'group' => 'platform',
            'title' => 'Keep your account secure',
            'summary' => 'Two-factor authentication, passkeys, sessions and account-wide security rules.',
            'steps' => [
                ['Turn on two-factor authentication', 'Your settings → Security. Scan the code with an authenticator app, and keep the recovery codes somewhere safe.'],
                ['Add a passkey', 'On the same page, add a passkey to sign in with your device’s fingerprint, face or PIN.'],
                ['Check your sessions', 'Your settings → Sessions lists where you’re signed in and your recent sign-ins. Sign out anything you don’t recognise.'],
                ['Set rules for everyone', 'Owners can require two-factor authentication, limit sign-in to certain email domains or IP addresses, sign people out after a period of inactivity, and set up single sign-on, all from Account → Security.'],
                ['Provision people from your identity provider', 'On Account → Security, turn on SCIM provisioning and copy the base URL and token into Okta or Microsoft Entra ID. People you assign the app to join with the role you choose; unassigning or deactivating them removes them, and reactivating brings them back. The last owner is never removed.'],
            ],
        ],
        'api' => [
            'group' => 'platform',
            'title' => 'Use the API',
            'summary' => 'Automate deploys and more with API tokens.',
            'steps' => [
                ['Create a token', 'Account → API tokens → Create a token. Choose only the abilities it needs and an expiry date. The token is shown once, so copy it straight away.'],
                ['Call the API', 'Send it as a bearer token. The API reference lists every endpoint, and the OpenAPI document can generate a client for you.'],
                ['Old scripts', 'Deployer API v1 scripts keep working unchanged, including old numeric IDs.'],
                ['Spreadsheets', 'Servers, Websites, Repositories, Account → Providers and Account → Recipes each have Export CSV: the inventory as a spreadsheet, with what you can see and never any secrets.'],
                ['Resources', 'The resources API (/api/v2) creates, reads, changes and deletes projects (with their services), servers, websites and monitors. Servers and websites answer at once and set up in the background; read them until their status is active or failed.'],
                ['Terraform', 'The BuildPusher Terraform provider manages projects, servers, websites and monitors as code with the resources API. Give its token projects, infrastructure and monitoring read and write scopes, set BUILDPUSHER_TOKEN, and declare buildpusher_project, buildpusher_server, buildpusher_website and buildpusher_monitor resources; existing ones can be imported by ID.'],
            ],
        ],
        'agencies' => [
            'group' => 'platform',
            'title' => 'Run client work (agencies)',
            'summary' => 'Your branding on what clients see, a monthly report for each client, and costs passed on with your markup.',
            'steps' => [
                ['White label', 'Account → Clients → White label. Set your name, an HTTPS logo and a colour; status pages, shared Analytics reports and client reports then show them instead of ours, without “Powered by”. It comes with the Deploy Team plan and above.'],
                ['Add clients', 'Add a client with the projects you run for them, who gets their report and your markup on costs. Preview last month’s report from the client’s card.'],
                ['Monthly reports', 'On the 1st, each client gets last month’s uptime, incidents, releases and visitors for their projects, with what they cost including your markup, sent in your name.'],
                ['Pass costs on', 'Download costs by client gives a CSV of each client’s projects with your plan share and server costs, marked up, ready for your invoices.'],
                ['Give clients access', 'To let a client look around, invite them as a Viewer on the Members page and limit them to their projects.'],
            ],
        ],
        'assistant' => [
            'group' => 'platform',
            'title' => 'Ask the assistant',
            'summary' => 'Ask about deploys, errors, checks, incidents, Analytics and servers in plain language, in the app or from your AI tools.',
            'steps' => [
                ['Ask in the app', 'Open Ask from the account menu and type a question, such as “why did errors go up after the last deploy?” or “which pages lost visitors this week?”. It looks at your deploys and their before-and-after numbers, error issues, uptime checks, incidents, Analytics and servers, and answers with the figures it used. Ask follow-ups in the same conversation; conversations are kept for 30 days.'],
                ['What it can see', 'Only what you can see yourself: projects you can open and services your membership includes. It reads; it never changes anything.'],
                ['From your AI tools', 'Connect Claude, Cursor or another tool that speaks the Model Context Protocol to the MCP address on the Ask page, with an API token (Account → API tokens) as the bearer token. Give the token the read scopes for what it should see: projects:read, deploy:read, monitoring:read, analytics:read and infrastructure:read.'],
                ['Limits', 'Each account can ask a set number of questions a day in the app. The MCP address follows the API’s rate limits.'],
            ],
        ],
        'webhooks' => [
            'group' => 'platform',
            'title' => 'Webhooks',
            'summary' => 'Send deploys, incidents, servers, backups, findings and billing changes to your own automation.',
            'steps' => [
                ['Add an endpoint', 'Account → Webhooks → Add an endpoint. Give a public HTTPS address and choose the events, or Everything to get new kinds of event as they’re added. The signing secret is shown once.'],
                ['What arrives', 'A POST with JSON: id, event (such as deploy.succeeded, incident.opened, server.ready, backup.failed, security.finding or billing.plan_changed), created_at, account_id and data about what happened.'],
                ['Check it came from us', 'X-BuildPusher-Signature is v1= followed by HMAC-SHA256 of the X-BuildPusher-Timestamp header, a dot and the raw body, using the secret. The Webhooks page has a code sample. Ignore repeats of an X-BuildPusher-Delivery ID you’ve already handled.'],
                ['Retries', 'Answer with any 2xx within 10 seconds. Otherwise the delivery is tried up to six times over about three hours; after 20 failed deliveries in a row the endpoint is paused until you turn it back on. Send a test and Send again are on the same page, with the last deliveries’ results.'],
            ],
        ],
        'project-domains' => [
            'group' => 'platform',
            'title' => 'Claim your project’s domains',
            'summary' => 'Add the hostnames a project serves and verify them, so no other account can claim them.',
            'steps' => [
                ['Add a domain', 'Open the project’s Domains page (under the project’s name in the sidebar) and choose Add a domain. Enter the hostname, such as shop.example.com, and optionally the environment it belongs to.'],
                ['Verify it', 'Add the TXT record shown, with its name and value, at your DNS provider, then choose Check DNS. Once it’s found, the domain is marked Verified and no other account can claim it.'],
                ['Keep track', 'Each domain shows when it was verified and last checked. Add www and the bare domain separately if you serve both.'],
                ['Remove one', 'Removing a domain means the project stops claiming it, and its services stop serving it.'],
            ],
        ],
        'your-data' => [
            'group' => 'platform',
            'title' => 'Download or delete your data',
            'summary' => 'Get a copy of what we hold about you, or delete your user account.',
            'steps' => [
                ['Download your data', 'Your settings → Privacy → Download my data gives a JSON file with your profile, accounts and roles, sign-in methods (never secrets), API token names, sign-in history and your activity. Project and service data is exported per account, for example with Export CSV and the API.'],
                ['Delete your account', 'On the same page, Delete my user account signs you out everywhere and erases your sign-in methods, history and API tokens. It can’t be undone.'],
                ['Accounts you share', 'Accounts where you’re the only member are deleted with you. You leave accounts other people use, and they keep working. If you’re the only owner of an account others use, make someone else an owner first.'],
            ],
        ],
        'connect-a-provider' => [
            'group' => 'infrastructure',
            'title' => 'Connect a cloud provider',
            'summary' => 'Let BuildPusher create servers in your DigitalOcean, Hetzner Cloud, Vultr, Linode, AWS (Lightsail or EC2), Google Compute Engine, Azure, OVHcloud, Scaleway or UpCloud account.',
            'steps' => [
                ['Create a token at the provider', 'In your provider’s dashboard, create an API token with read and write access.'],
                ['Add it here', 'Account → Providers → Connect a provider. Choose the provider, paste the token and save. We check it straight away. You can also connect one without leaving the page you’re on: the new server form, a new repository and Start from a template each offer Connect a provider, and pick it up once it’s saved.'],
                ['Credentials that aren’t one token', 'AWS Lightsail takes an access key as ACCESS_KEY_ID:SECRET_ACCESS_KEY. Scaleway takes the project ID and an API secret key as PROJECT_ID:SECRET_KEY; servers go in that project and its SSH keys are added to them. UpCloud takes an API user (Account → People, with API access) as USERNAME:PASSWORD. Scaleway, UpCloud and OVHcloud prices are shown in euros.'],
                ['AWS EC2, Google Cloud and Azure', 'AWS EC2 takes an access key as ACCESS_KEY_ID:SECRET_ACCESS_KEY for an IAM user allowed EC2 actions; servers go in the region’s default VPC with a “buildpusher” security group for SSH, HTTP and HTTPS. Google Compute Engine takes a service account’s JSON key (paste the whole file) with the Compute Instance Admin and Compute Security Admin roles; servers go in that project’s default network. Azure takes a service principal with Contributor on the subscription as TENANT_ID:CLIENT_ID:SUBSCRIPTION_ID:CLIENT_SECRET; each server gets its own resource group, removed with the server. Prices shown are on-demand list prices in us-east-1, us-central1 or East US; Costs shows what AWS actually charged.'],
                ['OVHcloud', 'Create an API application and a consumer key allowed GET, POST and DELETE on /cloud/project/*, then enter ENDPOINT:APPLICATION_KEY:APPLICATION_SECRET:CONSUMER_KEY:PROJECT_ID, with eu or ca as the endpoint and your Public Cloud project’s ID. Instances are billed by the hour.'],
                ['GitHub App', 'Where the GitHub App is available, choose Install the GitHub App on Account → Providers and pick the repositories it may reach. Its repositories are listed for you to connect, pushes deploy without a webhook to set up, and previews get a check run and a comment on the pull request.'],
                ['Source control and DNS', 'GitHub, GitLab, Bitbucket and DNS providers (Cloudflare, Hetzner DNS and AWS Route 53, whose credential is ACCESS_KEY_ID:SECRET) are added the same way, from the same page. A DigitalOcean provider manages DigitalOcean DNS too.'],
            ],
        ],
        'create-a-server' => [
            'group' => 'infrastructure',
            'title' => 'Create a server',
            'summary' => 'Provision a server in your cloud account and follow its setup live.',
            'steps' => [
                ['Start', 'In your project, go to Infrastructure → Servers → Create server. It opens beside the page you’re on.'],
                ['Choose what it’s for', 'Pick a provider, the server type (an app server runs PHP, Node, Caddy, MySQL and Redis together), a region and a size. Add recipes to run your own scripts once it’s set up.'],
                ['Watch it come up', 'The server page follows setup live: first waiting for the provider to give it an address, then each installation step. It usually takes a few minutes.'],
                ['Already have a server?', 'Choose Import a server to bring in an Ubuntu server over SSH instead; we check it before managing it.'],
            ],
        ],
        'add-a-website' => [
            'group' => 'infrastructure',
            'title' => 'Add a website',
            'summary' => 'Host a website on a server, with a domain, TLS and a database.',
            'steps' => [
                ['Create it', 'Infrastructure → Websites → Create website. Choose the server and the website’s main domain.'],
                ['Already running?', 'Import a website adopts an application already in /var/www on one of your app servers. Its files, Caddy site and database are left as they are.'],
                ['Point the domain', 'Point the domain’s DNS at the server’s IP address, or choose a DNS provider (Cloudflare, DigitalOcean, Hetzner DNS or Route 53) and we’ll create the record in its zone. A certificate is issued automatically.'],
                ['Aliases and redirects', 'Add more domains on the website’s page, as aliases or as redirects to the main one.'],
                ['Database', 'App-server websites get their own MySQL database. On the Database tab you can inspect it, add users that expire, and copy data from another website.'],
                ['Heal it automatically', 'With the health check on, tick Heal it automatically: when the check fails, BuildPusher restarts Caddy, PHP-FPM or the website’s workers if any have stopped (or reloads them when all are running), at most three times an hour, and notes what it did on the incident.'],
            ],
        ],
        'server-tasks' => [
            'group' => 'infrastructure',
            'title' => 'Cron jobs, processes, firewall and services',
            'summary' => 'Schedule commands, keep workers running, open ports and install search or cache on a server.',
            'steps' => [
                ['Cron jobs', 'On the server’s Processes & cron tab, add a command and a schedule (or pick a preset such as every minute). It runs as the server’s user.'],
                ['Processes', 'The same tab keeps commands running and restarts them if they stop: queue workers, Horizon, Reverb, Pulse or your own. Restart one after a deploy from its row.'],
                ['Firewall', 'The Network tab opens or closes ports, for everyone or only some addresses. Turn on Private network there to let your other servers in the same region connect.'],
                ['Services', 'The Services tab installs Meilisearch, Typesense or Redis, listening on the server only or on the private network. Its address and key are shown once it’s running.'],
            ],
        ],
        'website-tools' => [
            'group' => 'infrastructure',
            'title' => 'Web server, files, logs and CDN',
            'summary' => 'Adjust how a website is served, look at its files and logs, and put it behind a CDN.',
            'steps' => [
                ['Web server settings', 'On the website’s Settings tab, add your own Caddy settings under Web server (Caddy). They’re checked first, and the previous settings come back if they’re invalid.'],
                ['WebSockets', 'Under WebSockets (Laravel Reverb) on the Settings tab, set up Reverb in one step: it runs as a process and the web server forwards its traffic.'],
                ['Files and logs', 'The Files tab lets you browse the website’s files, follow the end of a log, and search the logs for a phrase.'],
                ['CDN and firewall', 'On the Domains tab, choose CDN and firewall on a domain to serve it through Cloudflare, block countries or addresses, and rate-limit requests. The cache is cleared after every deploy.'],
                ['Slow queries and tuning', 'The Database tab shows the week’s slowest queries on the website’s database (with values replaced by ?, so repeats group together) once the slow query log is on; choose Turn on the slow query log to start it (queries over a second, for the whole MySQL server). It also suggests settings to change: the InnoDB buffer pool, temporary tables written to disk, connections near the limit and joins without indexes.'],
            ],
        ],
        'commands-and-terminal' => [
            'group' => 'infrastructure',
            'title' => 'Run commands and open a terminal',
            'summary' => 'Run a one-off command on a server, or open a root shell in your browser to troubleshoot.',
            'steps' => [
                ['Run a command', 'On the server’s page, choose Run a command. It runs as root, one at a time, and times out after the limit shown. The output is stored encrypted and kept for 180 days.'],
                ['Look back', 'Command history on the server’s page lists every command with its status, exit code and output. Run again repeats one, and Export CSV downloads the history.'],
                ['Open a terminal', 'Choose Open terminal for a root shell on the server in your browser. It closes after 10 idle minutes, or 30 minutes at most, and opening and closing it are recorded in the audit log.'],
                ['Who can', 'People who can manage the server can run commands and open a terminal. The terminal needs the server’s host key to be known, so it’s available once the server is set up.'],
            ],
        ],
        'recipes' => [
            'group' => 'infrastructure',
            'title' => 'Recipes and the recipe gallery',
            'summary' => 'Your own scripts for new servers, and ready-made ones other accounts have shared.',
            'steps' => [
                ['Write a recipe', 'Account → Recipes → New recipe. Give it a name, what it does and a Bash script. It runs as root at the end of a new server’s provisioning, so make it safe to run once on a fresh Ubuntu server.'],
                ['Use it', 'Tick recipes when you create a server; they run in the order shown, and the server keeps the version it ran. Recipes for the servers an environment deploys to are on the environment’s Recipes tab.'],
                ['History', 'Each save keeps a revision, so you can see what changed and who changed it. Make a copy to start a variation.'],
                ['The gallery', 'The recipe gallery has recipes other accounts have published. Read a script before you install it: it runs as root on your servers. Install one into your account, rate it, mark favourites, or report a harmful, broken or spam recipe to its publisher.'],
                ['Share yours', 'Owners and admins can publish a recipe to the gallery or take it out again. When the gallery has a newer version of one you installed, choose Update from the gallery; your current version stays in the history.'],
            ],
        ],
        'storage-buckets' => [
            'group' => 'infrastructure',
            'title' => 'Storage buckets',
            'summary' => 'Object storage for your apps, from S3, Spaces, R2, Google Cloud Storage and others.',
            'steps' => [
                ['Add a bucket', 'Infrastructure → Storage → Add a bucket. Create a new one or connect an existing bucket with its access key.'],
                ['Use it in an app', 'Attach the bucket to an environment and its details are added as environment variables (the usual AWS_ names), ready for Laravel’s s3 disk.'],
            ],
        ],
        'move-from-forge-or-ploi' => [
            'group' => 'infrastructure',
            'title' => 'Move from Forge or Ploi',
            'summary' => 'Read your servers and sites from Laravel Forge or Ploi and recreate them here, one site at a time.',
            'steps' => [
                ['Connect', 'Infrastructure → Servers → Move from Forge or Ploi. Paste an API token from Forge (Account → API tokens) or Ploi (Profile → API keys). It’s only read from, and stored encrypted; Forget the token removes it and everything read.'],
                ['What’s read', 'Each server’s sites with their domain, repository, branch, PHP version, environment file and deploy script, and the server’s cron jobs and daemons.'],
                ['Move a site', 'Choose one of your servers here and Move. A website is created for the domain with the same environment file, and the cron jobs and daemons that run in the site’s directory are added to the new server, pointed at the new directory and run as its user. Any that don’t fit, such as an unusual schedule, are listed for you to add yourself.'],
                ['Finish', 'Connect the repository in Deploy and deploy once, copy the database and uploaded files across, then point DNS at the new server. Nothing changes in Forge or Ploi, so the old site keeps serving until DNS moves.'],
            ],
        ],
        'costs' => [
            'group' => 'infrastructure',
            'title' => 'Costs and right-sizing',
            'summary' => 'See what your servers cost and what your providers billed, set a budget, and size them to what they actually use.',
            'steps' => [
                ['Costs', 'Infrastructure → Costs lists each server’s monthly price from your provider, its recent CPU and the projects on it, with totals.'],
                ['Actual bills', 'For DigitalOcean, Vultr, Linode, Lightsail and EC2 credentials, Costs also shows what the provider actually charged: last month’s invoice beside the estimate from list prices, and this month so far. They’re read daily, or when you choose Check prices now. The credential needs billing read access (for Lightsail and EC2, an AWS key allowed ce:GetCostAndUsage); if it hasn’t, Costs says so. Invoices cover everything in the provider account, such as bandwidth, volumes and backups, so they’re usually above the estimate. Hetzner has no billing API.'],
                ['Budget', 'Set a monthly budget there to be told when your servers go over it.'],
                ['Snapshots', 'On a server’s Settings tab, tick Snapshot before risky changes (DigitalOcean, Hetzner, Vultr, Linode, Lightsail, EC2, Compute Engine and Azure servers). A provider snapshot is then taken before updates are installed, security fixes run or Node.js changes, and the three newest are kept; restore one from your provider’s dashboard if a change goes wrong. Take a snapshot now takes one straight away. Your provider charges for the storage.'],
                ['Disk clean-up', 'On a server’s Overview tab, under Diagnostics, choose Measure the disk to see how much space old releases, old logs, package caches, unused Docker images and old temporary files take, then Clear any of them. The live release and the releases each website keeps stay, and logs from the last two weeks stay.'],
                ['Right-sizing', 'Once a server has a few days of readings, Costs suggests a smaller size when even its busiest 5% of the time leaves most of it idle (with the monthly saving), or a bigger one when it runs hot. Suggestions keep headroom: at most 60% CPU and 70% memory at the same load. Resize in your provider’s dashboard.'],
            ],
        ],
        'backups' => [
            'group' => 'infrastructure',
            'title' => 'Back up and restore',
            'summary' => 'Scheduled, verified backups to your own storage.',
            'steps' => [
                ['Add a destination', 'Infrastructure → Backups → Add destination. Give S3-compatible storage you own (a bucket, its endpoint and keys); we check we can write to it before saving. Each website gets its own encrypted restic repository there.'],
                ['Schedule backups', 'On the website’s Backups tab, choose Schedule backups: how often, the time (UTC) and how many snapshots to keep. Each backup holds the database, the .env file and shared storage, and is checked after it’s written. Back up now takes one straight away.'],
                ['Restore', 'Choose Restore on a backup in the website’s Backups tab. The website is in maintenance mode meanwhile, and put back as it was if any step fails. Infrastructure → Backups lists recent backups across the project.'],
                ['A second copy', 'When scheduling backups, choose Also copy to for a second destination (another provider or region). Each backup is sent there too, for a 3-2-1 setup; the backup list shows whether the second copy was made.'],
                ['Restore drills', 'Leave Monthly restore drill ticked and, once a month, the latest backup is restored into a scratch area on the server and checked (the database loads and the app starts), then cleaned up. If it fails, the account’s owners are emailed.'],
            ],
        ],
        'read-replicas' => [
            'group' => 'infrastructure',
            'title' => 'Add a read replica',
            'summary' => 'Copy a database server continuously to another one that serves reads, and promote it if the primary fails.',
            'steps' => [
                ['Create the replica server', 'Create another database server with the same engine (MySQL or PostgreSQL), ideally with the same provider and region so the copy uses the private network. Anything already on it is moved aside.'],
                ['Add it', 'Open the primary database server → Database tab, choose the new server under Add a read replica, and type its name to confirm. The primary gets a replication login for that server only and opens its database port to it; the replica takes a full copy and then follows every change.'],
                ['Send reads to it', 'Once the replica shows Streaming, point read-only queries and reports at it. In Laravel, the Database tab shows the read and write hosts to put in config/database.php.'],
                ['Watch the lag', 'Every five minutes the replica is checked and the tab shows how many seconds it’s behind. If it stops copying, the account’s owners are emailed with the reason.'],
                ['Promote it', 'If the primary fails, open the replica → Database tab → Promote to a standalone server. It stops following the primary and accepts writes, keeping everything copied; then point your applications at it.'],
            ],
        ],
        'load-balancers' => [
            'group' => 'infrastructure',
            'title' => 'Load balancers',
            'summary' => 'Spread a hostname’s traffic across app servers, skipping any that fail a health check.',
            'steps' => [
                ['Create the proxy server', 'Create a server of the Load balancer type. Load balancers come with the Business Deploy plan and above.'],
                ['Add a load balancer', 'Infrastructure → Load balancers → Add load balancer. Choose the proxy server, the hostname, a health check path and, optionally, the website it serves. Point the hostname’s DNS at the proxy server; Caddy gets its certificate.'],
                ['Add nodes', 'Add a node for each app server, with its port and a weight. Traffic is shared by weight, and nodes are reached over HTTP on their public address. Until there are nodes, visitors get a 503 page.'],
                ['Take one out', 'Take out removes a node from rotation, for maintenance for example; Put back returns it. Nodes that fail the health check are skipped on their own.'],
            ],
        ],
        'deploy-from-git' => [
            'group' => 'deploy',
            'title' => 'Deploy from Git',
            'summary' => 'Connect a repository and deploy it to a website on every push.',
            'steps' => [
                ['Connect the repository', 'Deploy → Repositories → Connect a repository. Choose the provider, the repository and branch, the environment, and the website it deploys to.'],
                ['Set up the build', 'Add your build commands under Build and filters, and the environment’s variables (see Environments and variables). The repository’s Settings tab has the build cache and build settings for later.'],
                ['Pipelines', 'Deploy → Pipelines chains repositories, such as the API and then the frontend. Choose Run: the first deploys, each next one starts only once the one before is live, and the run stops if a deploy fails, is rejected or is cancelled. Each step deploys its branch’s latest commit, with the usual approvals and checks.'],
                ['Monorepos', 'For one app in a larger repository, set Subdirectory to its folder (such as apps/api), and under Push deploys only for these paths list its folder (apps/api/**) plus anything it shares (packages/**). A push that changes nothing there doesn’t deploy it; connect each app in the repository the same way.'],
                ['Deploy', 'Deploy from the repository page (now, a chosen version, or later), or set up the Push deploys tab so every push to the branch deploys. Each deploy is a new release, and the previous ones are kept.'],
                ['Follow it', 'The deploy page shows each step’s log as it runs, and the release is marked in Monitoring and Analytics once it’s live.'],
            ],
        ],
        'use-the-cli' => [
            'group' => 'deploy',
            'title' => 'Deploy from the command line',
            'summary' => 'Deploy, follow logs and roll back from your terminal or CI with the BuildPusher CLI.',
            'steps' => [
                ['Install it', 'Run curl -fsSL https://buildpusher.com/cli/install.sh | sh. It’s one PHP file, so it needs PHP 8.1 or later.'],
                ['Log in', 'Create an API token with the Deploy scopes under Account → API tokens, then run buildpusher login and paste it. In CI, set BUILDPUSHER_TOKEN instead.'],
                ['Deploy', 'Run buildpusher deploy <project> [environment] --wait to deploy and follow the log; add --ref=v1.4.0 to deploy a tag, branch or commit. It exits non-zero if the deploy fails, so CI jobs fail with it.'],
                ['Follow and undo', 'buildpusher status lists recent deploys, buildpusher logs <id> --follow streams one, and buildpusher rollback <id> goes back to the release a deploy shipped.'],
                ['Set defaults', 'Put {"project": "shop", "environment": "staging"} in .buildpusher.json at the root of your repository to leave them off each command.'],
                ['In GitHub Actions or code', 'Deploy from a workflow with the BuildPusher GitHub Action (buildpusher/deploy-action), which waits for the result, fails the job if the deploy fails, and comments the result on the pull request; or from your own code with the PHP (buildpusher/sdk) and JavaScript (@buildpusher/sdk) SDKs.'],
            ],
        ],
        'environments-and-variables' => [
            'group' => 'deploy',
            'title' => 'Environments and variables',
            'summary' => 'Configure each environment: variables, workers, how deploys run, and recipes.',
            'steps' => [
                ['Open the environment', 'Deploy → Environments, then choose one, such as production or staging.'],
                ['Clone one', 'Project settings → Environments: name the new environment, pick one under Copy settings from and choose Clone. Its deploy settings, workers, recipes and variables come across, and its schedules come across switched off. Secret values are copied only if you tick Copy secret values too; otherwise you’re told which secrets to set. Connect a repository to a website for it to deploy.'],
                ['Variables', 'On the Variables tab, add environment variables and secrets. They’re encrypted, and previews never inherit them.'],
                ['From a password manager', 'Under Secrets from a password manager, connect Doppler (a service token for the config), 1Password Connect (your Connect server’s https address, a token, and the vault and item IDs; each field’s label becomes the variable name) or AWS Secrets Manager (a region, an access key that can read the secret, and its name; the secret’s value must be a JSON object). They sync every hour or when you choose Sync now, as secret variables for runtime and build. Variables set here by hand are never overwritten, and keys removed from the source are removed here.'],
                ['How deploys run', 'On the environment’s Settings tab, under How deploys run, choose the strategy (atomic, rolling, blue-green or canary). Approvals, deploy locks, weekly windows and freezes are on the Controls tab.'],
                ['Build server', 'On the Settings tab, under Build server, choose one of your app or worker servers and one of the project’s storage buckets. Deploys then clone, install dependencies and build there, and upload the built release to the bucket through a link that expires; the website’s server downloads it, unpacks it and runs the rest (environment file, migrations, going live). The bucket’s keys never reach either server, and each release is deleted from the bucket when its deploy finishes. The build server needs the same PHP and Node.js versions as the website’s. Docker and Compose deploys keep building on the website’s server.'],
                ['Destructive migrations', 'Tick Stop before destructive migrations on the environment’s Settings tab. Before migrating, a Laravel deploy lists the SQL its pending migrations would run (with migrate --pretend, which changes nothing) and stops if any of it drops, truncates or renames. The deploy page shows the statements; someone other than the person who deployed can approve them, and the same revision deploys again and migrates.'],
                ['Approve from Slack', 'On the environment’s Notifications tab, tick Needs approval for a Slack (or Teams) destination. Each deploy that needs approval arrives with Approve and Reject buttons; they open the deploy with that choice ready, so one more tap confirms it. Only people who can approve deploys, other than whoever started it, can confirm.'],
                ['Release analysis', 'On the Settings tab, under Watch health after each deploy, choose how long to watch, then the limits: failed requests, how much slower requests may get, and how far the Analytics conversion rate may drop. Each deploy is compared with the same length of time before it; past a limit, it’s marked failed and, with automatic rollback on, the previous release goes back live. The build page shows the before-and-after figures.'],
                ['Docker Compose', 'Choose the Docker Compose runtime on the Settings tab, give the Compose file (compose.yaml by default), the service that serves the website and its container port. Each deploy builds and starts the stack on your server as one project; the web service gets the website’s .env and sits behind Caddy with HTTPS, other services (a database, a worker) run beside it, and named volumes are kept between deploys.'],
                ['Resources', 'The Resources tab adds the databases, caches and other services the environment uses. A managed one is set up for you (MySQL uses the website’s database; Redis and Valkey run on the server); for an external one, enter its variables. Either way they go into .env.'],
                ['Workers and recipes', 'Run queue workers and schedulers from the Workers tab, and scripts on the environment’s servers from the Recipes tab.'],
            ],
        ],
        'scaling-and-maintenance' => [
            'group' => 'deploy',
            'title' => 'Autoscaling, maintenance mode and regions',
            'summary' => 'Scale with demand, take the site down for planned work, and see where it runs.',
            'steps' => [
                ['Autoscale', 'On the environment’s Settings tab, tick Scale automatically and set a target CPU. Replicas are added and removed within the minimum and maximum you set. Set Waiting jobs per replica too, and replicas are added when the environment’s queue monitors report a backlog, even while CPU is low.'],
                ['On a schedule', 'The Automation tab has scaling schedules (more replicas for a known busy time), scheduled deploys and scheduled tasks.'],
                ['Waking from hibernation', 'Turn on Hibernation on the Automation tab for an environment that can sleep when nobody uses it. A hibernating website wakes on its first request: its server tells BuildPusher straight away, and workers start again within seconds.'],
                ['Maintenance mode', 'On the Automation tab, choose Turn on maintenance mode. Visitors see a “back soon” page; open the secret path shown there once to get in yourself. It stays on through deploys until you turn it off.'],
                ['Regions', 'The Controls tab lists every website the environment deploys to and its region. To run in another region, add a website on a server there and connect the repository to it.'],
            ],
        ],
        'previews' => [
            'group' => 'deploy',
            'title' => 'Preview pull requests',
            'summary' => 'Give every pull request its own running copy.',
            'steps' => [
                ['Turn previews on', 'On the repository’s Settings tab, turn on pull-request previews. Each new pull request gets its own website and environment.'],
                ['Share it', 'GitHub App repositories get a check run and a comment with the preview’s address.'],
                ['Secrets', 'Previews start without secrets; approve the ones a preview needs for its exact revision.'],
                ['Start with data', 'On the repository’s Settings tab, choose a website to copy the database from, and each preview starts with a copy of it: everything, a quick branch with the first 1,000 rows of each table (best for big databases), or the schema only for your seeders to fill. Tick Mask personal data to replace emails, names, phone numbers, addresses, IP addresses and dates of birth in each copy.'],
                ['Clean-up', 'A preview is removed when its pull request is closed or merged.'],
                ['Any branch', 'On Deploy → Previews, use Preview a branch to open one for any branch, not only a pull request, and choose when it closes (1 to 30 days). It deploys the branch’s latest commit; open it again to deploy newer commits or move the date.'],
            ],
        ],
        'rollback-and-promotion' => [
            'group' => 'deploy',
            'title' => 'Roll back, compare and promote',
            'summary' => 'Go back to a known release, see what changed, and move a tested build forward.',
            'steps' => [
                ['Roll back', 'On any earlier successful build, choose Roll back. The previous release is switched back in seconds.'],
                ['Compare', 'Choose Compare on a build to see the commits and settings that changed since another build.'],
                ['Release notes', 'Each deploy lists the commits since the last live release as release notes: feat:, fix: and perf: commits are grouped (use conventional commit prefixes for the best notes), and chores, CI, docs, tests and merges are left out. They’re on the deploy’s page and in Deploy live notifications to Slack and Discord. To publish them, choose Publish release notes on the environment’s Automation tab; the public page shows only the notes, not who wrote them.'],
                ['Promote', 'Promote a build that passed in staging to production; it keeps its history.'],
            ],
        ],
        'configuration-as-code' => [
            'group' => 'deploy',
            'title' => 'Configuration as code',
            'summary' => 'Describe environments in YAML, see exactly what would change, and apply it as a review.',
            'steps' => [
                ['Write the document', 'Deploy → Configuration. Write a version 2 YAML document (the same format as Deployer). Names in placements, repositories and secret references are bound to records under Bindings: websites, this project’s repositories and secret variables.'],
                ['Plan', 'Choose Plan changes to see exactly what applying the document would change. Nothing changes yet, and objects the document doesn’t mention are left alone.'],
                ['Review and apply', 'Choose Create review. A review lasts 15 minutes and only its creator can apply it, as long as nothing has changed since. Applying gives a receipt that follows its deploys.'],
                ['Taking objects over', 'Objects that already exist but aren’t owned by configuration need adopt: true in the document; plan again after adding it.'],
                ['Workflows', 'Under Workflow (version 1), paste Deployer’s workflow format to set scheduled deploys, scaling, scaling schedules and processes per environment all at once. The same document can be sent to PUT /api/v1/projects/{project}/workflow.'],
            ],
        ],
        'monitor-uptime' => [
            'group' => 'monitoring',
            'title' => 'Monitor uptime',
            'summary' => 'Check your sites and jobs, and get told when something breaks.',
            'steps' => [
                ['Add a monitor', 'Monitoring → Monitors → Add a monitor. Choose HTTP, DNS, TLS, TCP, a multi-step check, a heartbeat for scheduled jobs, or a queue.'],
                ['Multi-step checks', 'A multi-step check follows a flow such as signing in or checking out: up to 10 requests in order, sharing cookies, following redirects, checking each status and text, and carrying values like a CSRF token from one step to the next with extract and {{name}}. The steps are stored encrypted; use a dedicated test account. It checks over HTTP, so pages that only work with JavaScript need an API step instead.'],
                ['Choose where alerts go', 'Monitoring → Alerts → Destinations → Add destination. Add email, push notifications, Slack, Microsoft Teams, PagerDuty, Discord or a webhook.'],
                ['Alerts on your phone', 'In your settings, under Notifications → Push notifications, choose Turn on for this device (on iPhone and iPad, add BuildPusher to your Home Screen first and do it from there). Then add a Push notification destination for yourself or for whoever is on call. Alerts arrive even when BuildPusher isn’t open; tap one to open the incident.'],
                ['Planned work', 'Choose Maintenance on the Monitors page (or Monitoring → Alerts → Maintenance) and add a window before planned work, so expected downtime doesn’t open an incident.'],
                ['Services you depend on', 'Under Services you depend on, follow GitHub, Cloudflare, DigitalOcean, Twilio and others, or any status page built on Atlassian Statuspage. Their status is checked every five minutes and shown beside your monitors, with the affected components and the provider’s incident.'],
            ],
        ],
        'send-telemetry' => [
            'group' => 'monitoring',
            'title' => 'Send errors, traces and metrics',
            'summary' => 'Instrument your application so problems point at the release that caused them.',
            'steps' => [
                ['Get a key', 'Monitoring → Setup → Ingest keys → Create key, for the environment. The checklist on the same page tracks your first event, monitor, alert destination and release.'],
                ['Server logs', 'On a server’s Logs tab, under Send logs to Monitoring, choose an environment. A small agent then sends the server’s system warnings and errors, and its websites’ Laravel warnings and errors with stack traces, to Monitoring → Events (type log), where you can search them and set alert rules on matching lines. It sends up to 600 lines a minute and uses its own key, revoked when you stop.'],
                ['Tickets', 'Monitoring → Setup → Ticket trackers: connect GitHub Issues (a repository and a fine-grained token that can write issues), Linear (an API key and the team ID) or Jira Cloud (your atlassian.net site, email, API token and project key). Then choose Create ticket on any issue; the ticket gets the error, where it happened, how often, and a link back, and the issue links to it. When the ticket is closed (completed in Linear, done in Jira), the issue is resolved within the hour; if the error happens again, it reopens.'],
                ['Laravel', 'For Laravel apps, composer require buildpusher/laravel and set BUILDPUSHER_TOKEN. Each request is recorded with a timeline of its queries, mail and notifications and its cache hits and misses; exceptions carry a hashed user ID so issues count the people affected; slow queries and N+1 queries (the same query five or more times in a request) are flagged; queue jobs, scheduled tasks, commands and warning-level logs are recorded too. php artisan buildpusher:deploy marks each release.'],
                ['Send data', 'Use the SDK snippet on the setup page, or send OpenTelemetry traces, logs and metrics to the OTLP endpoint shown there.'],
                ['Investigate', 'Errors are grouped into Issues; Events, Metrics and Traces let you dig in, and Releases show what changed.'],
                ['Browser errors', 'Monitoring → Setup → Browser errors. List the origins your pages are served from and turn it on, then add the script tag it shows to every page. JavaScript errors and unhandled promise rejections become issues from the “browser” service, with the browser, operating system and release. Query strings are dropped from page addresses.'],
                ['Link to deploys', 'Every trace shows the deploy that was live when it ran, and each deploy links to its requests and traces, so you can see what a release changed.'],
            ],
        ],
        'alert-rules' => [
            'group' => 'monitoring',
            'title' => 'Alert rules',
            'summary' => 'Open incidents from errors, latency, log lines, metrics and SLO burn, and keep alerts quiet enough to trust.',
            'steps' => [
                ['Add a rule', 'Monitoring → Alerts → Rules → New rule. Choose what it measures, the threshold and how many minutes it must hold, then where it notifies.'],
                ['Alerts from log lines', 'Choose “Matching log / event count”, enter text to match (such as “payment declined”), and a threshold: 1 alerts on the first matching line, a higher number when it appears too often.'],
                ['Error budget burn', 'Choose “SLO error-budget burn rate” and an objective. A burn rate of 1 uses the budget exactly over the objective’s period; alert at 2 or more to hear while there’s still budget left, not once it’s breached.'],
                ['Anomalies', 'Choose “Metric anomaly score” to be told when a metric moves far from its usual range, without picking a fixed threshold.'],
                ['Keep it quiet', 'Monitoring → Alerts → Noise ranks the rules and monitors that fired most in the last 30 days, with how often they flapped (recovered within five minutes, unacknowledged) and how often nobody acknowledged them, and suggests how to tune each.'],
            ],
        ],
        'on-call' => [
            'group' => 'monitoring',
            'title' => 'On-call schedules',
            'summary' => 'Decide who gets paged, by rotation, and cover for people who are away.',
            'steps' => [
                ['Add a schedule', 'Monitoring → Alerts → On-call → Add a schedule. Choose how long each turn lasts (a week or a day), when it hands over, the time zone, when the first turn starts, and who takes turns, in order.'],
                ['Page whoever is on call', 'Add an email or push notification destination (Monitoring → Alerts → Destinations) and choose the schedule as its recipient. Alerts then go to whoever is on call when they fire.'],
                ['Cover for someone', 'On the schedule, put someone else on call for a while, such as while the person whose turn it is is away. The schedule goes back to its rotation afterwards.'],
            ],
        ],
        'incidents-and-status-pages' => [
            'group' => 'monitoring',
            'title' => 'Incidents and status pages',
            'summary' => 'Respond to problems and keep your users informed.',
            'steps' => [
                ['Respond', 'Monitoring → Incidents. Acknowledge, assign, and add notes; the timeline records it all.'],
                ['Escalate', 'Set escalation steps on an alert rule, so someone else is told if nobody responds. To page whoever’s turn it is, see On-call schedules.'],
                ['Post-mortems', 'On a resolved incident, choose Write a post-mortem. It starts as a draft built from the incident: how long it lasted, what the check or rule saw, who responded, your notes, and any deploys in the two hours before it opened as leads. Edit each section, save, and publish it to a status page if you like.'],
                ['Publish a status page', 'Monitoring → Status pages → New status page. Choose the monitors to show, post updates, and let people subscribe by email.'],
                ['Groups and reports', 'Give components a group (such as API or Website) to show them under a heading with the group’s worst status. Every month has a public uptime report (linked as Monthly uptime at the foot of the page) with each component’s uptime, the incidents and total downtime; tick Monthly uptime report to send it to subscribers on the 1st.'],
                ['Your own domain', 'Under Custom domain, enter a domain such as status.example.com, add the two DNS records shown (one proves it’s yours, one sends its visitors here) and check them. HTTPS is set up for you.'],
            ],
        ],
        'slos' => [
            'group' => 'monitoring',
            'title' => 'Service level objectives (SLOs)',
            'summary' => 'Promise how reliable a service is, and see how much room is left before you break it.',
            'steps' => [
                ['Add an objective', 'Monitoring → SLOs → New SLO. Choose the environment, then measure availability (which status codes count as good) or latency (how fast is fast enough, in milliseconds), the target and the rolling window. Optionally limit it to one service or route, such as /checkout.'],
                ['Read the error budget', 'The budget is the failures you can afford in the window: 99.9% over 30 days allows about 43 minutes of downtime. Each objective shows how much is left, and whether it’s healthy, running low or exhausted.'],
                ['Burn rate', 'A burn rate of 1 uses the budget exactly by the end of the window; 14 empties a 30-day budget in about two days. Add an alert rule on “SLO error-budget burn rate” (see Alert rules) to hear while there’s still budget left.'],
                ['When it’s gone', 'Slow down risky deploys and spend the time on reliability until the budget recovers.'],
            ],
        ],
        'dashboards' => [
            'group' => 'monitoring',
            'title' => 'Dashboards',
            'summary' => 'Bring telemetry, incidents, monitors and SLOs together on one page your team can share.',
            'steps' => [
                ['Add a dashboard', 'Monitoring → Metrics → New dashboard. Give it a name, a telemetry range and a description, and pick the widgets to show, in order.'],
                ['Widgets', 'Choose from requests and their duration and error rate with a trend, how much telemetry arrived by type, open incidents, monitor health, each SLO’s compliance and error budget, and when each project last sent telemetry.'],
                ['Across projects', 'Dashboards cover every project in the account, so one page can show everything you run. Your plan sets how many you can have.'],
            ],
        ],
        'security-basics' => [
            'group' => 'security',
            'title' => 'Get started with Security',
            'summary' => 'Turn on Security, read the findings and fix what matters first.',
            'steps' => [
                ['Turn it on', 'On the project’s overview, choose Turn on Security. Each check runs straight away, then as often as your plan allows (weekly on Free, daily on Pro, every six hours on Team).'],
                ['Read the overview', 'Security shows a score out of 100 and a grade, the checks and when they last ran, and the most serious open findings.'],
                ['Fix and confirm', 'Each finding says how to fix it. After fixing, choose Scan now on the check; the finding resolves when the scan no longer sees it.'],
                ['Ignore with a reason', 'For a false positive or an accepted risk, choose Ignore and say why. It stays ignored through later scans until someone reopens it.'],
                ['Domains and email', 'The domain check looks at every domain in the project: certificates, TLS versions, the redirect to HTTPS, security headers, SPF and DMARC, and CNAMEs left pointing at services that could be taken over.'],
            ],
        ],
        'security-code' => [
            'group' => 'security',
            'title' => 'Vulnerable packages, secrets and the deploy gate',
            'summary' => 'Find known vulnerabilities and leaked credentials in what you deploy, and stop risky deploys.',
            'steps' => [
                ['Vulnerable packages', 'Security reads the composer.lock and package-lock.json of each live website and checks every package against the OSV vulnerability database. Each finding names the version that fixes it. Development-only packages count one level lower.'],
                ['Leaked secrets', 'On Pro and above, Security looks for keys and tokens (AWS, Stripe, GitHub, Slack, private keys and more) in each website’s code and in recent error reports and logs, and for .env files committed with the code. Secrets are never stored or shown in full.'],
                ['Deploy gate', 'On the Security overview, choose Block deploys with for an environment. A deploy whose packages have a vulnerability at that level stops before it goes live, and the reason appears on the deploy.'],
                ['Accepting a risk', 'To let a deploy through anyway, ignore the finding in Security with a reason. The gate treats ignored findings as accepted.'],
            ],
        ],
        'security-servers' => [
            'group' => 'security',
            'title' => 'Harden and update servers',
            'summary' => 'See how each server is set up, fix problems in a click, and install security updates on a schedule.',
            'steps' => [
                ['What’s checked', 'On Pro and above, Security audits each server the project runs on: SSH passwords and root sign-in, the firewall and anything open to the internet (such as a database), fail2ban, automatic updates, waiting security updates, a pending reboot, and the Ubuntu release.'],
                ['Fix in a click', 'Findings with a fix have a button, such as Turn the firewall on or Allow SSH keys only. Fixes never remove BuildPusher’s own key access, and the server is checked again afterwards.'],
                ['Update windows', 'Security → Servers sets a weekly window (day and hour, in UTC) when each server installs its security updates, optionally rebooting if they need it. Install updates now runs them straight away.'],
            ],
        ],
        'security-firewall' => [
            'group' => 'security',
            'title' => 'Firewall, bots and attacks',
            'summary' => 'Cloudflare protection for your zones, and automatic blocking of attackers.',
            'steps' => [
                ['Zones', 'Security → Firewall lists the Cloudflare zones behind the project’s domains (their DNS must be managed at Cloudflare through BuildPusher).'],
                ['Security level and bots', 'On the Team plan, choose how suspicious a visitor must look before Cloudflare checks them, and turn on bot fight mode to challenge known bots and scrapers.'],
                ['Under attack', 'During an attack, turn on Under attack mode: every visitor gets a short check before reaching the site. Turn it off again afterwards.'],
                ['Per domain', 'Blocking countries or addresses and rate limits stay on each website’s Domains tab, under CDN and firewall.'],
                ['Automatic blocking', 'On Pro and above, Security checks each website’s access log every five minutes and blocks addresses in the server’s firewall after 20 failed sign-ins, 10 requests for known vulnerable paths (such as /.env) or 3,000 requests in ten minutes. Security → Attacks shows who’s blocked, lets you unblock someone, and sets how long blocks last and which addresses are never blocked.'],
            ],
        ],
        'security-access' => [
            'group' => 'security',
            'title' => 'SSH keys and access reviews',
            'summary' => 'Give people their own SSH access, and review who can reach the account.',
            'steps' => [
                ['Add your key', 'In Your settings → Security, add your SSH public key (the contents of your .pub file).'],
                ['Give access', 'On Pro and above, Security → Servers gives a member SSH access to a server as its deploy user, with the keys on their profile. When they change their keys, or leave the account, the server is updated.'],
                ['Review access', 'On the Team plan, Security → Access lists members (with two-factor status), API tokens and SSH access. Tick anything that should go and choose Complete review; the removals happen and the review is kept as evidence.'],
                ['Reminders', 'A finding appears when the last review is more than 90 days old, and for members without two-factor authentication and API tokens unused for 90 days.'],
            ],
        ],
        'security-compliance' => [
            'group' => 'security',
            'title' => 'Compliance evidence',
            'summary' => 'Download evidence for SOC 2, ISO 27001 and security questionnaires.',
            'steps' => [
                ['Download', 'On the Team plan, Security → Compliance downloads a ZIP covering the last 3, 6 or 12 months.'],
                ['What’s inside', 'Spreadsheets of members and two-factor status, API tokens, access reviews, every deploy with who asked and who approved, vulnerabilities and how each was handled, scans, patching, blocked attacks, backups and restore tests, incidents, and the audit log, with a README mapping each to the controls it supports.'],
                ['Keeping it complete', 'Review access every 90 days, fix or ignore findings with a reason, and keep backup verification on; each shows up in the next pack.'],
            ],
        ],
        'add-analytics' => [
            'group' => 'analytics',
            'title' => 'Add analytics to a website',
            'summary' => 'Count visitors without cookies, and measure the goals that matter.',
            'steps' => [
                ['Add the site', 'Analytics → Sites → Add a site, with the domain it runs on.'],
                ['Install the tracker', 'Copy the one-line script from the site’s page into your website’s head. Visits appear within a minute.'],
                ['Set goals', 'Analytics → Goals. Count visits to a page, or an event you send, as a conversion.'],
                ['Count more', 'Add data-outbound, data-downloads, data-vitals or data-not-found to the script for links, downloads, page speed and missing pages. Engagement (time on page and scroll depth) is counted automatically.'],
                ['Events without code', 'Give any button or link a class such as bp-event-name=Signup, and bp-event-plan=pro for a property; clicking it sends the event.'],
                ['Groups and searches', 'In the site’s settings, name groups of pages (such as Blog: /blog/*) to see them added up. Searches are read from ?q=, ?s= or ?search= (choose with data-search), and buildpusher.search(\'term\', 0) records a search that found nothing.'],
                ['Spam and bots', 'Known referrer spam, bots and ignored addresses are left out automatically; the site’s page says how many. Add your own spam domains in the site’s settings.'],
                ['Leave visits out', 'In the site’s settings, list addresses or networks to ignore (such as your office); their visits aren’t counted. Single-page apps that route with #/paths should add data-hash to the snippet.'],
                ['Custom properties', 'To break events down by your own details, list the property names in the site’s settings, then send them: window.buildpusher.track(\'signup\', {plan: \'pro\'}).'],
            ],
        ],
        'explore-analytics' => [
            'group' => 'analytics',
            'title' => 'Explore your traffic',
            'summary' => 'Choose any period, compare it, save segments, and dig into paths, retention and sales.',
            'steps' => [
                ['Pick a period', 'On the Analytics overview, choose a preset or set From and To dates, and compare with the previous period, the same period last year, or nothing.'],
                ['Filter and save', 'Click any page, channel, country, city, browser or campaign to filter by it, then save the filters as a view (a segment) to come back to.'],
                ['Explore', 'Analytics → Explore has Insights (the biggest changes), Paths (where people came from and went next), Properties, Items (e-commerce), Attribution, Clicks, Forms, Experiments and Retention.'],
                ['A/B tests', 'Start an experiment in Explore → Experiments with a key, its variants (the control first) and a goal. On the page, buildpusher.variant(\'key\', [\'control\', \'b\']) returns the variant to show and keeps it the same for the whole visit. Results show each variant’s conversion rate, lift over the control and whether it’s significant (p below 0.05); wait for a few hundred visitors per variant before deciding.'],
                ['Ad spend', 'On Analytics → Campaigns, choose Import ad spend and import a daily campaign report exported from Google Ads, Meta, LinkedIn or any ad platform as CSV (date, campaign and cost; source, currency, clicks and impressions if it has them). Each campaign then shows its cost, cost per conversion and return on ad spend. Campaign and source are matched to utm_campaign and utm_source, ignoring case; importing a day again replaces it.'],
                ['Straight from Google Ads and Meta', 'On Analytics → Campaigns, choose Connect Google Ads or Connect Meta Ads, sign in, and pick the ad account. Its last 30 days of spend per campaign are read straight away and again every morning, filed under the google or facebook source; Read now reads them at once. It only reads reporting, never changes your ads. Disconnecting keeps the spend already read.'],
                ['Attribution', 'Attribution credits goals and revenue to the channel or campaign that brought the converting visit (last touch) and that first brought the visitor (first touch; needs data-retention to look past one visit).'],
                ['Clicks and forms', 'Add data-clicks to the snippet for click maps, and data-forms for where people give up on forms. Only element descriptions, positions and field names are kept, never what people type.'],
                ['Retention', 'Add data-retention to the script to recognise returning browsers. It keeps a random ID in the browser, so ask for consent where the law requires it.'],
                ['Notes', 'Choose Add a note on the overview to mark a launch or outage on the chart.'],
            ],
        ],
        'funnels' => [
            'group' => 'analytics',
            'title' => 'Funnels',
            'summary' => 'See how many visitors take the steps you care about, in order, and where they drop off.',
            'steps' => [
                ['Add a funnel', 'Analytics → Funnels → Add a funnel. Funnels belong to a site, so pick the site at the top of the page first. Name the funnel after what visitors are trying to do, such as Checkout or Sign-up.'],
                ['Choose the steps', 'Add two to six steps. Each is a page (matching it exactly or by how its path starts) or a custom event you send.'],
                ['Read it', 'A visitor counts at a step once they’ve done every step before it, in order, over the last 30 days. Each step shows how many made it and the share who carried on; the hatched area is who dropped off, and the biggest drop is called out.'],
            ],
        ],
        'share-analytics' => [
            'group' => 'analytics',
            'title' => 'Reports, alerts and sharing',
            'summary' => 'Send regular reports and CSV exports, get told about spikes and unusual days, and share or embed a report.',
            'steps' => [
                ['Reports and alerts', 'On the site’s page, under Reports and alerts, add a weekly or monthly report, or a traffic spike alert, by email or to a Slack incoming webhook.'],
                ['Scheduled CSV exports', 'Save a view of the report with the filters you want (for example, only /pricing, or one campaign), then add a weekly or monthly CSV export and choose that view. The CSV arrives by email on Monday or the 1st, covering the week or month just gone.'],
                ['Unusual traffic alerts', 'An unusual traffic alert compares yesterday’s visitors and conversions with the same weekday over the last eight weeks, and tells you when one was far above or below normal. It needs four weeks of history and at least 20 visitors (or 5 conversions) on a typical day before it judges.'],
                ['Share', 'Under Share the report, create a read-only link, with a password if you like.'],
                ['View-only people', 'Under View-only access, invite someone by email; they get their own link to the report without joining the account, and you can remove it on its own.'],
                ['Embed', 'A link without a password comes with an iframe snippet to put the report on another page.'],
                ['Looker Studio', 'Download the connector (/connectors/looker-studio/Code.gs and appsscript.json), paste both into a new Apps Script project, deploy it as a community connector and open it in Looker Studio. Sign in with an API token that has analytics:read, enter the site ID and choose a breakdown. It reads the same daily rows as the API’s /analytics/sites/{site}/rows, which also suits spreadsheets and other dashboards.'],
                ['Export', 'Export a report as CSV from the overview, or read it through the API.'],
            ],
        ],
        'analytics-data' => [
            'group' => 'analytics',
            'title' => 'Import, export and your own domain',
            'summary' => 'Bring your Google Analytics history, send raw data to BigQuery, and avoid ad blockers.',
            'steps' => [
                ['Import from Google Analytics', 'On the site’s page, choose Connect Google Analytics, then pick the GA4 property and dates. Only days before your site’s own data are imported.'],
                ['Raw data export', 'Under Raw data export, choose one of the project’s storage buckets. Each night, the previous day’s events are written as gzipped JSON lines, one file per day, ready for BigQuery or Athena.'],
                ['From your server', 'Send pageviews and events from your backend with an API token that has the Analytics write scope: POST /api/v1/analytics/sites/{site}/events, or analyticsEvents() in the PHP and JavaScript SDKs. Include each visitor’s IP address and browser so they’re counted like browser visits.'],
                ['Your own domain', 'Under Send through your own domain, copy the proxy rules for Caddy or Nginx and the matching snippet, so the tracker loads from your site and ad blockers don’t stop it.'],
            ],
        ],
        ...((bool) env('AUDIT_ENABLED', false) ? [
            'run-an-audit' => [
                'group' => 'audit',
                'title' => 'Run an audit of your site',
                'summary' => 'Watch a simulated visitor try real tasks on your site and your competitors’, and see what to improve.',
                'steps' => [
                    ['Turn on Audit', 'On the project’s overview, choose Turn on Audit. It appears in the project’s sidebar.'],
                    ['Add your site', 'Choose New audit and enter your site’s address. Pick up to five tasks for the visitor to try, such as finding the price or signing up, or describe your own.'],
                    ['Choose competitors', 'Add the sites people compare you with, or choose Suggest competitors and pick from the list. Your plan sets how many you can compare with.'],
                    ['Read the report', 'The first report is ready in a few minutes. It scores your site and each competitor on navigation, conversion, clarity, trust, speed, accessibility, search and mobile, and lists what to fix first.'],
                    ['Look at the evidence', 'Each finding shows the screen where the visitor met the problem, with it outlined. The most important ones come with a mock-up of the fix. Open a journey to replay every step and read why the visitor did what they did.'],
                    ['Run it again', 'Choose Run audit after you change your site, or set the audit to run every month or week (Pro and Business plans) to see whether the changes helped.'],
                ],
            ],
            'audit-bot' => [
                'group' => 'audit',
                'title' => 'About the BuildPusher Audit visitor',
                'summary' => 'What the BuildPusherAudit user agent is, what it does on your site, and how to stop it.',
                'steps' => [
                    ['What it is', 'BuildPusherAudit is a headless Chromium browser. A BuildPusher customer asked it to try tasks on their site or on sites they compare themselves with, such as finding the price, the way a first-time visitor would.'],
                    ['What it does', 'It opens public pages only, at most about two a second and a few dozen per audit. It never submits a purchase, payment or sign-up, and when a form needs details it types obviously fake ones (Alex Example, alex@example.com).'],
                    ['How it identifies itself', 'Its user agent contains “BuildPusherAudit/1.0” and a link to this page.'],
                    ['How to stop it', 'Add a robots.txt group for BuildPusherAudit (or for every user agent) that disallows the pages you don’t want visited. Audits read robots.txt before every page and skip what it disallows.'],
                ],
            ],
        ] : []),
    ],
];
