<?php

namespace App\Http\Controllers;

use App\Models\Provider;
use App\Models\Repository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class RepositoryWebhookSettingsController extends Controller
{
    public function store(Request $request, Repository $repository): RedirectResponse
    {
        $this->authorize('update', $repository);
        $repository->loadMissing('provider');

        if ($repository->provider->provider === Provider::TYPE_GITLAB) {
            $secret = $request->validate([
                'signing_token' => [
                    'required',
                    'string',
                    'max:512',
                    function (string $attribute, mixed $value, \Closure $fail): void {
                        $encoded = is_string($value) && str_starts_with($value, 'whsec_')
                            ? substr($value, 6)
                            : '';
                        $decoded = base64_decode($encoded, true);
                        if ($decoded === false || strlen($decoded) < 16) {
                            $fail(__('Enter the whsec_ signing token generated by GitLab.'));
                        }
                    },
                ],
            ])['signing_token'];
        } else {
            $secret = Str::random(64);
            session()->flash("repository:{$repository->id}:webhook_secret", $secret);
        }

        $repository->update([
            'webhook_enabled' => true,
            'webhook_secret' => $secret,
        ]);

        return redirect(route('repositories.show', $repository).'#deployment-webhook')
            ->with('success', __('Deployment webhook enabled.'));
    }

    public function destroy(Repository $repository): RedirectResponse
    {
        $this->authorize('update', $repository);
        $repository->update([
            'webhook_enabled' => false,
            'webhook_secret' => null,
            'webhook_pending' => false,
        ]);

        return redirect(route('repositories.show', $repository).'#deployment-webhook')
            ->with('success', __('Deployment webhook disabled.'));
    }
}
