<x-layouts.app>
    <x-layouts.partials.heading icon="information-circle" :title="__('Product feedback')" :description="__('Report a bug, share an idea, or tell us where the product became confusing.')" />

    <div class="mt-8 grid gap-6 xl:grid-cols-[22rem_1fr]">
        <section class="rounded-2xl border border-primary bg-primary p-5">
            <h2 class="text-lg font-black text-primary">{{ __('Send private feedback') }}</h2>
            <p class="mt-1 text-sm leading-6 text-secondary">{{ __('Visible only to you and workspace administrators. Never include passwords, tokens, private keys, or environment values.') }}</p>
            <form method="POST" action="{{ route('feedback.store') }}" class="mt-5 space-y-3">@csrf
                <div class="grid grid-cols-2 gap-3"><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Type') }}</span><select name="category" class="input secondary mt-1 rounded-sm">@foreach(\App\Models\ProductFeedback::CATEGORIES as $value)<option value="{{ $value }}">{{ str($value)->headline() }}</option>@endforeach</select></label><label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Impact') }}</span><select name="severity" class="input secondary mt-1 rounded-sm">@foreach(\App\Models\ProductFeedback::SEVERITIES as $value)<option value="{{ $value }}" @selected($value==='normal')>{{ str($value)->headline() }}</option>@endforeach</select></label></div>
                <label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Summary') }}</span><input name="title" maxlength="160" required value="{{ old('title') }}" class="input secondary mt-1 rounded-sm" placeholder="{{ __('What happened or should change?') }}"></label>
                <label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Details') }}</span><textarea name="description" rows="5" maxlength="10000" required class="input secondary mt-1 rounded-sm" placeholder="{{ __('Describe the outcome you expected and what you saw.') }}">{{ old('description') }}</textarea></label>
                <label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Steps to reproduce (optional)') }}</span><textarea name="reproduction_steps" rows="4" maxlength="10000" class="input secondary mt-1 rounded-sm" placeholder="1. Open…">{{ old('reproduction_steps') }}</textarea></label>
                <label><span class="block text-xs font-bold uppercase text-secondary">{{ __('Related page (optional)') }}</span><input name="page" maxlength="500" value="{{ old('page', request()->query('from')) }}" class="input secondary mt-1 rounded-sm font-mono" placeholder="/projects/12"></label>
                <x-forms.errors name="category" /><x-forms.errors name="severity" /><x-forms.errors name="title" /><x-forms.errors name="description" /><x-forms.errors name="reproduction_steps" /><x-forms.errors name="page" />
                <button type="submit" class="button primary w-full">{{ __('Submit feedback') }}</button>
            </form>
        </section>

        <section>
            <form method="GET" class="mb-4 flex flex-wrap gap-2"><select name="status" class="input secondary rounded-sm"><option value="">{{ __('Every status') }}</option>@foreach(\App\Models\ProductFeedback::STATUSES as $value)<option value="{{ $value }}" @selected($status===$value)>{{ str($value)->headline() }}</option>@endforeach</select><select name="category" class="input secondary rounded-sm"><option value="">{{ __('Every type') }}</option>@foreach(\App\Models\ProductFeedback::CATEGORIES as $value)<option value="{{ $value }}" @selected($category===$value)>{{ str($value)->headline() }}</option>@endforeach</select><button type="submit" class="button secondary">{{ __('Filter') }}</button>@if($status || $category)<a href="{{ route('feedback.index') }}" class="button tertiary">{{ __('Clear') }}</a>@endif</form>
            <div class="space-y-4">@forelse($feedback as $item)<article class="rounded-2xl border border-primary bg-primary p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><div class="flex flex-wrap gap-2 text-[11px] font-bold uppercase"><span class="rounded-full bg-secondary px-2 py-1 text-secondary">{{ str($item->category)->headline() }}</span><span class="rounded-full bg-secondary px-2 py-1 text-secondary">{{ str($item->severity)->headline() }}</span><span class="rounded-full bg-ternary px-2 py-1 text-white">{{ str($item->status)->headline() }}</span></div><h2 class="mt-3 text-lg font-black text-primary">{{ $item->title }}</h2><p class="mt-1 text-xs text-secondary">{{ __('Submitted by :name :time', ['name'=>$item->submitter->name,'time'=>$item->created_at->diffForHumans()]) }}@if($item->page) · <code>{{ $item->page }}</code>@endif</p></div><form method="POST" action="{{ route('feedback.destroy',$item) }}">@csrf @method('DELETE')<button type="submit" class="button tertiary" onclick="return confirm({{ Illuminate\Support\Js::from(__('Remove this feedback permanently?')) }})">{{ __('Delete') }}</button></form></div><p class="mt-4 whitespace-pre-wrap text-sm leading-6 text-secondary">{{ $item->description }}</p>@if($item->reproduction_steps)<details class="mt-3"><summary class="cursor-pointer text-sm font-bold text-ternary">{{ __('Reproduction steps') }}</summary><p class="mt-2 whitespace-pre-wrap rounded-lg bg-secondary p-3 text-sm text-primary">{{ $item->reproduction_steps }}</p></details>@endif @if($item->review_response)<div class="mt-4 rounded-xl border border-primary bg-secondary p-4"><p class="text-xs font-bold uppercase text-secondary">{{ __('Workspace response') }}</p><p class="mt-2 whitespace-pre-wrap text-sm text-primary">{{ $item->review_response }}</p></div>@endif @if($canReview)<details class="mt-4"><summary class="cursor-pointer text-sm font-bold text-ternary">{{ __('Review feedback') }}</summary><form method="POST" action="{{ route('feedback.update',$item) }}" class="mt-3 space-y-3">@csrf @method('PATCH')<select name="status" class="input secondary rounded-sm">@foreach(\App\Models\ProductFeedback::STATUSES as $value)<option value="{{ $value }}" @selected($item->status===$value)>{{ str($value)->headline() }}</option>@endforeach</select><textarea name="review_response" rows="3" maxlength="10000" class="input secondary rounded-sm" placeholder="{{ __('Decision, workaround, or planned resolution') }}">{{ $item->review_response }}</textarea><button type="submit" class="button primary">{{ __('Save review') }}</button></form></details>@endif</article>@empty<div class="rounded-2xl border border-dashed border-primary bg-primary p-8 text-center"><h2 class="font-black text-primary">{{ __('No matching feedback') }}</h2><p class="mt-2 text-sm text-secondary">{{ __('Submitted feedback will appear here without exposing its content in notifications or exports.') }}</p></div>@endforelse</div>
            <div class="mt-5">{{ $feedback->links() }}</div>
        </section>
    </div>
</x-layouts.app>
